Repository amplication/amplication, pull requests merged in 2020-09, with the labels that each got.

#399 Resolve client warnings
  packages/amplication-client/src/Application/Applications.tsx
  packages/amplication-client/src/Components/EditableTitleField.tsx
  packages/amplication-client/src/Components/TextField.tsx
  packages/amplication-client/src/Entity/EntityFieldList.tsx
  packages/amplication-client/src/Entity/EntityList.tsx
  packages/amplication-client/src/Entity/EntityListItem.tsx
  packages/amplication-client/src/Layout/FloatingToolbar.tsx
  packages/amplication-client/src/Permissions/EntityPermissionFields.tsx
  packages/amplication-client/src/Settings/RoleList.tsx
  packages/amplication-client/src/VersionControl/BuildNewVersion.tsx
  packages/amplication-client/src/VersionControl/NextBuild.tsx
  packages/amplication-server/src/core/permissions/permissions.service.spec.ts
Labels: bug

#400 Code review fixes
  packages/amplication-client/src/App.tsx
  packages/amplication-client/src/Application/ApplicationCard.tsx
  packages/amplication-client/src/Application/Applications.tsx
  packages/amplication-client/src/Components/PanelCollapsible.scss
  packages/amplication-client/src/Permissions/EntityPermissionAction.tsx
  packages/amplication-client/src/VersionControl/ActionLog.tsx
Labels: bug

#401 Move functions from build.consumer to action.service
  packages/amplication-server/src/core/action/action.service.ts
  packages/amplication-server/src/core/action/dto/CompleteStepArgs.ts
  packages/amplication-server/src/core/action/dto/CreateLogArgs.ts
  packages/amplication-server/src/core/action/dto/CreateStepArgs.ts
  packages/amplication-server/src/core/action/dto/index.ts
  packages/amplication-server/src/core/build/build.consumer.spec.ts
  packages/amplication-server/src/core/build/build.consumer.ts
  packages/amplication-server/src/core/build/build.module.ts
  packages/amplication-server/src/schema.graphql
Labels: enhancement

#405 Multi-step log
  packages/amplication-client/src/Layout/FloatingToolbar.scss
  packages/amplication-client/src/VersionControl/ActionLog.scss
  packages/amplication-client/src/VersionControl/ActionLog.tsx
  packages/amplication-server/src/core/action/action.service.ts
  packages/amplication-server/src/core/build/build.service.spec.ts
  packages/amplication-server/src/core/build/build.service.ts
Labels: enhancement

#406 Sticky elements
  packages/amplication-client/src/Layout/PageContent.scss
  packages/amplication-client/src/Layout/Sidebar.scss
  packages/amplication-client/src/VersionControl/ActionLog.scss
  packages/amplication-client/src/VersionControl/AppControlToolbar.scss
  packages/amplication-client/src/VersionControl/Builds.scss
  packages/amplication-client/src/VersionControl/Builds.tsx
  packages/amplication-client/src/style/css-variables.css
  packages/amplication-client/src/style/mixin.scss
  packages/amplication-client/src/style/parameters.scss
Labels: enhancement

#402 Form component
  packages/amplication-client/src/Components/Form.scss
  packages/amplication-client/src/Components/Form.tsx
  packages/amplication-client/src/Entity/EntityFieldForm.tsx
  packages/amplication-client/src/Entity/SchemaFields.tsx
  packages/amplication-client/src/Settings/RoleForm.tsx
  packages/amplication-client/src/User/Login.tsx
Labels: enhancement

#407 Command palette style
  packages/amplication-client/src/App.tsx
  packages/amplication-client/src/CommandPalette/CommandPalette.scss
  packages/amplication-client/src/CommandPalette/CommandPalette.tsx
  packages/amplication-client/src/Layout/MainLayout.tsx
  packages/amplication-client/src/User/User.tsx
Labels: enhancement

#403 Action log steps
  packages/amplication-client/src/VersionControl/ActionLog.scss
  packages/amplication-client/src/VersionControl/ActionLog.tsx
  packages/amplication-client/src/VersionControl/BuildNewVersion.tsx
  packages/amplication-server/src/core/action/action.service.ts
  packages/amplication-server/src/core/build/build.service.spec.ts
  packages/amplication-server/src/core/build/build.service.ts
Labels: enhancement

#414 Center application list when less than 3
  packages/amplication-client/src/Application/Applications.scss
  packages/amplication-client/src/Application/Applications.tsx
Labels: bug

#408 show failed steps
  packages/amplication-client/src/VersionControl/ActionLog.tsx
  packages/amplication-server/src/core/build/build.consumer.ts
Labels: enhancement

#411 Clear cache on logout
  packages/amplication-client/src/Layout/MainLayout.tsx
  packages/amplication-client/src/User/Login.tsx
Labels: bug

#346 Added 'None' option to page-type>navigate-to in Entity Page
  packages/amplication-client/src/Components/SelectField.tsx
  packages/amplication-client/src/Pages/EntityPageForm.tsx
  packages/amplication-client/src/Pages/PageSelectField.tsx
  packages/amplication-server/src/core/entityPage/dto/EntityPageCreateInput.ts
  packages/amplication-server/src/core/entityPage/dto/EntityPageUpdateInput.ts
  packages/amplication-server/src/schema.graphql
Labels: enhancement

#413 Create sample app with new organizations
  packages/amplication-server/src/core/app/app.service.spec.ts
  packages/amplication-server/src/core/app/app.service.ts
  packages/amplication-server/src/core/auth/auth.service.spec.ts
  packages/amplication-server/src/core/auth/auth.service.ts
  packages/amplication-server/src/core/entity/constants.ts
  packages/amplication-server/src/core/entity/entity.service.ts
  packages/amplication-server/src/core/organization/initialAppData.ts
  packages/amplication-server/src/core/organization/organization.module.ts
  packages/amplication-server/src/core/organization/organization.service.spec.ts
  packages/amplication-server/src/core/organization/organization.service.ts
Labels: enhancement

#419 GCS
  packages/amplication-server/.env
  packages/amplication-server/src/core/storage/gcs.disk.service.spec.ts
  packages/amplication-server/src/core/storage/gcs.disk.service.ts
  packages/amplication-server/src/core/storage/local.disk.service.spec.ts
  packages/amplication-server/src/core/storage/local.disk.service.ts
  packages/amplication-server/src/core/storage/local.disk.ts
  packages/amplication-server/src/core/storage/root-storage.module.ts
  packages/amplication-server/src/core/storage/storage-options.module.ts
  packages/amplication-server/src/core/storage/storage-options.service.ts
  terraform/envs/dev/main.tf
  terraform/envs/dev/terraform.tfvars
  terraform/envs/dev/variables.tf
  terraform/envs/production/main.tf
  terraform/envs/production/terraform.tfvars
  terraform/envs/production/variables.tf
  terraform/modules/env_baseline/main.tf
  terraform/modules/env_baseline/variables.tf
Labels: enhancement

#424 Update README.md and add a link to discord channel
  README.md
  code_of_conduct.md
  package-lock.json
Labels: type: docs

#425 Add CONTRIBUTING.md
  CONTRIBUTING.md
Labels: type: docs

#423 Password service tests
  packages/amplication-server/src/core/account/password.service.spec.ts
Labels: type: enhancement

#429 dep: update packages
  package-lock.json
  package.json
  packages/amplication-server/package-lock.json
  packages/amplication-server/package.json
Labels: type: dependencies

#438 Improve Build Service Test
  packages/amplication-server/src/core/build/build.service.spec.ts
  packages/amplication-server/src/core/build/build.service.ts
Labels: type: test

#434 Set formatOnSave to true by default in VSCode
  .vscode/settings.json
Labels: type: enhancement

#435 Add file utils to recommended VSCode extensions
  .vscode/extensions.json
Labels: type: enhancement

#437 Remove memorystore variables from Terraform
  terraform/envs/dev/main.tf
  terraform/envs/dev/terraform.tfvars
  terraform/envs/dev/variables.tf
  terraform/envs/production/main.tf
  terraform/envs/production/terraform.tfvars
  terraform/envs/production/variables.tf
  terraform/modules/env_baseline/variables.tf
Labels: type: chore

#443 Remove static users module from generated app
  packages/amplication-data-service-generator/src/static/auth/auth.module.ts
  packages/amplication-data-service-generator/src/static/auth/auth.service.spec.ts
  packages/amplication-data-service-generator/src/static/auth/auth.service.ts
  packages/amplication-data-service-generator/src/static/users/users.module.ts
  packages/amplication-data-service-generator/src/static/users/users.service.spec.ts
  packages/amplication-data-service-generator/src/static/users/users.service.ts
  packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
  packages/amplication-data-service-generator/test/data-service-generator.e2e-spec.ts
Labels: type: bug

#446 Fix action service DB work
  packages/amplication-server/src/core/action/action.service.spec.ts
  packages/amplication-server/src/core/action/action.service.ts
  packages/amplication-server/src/core/build/build.service.spec.ts
  packages/amplication-server/src/core/build/build.service.ts
Labels: type: bug

#447 Improve logs of data service generator
  packages/amplication-data-service-generator/src/create-data-service.ts
  packages/amplication-data-service-generator/src/resource/create-resource.ts
Labels: type: enhancement

#431 Show user initials based on email address
  packages/amplication-server/src/core/auth/auth.service.ts
Labels: type: bug

#432 Pending changes icon
  packages/amplication-client/src/Entity/EntityListItem.tsx
  packages/amplication-client/src/VersionControl/AppControlToolbar.tsx
  packages/amplication-client/src/VersionControl/LockStatus.scss
  packages/amplication-client/src/VersionControl/LockStatus.tsx
  packages/amplication-client/src/VersionControl/LockStatusIcon.scss
  packages/amplication-client/src/VersionControl/LockStatusIcon.tsx
Labels: type: enhancement

#452 feat(client): sign in page
  packages/amplication-client/src/Layout/WelcomePage.scss
  packages/amplication-client/src/Layout/WelcomePage.tsx
  packages/amplication-client/src/User/GitHubLoginButton.scss
  packages/amplication-client/src/User/GitHubLoginButton.tsx
  packages/amplication-client/src/User/Login.scss
  packages/amplication-client/src/User/Login.tsx
  packages/amplication-client/src/assets/fonts/amplicationicon.eot
  packages/amplication-client/src/assets/fonts/amplicationicon.svg
  packages/amplication-client/src/assets/fonts/amplicationicon.ttf
  packages/amplication-client/src/assets/fonts/amplicationicon.woff
Labels: type: enhancement

#453 Update icons
  packages/amplication-client/src/Components/Dialog.tsx
  packages/amplication-client/src/Components/TextField.tsx
  packages/amplication-client/src/VersionControl/ActionLog.tsx
  packages/amplication-client/src/VersionControl/BuildList.tsx
  packages/amplication-client/src/VersionControl/LockStatusIcon.tsx
  packages/amplication-client/src/assets/fonts/amplicationicon.eot
  packages/amplication-client/src/assets/fonts/amplicationicon.svg
  packages/amplication-client/src/assets/fonts/amplicationicon.ttf
  packages/amplication-client/src/assets/fonts/amplicationicon.woff
Labels: type: bug

#445 Added should validate test to jsonSchemaValidation service
  packages/amplication-server/src/services/jsonSchemaValidation.service.spec.ts
Labels: type: enhancement

#460 Fix entityVersions and fieldPermanentId
  packages/amplication-client/src/Entity/EntityList.tsx
  packages/amplication-client/src/Entity/EntityListItem.tsx
  packages/amplication-client/src/VersionControl/PendingChangeDiff.tsx
  packages/amplication-client/src/models.ts
  packages/amplication-data-service-generator/src/models.ts
  packages/amplication-data-service-generator/src/types.ts
  packages/amplication-data/src/models.ts
  packages/amplication-server/src/core/entity/dto/EntityFieldOrderByInput.ts
  packages/amplication-server/src/core/entity/dto/EntityFieldWhereInput.ts
  packages/amplication-server/src/core/entity/entity.resolver.ts
  packages/amplication-server/src/schema.graphql
Labels: type: bug

#458 Client: Validate Entity Name
  packages/amplication-client/src/Components/NameField.scss
  packages/amplication-client/src/Components/NameField.tsx
  packages/amplication-client/src/Components/SelectField.tsx
  packages/amplication-client/src/Components/TextField.tsx
  packages/amplication-client/src/Components/TextInput.scss
  packages/amplication-client/src/Components/TextInput.tsx
  packages/amplication-client/src/Entity/Entity.scss
  packages/amplication-client/src/Entity/EntityForm.tsx
  packages/amplication-client/src/Entity/NewEntity.tsx
  packages/amplication-client/src/Entity/OptionSet.scss
  packages/amplication-client/src/Settings/RoleList.scss
  packages/amplication-data-service-generator/src/resource/create-resource.ts
  packages/amplication-data-service-generator/src/util/entity.ts
  packages/amplication-server/src/core/entity/constants.ts
Labels: type: bug

#463 Fix missing step completion time
  packages/amplication-server/src/core/action/action.service.spec.ts
  packages/amplication-server/src/core/action/action.service.ts
  packages/amplication-server/src/core/build/build.service.spec.ts
  packages/amplication-server/src/core/build/build.service.ts
Labels: type: bug

#461 Use nestjs-prisma in amplication-data-service-generator
  packages/amplication-data-service-generator/package-lock.json
  packages/amplication-data-service-generator/package.json
  packages/amplication-data-service-generator/src/resource/module/module.template.ts
  packages/amplication-data-service-generator/src/resource/service/service.template.ts
  packages/amplication-data-service-generator/src/static/package-lock.json
  packages/amplication-data-service-generator/src/static/package.json
  packages/amplication-data-service-generator/src/static/prisma/prisma.module.ts
  packages/amplication-data-service-generator/src/static/prisma/prisma.service.ts
  packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
Labels: type: enhancement

#462 Add README to generated app
  packages/amplication-data-service-generator/src/static/README.md
  packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
Labels: type: enhancement

#468 Fix auth service call to user service
  packages/amplication-data-service-generator/package.json
  packages/amplication-data-service-generator/src/create-data-service.ts
  packages/amplication-data-service-generator/src/prisma/create-prisma-schema.spec.ts
  packages/amplication-data-service-generator/src/prisma/create-prisma-schema.ts
  packages/amplication-data-service-generator/src/prisma/user-model.ts
  packages/amplication-data-service-generator/src/resource/controller/controller.template.ts
  packages/amplication-data-service-generator/src/resource/dto/create-dto.ts
  packages/amplication-data-service-generator/src/resource/module/module.template.ts
  packages/amplication-data-service-generator/src/resource/test/create-test.ts
  packages/amplication-data-service-generator/src/static/auth/auth.service.ts
  packages/amplication-data-service-generator/src/static/package-lock.json
  packages/amplication-data-service-generator/src/static/package.json
  packages/amplication-data-service-generator/src/static/prisma.util.spec.ts
  packages/amplication-data-service-generator/src/static/prisma.util.ts
  packages/amplication-data-service-generator/src/static/tsconfig.json
  packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
  packages/amplication-data-service-generator/src/types.ts
  packages/amplication-data-service-generator/src/user-entitiy.ts
Labels: type: bug

#469 Client: Fix update build list
  packages/amplication-client/src/VersionControl/ActionLog.tsx
  packages/amplication-client/src/VersionControl/Build.tsx
  packages/amplication-client/src/VersionControl/BuildList.tsx
Labels: type: bug

#472 Data Service Generator: Lookup Types
  .vscode/settings.json
  packages/amplication-data-service-generator/src/resource/dto/create-dto.spec.ts
  packages/amplication-data-service-generator/src/resource/dto/create-dto.ts
  packages/amplication-data-service-generator/src/static/main.ts
  packages/amplication-data-service-generator/src/static/prisma.util.spec.ts
  packages/amplication-data-service-generator/src/static/prisma.util.ts
  packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
  packages/amplication-data-service-generator/src/tests/entities.ts
  packages/amplication-data-service-generator/src/util/ast.spec.ts
  packages/amplication-data-service-generator/src/util/ast.ts
Labels: type: bug

#470 Login page spacing
  packages/amplication-client/src/User/GitHubLoginButton.scss
  packages/amplication-client/src/User/Login.scss
Labels: type: style

#471 CSS fixes
  packages/amplication-client/public/index.html
  packages/amplication-client/src/Application/ApplicationBadge.scss
  packages/amplication-client/src/Application/ApplicationCard.scss
  packages/amplication-client/src/Components/DataGrid.scss
  packages/amplication-client/src/Components/SelectMenu.scss
  packages/amplication-client/src/Layout/MainLayout.scss
  packages/amplication-client/src/VersionControl/AppControlToolbar.scss
  packages/amplication-client/src/style/css-variables.css
  packages/amplication-client/src/style/mixin.scss
Labels: type: style

#482 Move seed outside the generated app
  packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
  packages/amplication-data-service-generator/test/data-service-generator.e2e-spec.ts
  packages/amplication-data-service-generator/test/seed.ts
Labels: priority: critical, type: bug

#483 Fix generated Prisma schema optional fields
  .vscode/settings.json
  packages/amplication-data-service-generator/package-lock.json
  packages/amplication-data-service-generator/package.json
  packages/amplication-data-service-generator/src/prisma/create-prisma-schema.spec.ts
  packages/amplication-data-service-generator/src/prisma/create-prisma-schema.ts
Labels: priority: critical, type: bug

#485 DTO One-to-One Lookup Field
  packages/amplication-data-service-generator/src/resource/controller/controller.template.ts
  packages/amplication-data-service-generator/src/resource/dto/create-dto.spec.ts
  packages/amplication-data-service-generator/src/resource/dto/create-dto.ts
  packages/amplication-data-service-generator/src/static/prisma.util.spec.ts
  packages/amplication-data-service-generator/src/static/prisma.util.ts
  packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
  packages/amplication-data-service-generator/src/tests/entities.ts
Labels: priority: high, type: bug

#478 Detect screen resolution and mobile devices
  packages/amplication-client/package-lock.json
  packages/amplication-client/package.json
  packages/amplication-client/src/App.tsx
  packages/amplication-client/src/Application/ApplicationLayout.tsx
  packages/amplication-client/src/Application/Applications.scss
  packages/amplication-client/src/Application/Applications.tsx
  packages/amplication-client/src/Components/Dialog.scss
  packages/amplication-client/src/Layout/MainLayout.scss
  packages/amplication-client/src/Layout/MainLayout.tsx
  packages/amplication-client/src/Layout/MobileMessage.scss
  packages/amplication-client/src/Layout/MobileMessage.tsx
  packages/amplication-client/src/Layout/PageContent.scss
  packages/amplication-client/src/Layout/ScreenResolutionMessage.scss
  packages/amplication-client/src/Layout/ScreenResolutionMessage.tsx
  packages/amplication-client/src/assets/images/mobile-message-white.svg
  packages/amplication-client/src/assets/images/mobile-message.svg
  packages/amplication-client/src/assets/images/my-apps-bg.svg
  packages/amplication-client/src/style/mixin.scss
  packages/amplication-client/src/style/parameters.scss
Labels: type: enhancement

#455 Build Service Tests
  packages/amplication-server/src/core/build/build.service.spec.ts
Labels: type: enhancement

#486 fix(client): improve mobile message
  packages/amplication-client/src/Layout/MobileMessage.scss
  packages/amplication-client/src/Layout/MobileMessage.tsx
Labels: type: style

#488 Fix entity field properties
  packages/amplication-client/src/Entity/DataTypeSelectField.tsx
Labels: type: bug

#491 Show saved properties on selected field change
  packages/amplication-client/src/Entity/DataTypeSelectField.tsx
  packages/amplication-client/src/Entity/EntityField.tsx
  packages/amplication-client/src/Entity/EntityFieldForm.tsx
Labels: type: bug

#494 Add Analytics Events
  packages/amplication-client/src/Application/NewApplication.tsx
  packages/amplication-client/src/Components/Button.tsx
  packages/amplication-client/src/Entity/Entity.tsx
  packages/amplication-client/src/Entity/EntityField.tsx
  packages/amplication-client/src/Entity/NewEntity.tsx
  packages/amplication-client/src/Entity/NewEntityField.tsx
  packages/amplication-client/src/User/GitHubLoginButton.tsx
  packages/amplication-client/src/User/Login.tsx
  packages/amplication-client/src/VersionControl/BuildNewVersion.tsx
  packages/amplication-client/src/VersionControl/Commit.tsx
  packages/amplication-client/src/util/analytics.ts
Labels: type: enhancement

#495 Sample app build
  packages/amplication-server/src/core/entity/entity.service.ts
Labels: type: bug

#496 Menu items style
  packages/amplication-client/src/Application/ApplicationLayout.tsx
  packages/amplication-client/src/CommandPalette/CommandPalette.scss
  packages/amplication-client/src/CommandPalette/CommandPalette.tsx
  packages/amplication-client/src/Layout/MainLayout.scss
  packages/amplication-client/src/Layout/MainLayout.tsx
  packages/amplication-client/src/Layout/MenuItem.scss
  packages/amplication-client/src/Layout/MenuItem.tsx
Labels: type: bug, type: style

#512 Fix TextInput error style
  packages/amplication-client/src/Components/TextInput.scss
  packages/amplication-client/src/Components/TextInput.tsx
Labels: type: bug

#516 Add user badge tooltip
  packages/amplication-client/src/Components/UserBadge.tsx
  packages/amplication-client/src/Entity/NewEntity.tsx
Labels: type: bug

#514 Fix entity plural display name
  packages/amplication-client/src/Entity/NewEntity.tsx
Labels: type: bug

#522 Fix toggle button visible in FireFox
  packages/amplication-client/src/Components/ToggleButton.scss
Labels: type: bug

#511 Forms JSON Schema validation
  packages/amplication-client/src/Application/ApplicationForm.tsx
  packages/amplication-client/src/Application/NewApplication.tsx
  packages/amplication-client/src/Entity/EntityFieldForm.tsx
  packages/amplication-client/src/Entity/EntityForm.tsx
  packages/amplication-client/src/Entity/NewEntity.tsx
  packages/amplication-client/src/Entity/NewEntityField.tsx
  packages/amplication-client/src/Settings/NewRole.tsx
  packages/amplication-client/src/Settings/RoleForm.tsx
  packages/amplication-client/src/VersionControl/BuildNewVersion.tsx
  packages/amplication-client/src/VersionControl/Commit.tsx
  packages/amplication-client/src/util/formikValidateJsonSchema.ts
Labels: type: enhancement

#523 Refactor - entity version clone data
  packages/amplication-server/src/core/entity/entity.service.spec.ts
  packages/amplication-server/src/core/entity/entity.service.ts
Labels: type: refactor
