Repository amplication/amplication, pull requests merged in 2020-11, with the labels that each got.

#732 Style applications list
  packages/amplication-client/src/Application/Applications.scss
Labels: type: style

#728 Design system
  packages/amplication-design-system/.storybook/main.js
  packages/amplication-design-system/.storybook/preview.js
  packages/amplication-design-system/package-lock.json
  packages/amplication-design-system/package.json
  packages/amplication-design-system/src/components/Button.scss
  packages/amplication-design-system/src/components/Button.tsx
  packages/amplication-design-system/src/components/CircleIcon.scss
  packages/amplication-design-system/src/components/CircleIcon.tsx
  packages/amplication-design-system/src/components/TextInput.scss
  packages/amplication-design-system/src/components/TextInput.stories.tsx
  packages/amplication-design-system/src/components/TextInput.tsx
  packages/amplication-design-system/src/index.scss
  packages/amplication-design-system/src/style/amplication-font.scss
  packages/amplication-design-system/src/style/css-variables.css
  packages/amplication-design-system/src/style/index.scss
  packages/amplication-design-system/src/style/mixin.scss
  packages/amplication-design-system/src/style/parameters.scss
  packages/amplication-design-system/tsconfig.json
Labels: type: enhancement

#740 Add missing import
  packages/amplication-client/src/index.tsx
Labels: priority: critical, type: bug

#743 Fix client caching issue with new ApolloClient
  packages/amplication-client/src/Entity/EntityFieldList.tsx
  packages/amplication-client/src/Entity/EntityFieldListItem.tsx
  packages/amplication-client/src/Entity/EntityList.tsx
  packages/amplication-client/src/Entity/EntityListItem.tsx
  packages/amplication-client/src/Entity/NewEntity.tsx
  packages/amplication-client/src/Entity/NewEntityField.tsx
  packages/amplication-client/src/Roles/NewRole.tsx
  packages/amplication-client/src/Roles/RoleList.tsx
Labels: type: bug

#746 DSG - Add AppInfo object
  packages/amplication-data-service-generator/src/create-data-service.ts
  packages/amplication-data-service-generator/src/tests/appInfo.ts
  packages/amplication-data-service-generator/src/tests/create-data-service.spec.ts
  packages/amplication-data-service-generator/src/types.ts
  packages/amplication-server/src/core/app/app.module.ts
  packages/amplication-server/src/core/build/build.module.ts
  packages/amplication-server/src/core/build/build.service.spec.ts
  packages/amplication-server/src/core/build/build.service.ts
  packages/amplication-server/src/core/entity/entity.service.ts
Labels: type: enhancement

#749 Fix - Compare shows false changes on entity permissions
  packages/amplication-server/src/core/entity/entity.service.ts
Labels: type: bug

#751 Add missing AuthorizeContext attributes
  packages/amplication-server/src/core/app/app.resolver.ts
  packages/amplication-server/src/core/entity/entity.resolver.ts
  packages/amplication-server/src/core/organization/organization.resolver.ts
  packages/amplication-server/src/core/permissions/permissions.service.ts
  packages/amplication-server/src/core/user/user.resolver.ts
  packages/amplication-server/src/enums/AuthorizableResourceParameter.ts
  packages/amplication-server/src/schema.graphql
Labels: type: bug

#750 DSG: Swagger Responses
  .vscode/launch.json
  packages/amplication-data-service-generator/scripts/generate-test-data-service.ts
  packages/amplication-data-service-generator/src/resource/controller/controller.template.ts
  packages/amplication-data-service-generator/src/resource/controller/create-controller.ts
  packages/amplication-data-service-generator/src/static/errors.ts
  packages/amplication-data-service-generator/src/static/prisma.util.spec.ts
  packages/amplication-data-service-generator/src/static/prisma.util.ts
  packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
  packages/amplication-data-service-generator/test/data-service-generator.e2e-spec.ts
Labels: type: bug, type: enhancement

#722 Add tests for Build Service
  packages/amplication-server/src/core/build/build.service.spec.ts
  packages/amplication-server/src/core/build/build.service.ts
Labels: type: enhancement

#756 Add UserEntity related tests to AppResolver
  packages/amplication-server/src/core/app/app.resolver.spec.ts
Labels: type: enhancement

#753 Entity get fields
  packages/amplication-server/src/core/entity/entity.resolver.spec.ts
  packages/amplication-server/src/core/entity/entity.resolver.ts
  packages/amplication-server/src/core/entity/entity.service.spec.ts
  packages/amplication-server/src/core/entity/entity.service.ts
  packages/amplication-server/src/core/entity/entityVersion.resolver.ts
Labels: type: bug

#759 Swagger UI
  packages/amplication-data-service-generator/src/static/main.ts
  packages/amplication-data-service-generator/src/static/static/assets/logo-amplication-white.svg
  packages/amplication-data-service-generator/src/static/static/swagger.css
  packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
Labels: type: enhancement

#771 Fix DSG swagger options
  packages/amplication-data-service-generator/src/static/main.ts
  packages/amplication-data-service-generator/src/swagger.template.ts
  packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
Labels: priority: critical, type: bug

#765 Fix related entities issue
  packages/amplication-data-service-generator/src/prisma/create-prisma-schema.ts
  packages/amplication-data-service-generator/src/resource/test/create-test.ts
  packages/amplication-server/src/core/entity/entity.service.ts
Labels: priority: critical, type: bug

#772 Field display name
  packages/amplication-server/src/core/entity/entity.service.ts
Labels: type: bug

#773 Navigate to related entity
  packages/amplication-client/src/Components/DataGrid.scss
  packages/amplication-client/src/Entity/EntityFieldList.tsx
  packages/amplication-client/src/Entity/EntityFieldListItem.tsx
  packages/amplication-client/src/Entity/NewEntityField.tsx
Labels: type: enhancement

#778 Swagger Instructions
  packages/amplication-data-service-generator/src/create-data-service.ts
  packages/amplication-data-service-generator/src/create-swagger.ts
  packages/amplication-data-service-generator/src/static/nest-cli.json
  packages/amplication-data-service-generator/src/static/package.json
  packages/amplication-data-service-generator/src/static/scripts/copy-files.ts
  packages/amplication-data-service-generator/src/static/static/assets/favicon.png
  packages/amplication-data-service-generator/src/static/static/swagger.css
  packages/amplication-data-service-generator/src/swagger/create-swagger.spec.ts
  packages/amplication-data-service-generator/src/swagger/create-swagger.ts
  packages/amplication-data-service-generator/src/swagger/swagger.template.ts
  packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
Labels: type: enhancement

#758 Add tests for Auth Resolver
  packages/amplication-server/src/core/account/account.resolver.spec.ts
  packages/amplication-server/src/core/account/account.resolver.ts
  packages/amplication-server/src/core/auth/auth.resolver.spec.ts
  packages/amplication-server/src/core/auth/auth.resolver.ts
  packages/amplication-server/src/core/auth/auth.service.spec.ts
  packages/amplication-server/src/core/auth/auth.service.ts
  packages/amplication-server/src/core/auth/dto/ChangePasswordArgs.ts
  packages/amplication-server/src/core/auth/dto/LoginArgs.ts
  packages/amplication-server/src/core/auth/dto/SetCurrentOrganizationArgs.ts
  packages/amplication-server/src/core/auth/dto/SignupArgs.ts
  packages/amplication-server/src/core/auth/dto/change-password.input.ts
  packages/amplication-server/src/core/auth/dto/index.ts
  packages/amplication-server/src/core/auth/dto/login.input.ts
  packages/amplication-server/src/core/auth/dto/signup.input.ts
  packages/amplication-server/src/models/Account.ts
  packages/amplication-server/src/models/auth.ts
  packages/amplication-server/src/schema.graphql
Labels: type: test

#784 Add tests for Commit Resolver
  packages/amplication-server/src/core/app/app.resolver.spec.ts
Labels: type: test

#785 Add tests for Organization resolver
  packages/amplication-server/src/core/organization/organization.resolver.spec.ts
Labels: type: test

#788 Add all tests for Build Resolver
  packages/amplication-server/src/core/build/build.resolver.spec.ts
Labels: type: test

#783 Update README.md prerequisite installs
  packages/amplication-server/README.md
Labels: type: docs

#790 Fix Message from optional to required
  packages/amplication-server/src/core/build/dto/BuildCreateInput.ts
Labels: type: enhancement

#794 Fix circular ref
  packages/amplication-server/src/core/auth/auth.service.ts
  packages/amplication-server/src/core/build/build.resolver.spec.ts
Labels: type: bug

#787 Side bar close button
  packages/amplication-client/src/Components/DataGrid.scss
  packages/amplication-client/src/Layout/Sidebar.scss
  packages/amplication-client/src/Layout/SidebarHeader.tsx
  packages/amplication-client/src/Roles/NewRole.tsx
  packages/amplication-client/src/style/css-variables.css
Labels: type: style

#795 Server: Add Tests & Methods to Entity Resolver & Service
  packages/amplication-server/src/core/entity/entity.resolver.spec.ts
Labels: type: enhancement, type: test

#802 Server: Build on Commit Tests
  packages/amplication-server/src/core/app/app.service.spec.ts
  packages/amplication-server/src/core/build/build.service.spec.ts
Labels: type: test

#801 Rebuild layout for new commit flow
  packages/amplication-client/src/Application/ApplicationIcon.scss
  packages/amplication-client/src/Application/ApplicationLayout.scss
  packages/amplication-client/src/Application/ApplicationLayout.tsx
  packages/amplication-client/src/CommandPalette/CommandPalette.scss
  packages/amplication-client/src/Components/UserAvatar.scss
  packages/amplication-client/src/Layout/FloatingToolbar.tsx
  packages/amplication-client/src/Layout/MainLayout.scss
  packages/amplication-client/src/Layout/MainLayout.tsx
  packages/amplication-client/src/Layout/MenuItem.tsx
  packages/amplication-client/src/VersionControl/AppControlToolbar.scss
  packages/amplication-client/src/VersionControl/AppControlToolbar.tsx
  packages/amplication-client/src/VersionControl/LockStatus.tsx
  packages/amplication-client/src/VersionControl/PendingChangesBar.scss
  packages/amplication-client/src/VersionControl/PendingChangesBar.tsx
  packages/amplication-client/src/VersionControl/PendingChangesStatus.scss
  packages/amplication-client/src/VersionControl/PendingChangesStatus.tsx
Labels: type: enhancement

#803 New menu style
  packages/amplication-client/src/Layout/MainLayout.scss
  packages/amplication-client/src/Layout/MenuItem.scss
  packages/amplication-client/src/assets/logo.svg
  packages/amplication-client/src/style/parameters.scss
Labels: type: style

#804 Server: Add tests coverage for Password Service
  packages/amplication-server/src/core/account/password.service.spec.ts
Labels: type: test

#808 Menu fixed panel
  packages/amplication-client/src/Application/ApplicationLayout.scss
  packages/amplication-client/src/Application/ApplicationLayout.tsx
  packages/amplication-client/src/Layout/MainLayout.scss
  packages/amplication-client/src/Layout/MainLayout.tsx
  packages/amplication-client/src/Layout/MenuItem.scss
  packages/amplication-client/src/Layout/MenuItemWithFixedPanel.tsx
  packages/amplication-client/src/VersionControl/Commit.scss
  packages/amplication-client/src/VersionControl/Commit.tsx
  packages/amplication-client/src/VersionControl/PendingChange.tsx
  packages/amplication-client/src/VersionControl/PendingChanges.scss
  packages/amplication-client/src/VersionControl/PendingChanges.tsx
  packages/amplication-client/src/VersionControl/PendingChangesBar.tsx
  packages/amplication-client/src/style/css-variables.css
  packages/amplication-client/src/util/teleporter.ts
Labels: type: enhancement

#820 Last Build
  packages/amplication-client/src/VersionControl/Build.scss
  packages/amplication-client/src/VersionControl/Build.tsx
  packages/amplication-client/src/VersionControl/Commit.tsx
  packages/amplication-client/src/VersionControl/LastBuild.scss
  packages/amplication-client/src/VersionControl/LastBuild.tsx
  packages/amplication-client/src/VersionControl/PendingChanges.scss
  packages/amplication-client/src/VersionControl/PendingChangesBar.scss
  packages/amplication-client/src/VersionControl/PendingChangesBar.tsx
Labels: enhancement

#823 Pending changes style
  packages/amplication-client/src/Components/TimeSince.scss
  packages/amplication-client/src/Components/TimeSince.tsx
  packages/amplication-client/src/Components/UserAndTime.scss
  packages/amplication-client/src/VersionControl/Commit.scss
  packages/amplication-client/src/VersionControl/Commit.tsx
  packages/amplication-client/src/VersionControl/PendingChange.tsx
  packages/amplication-client/src/VersionControl/PendingChanges.scss
  packages/amplication-client/src/style/css-variables.css
Labels: enhancement

#807 Server: Fix No Account Found Logging Error
  packages/amplication-server/src/core/auth/auth.service.ts
Labels: type: test

#828 Scheduler
  .vscode/tasks.json
  packages/amplication-scheduler/.dockerignore
  packages/amplication-scheduler/.gitignore
  packages/amplication-scheduler/Dockerfile
  packages/amplication-scheduler/README.md
  packages/amplication-scheduler/example/config.json
  packages/amplication-scheduler/example/docker-compose.yaml
  packages/amplication-scheduler/package-lock.json
  packages/amplication-scheduler/package.json
  packages/amplication-scheduler/scripts/generate-help.ts
  packages/amplication-scheduler/src/config.schema.json
  packages/amplication-scheduler/src/get-config.ts
  packages/amplication-scheduler/src/help.ts
  packages/amplication-scheduler/src/index.ts
  packages/amplication-scheduler/src/scheduler.ts
  packages/amplication-scheduler/tsconfig.json
  packages/amplication-server/README.md
  packages/amplication-server/docker-compose.db.yml
  packages/amplication-server/docker-compose.yml
  packages/amplication-server/package.json
Labels: enhancement

#827 Server: Add Commit Resolver
  packages/amplication-server/src/core/app/app.module.ts
  packages/amplication-server/src/core/app/app.resolver.spec.ts
  packages/amplication-server/src/core/app/commit.resolver.ts
  packages/amplication-server/src/core/app/dto/FindManyCommitsArgs.ts
  packages/amplication-server/src/core/commit/commit.module.ts
  packages/amplication-server/src/core/commit/commit.resolver.spec.ts
  packages/amplication-server/src/core/commit/commit.resolver.ts
  packages/amplication-server/src/core/commit/commit.service.spec.ts
  packages/amplication-server/src/core/commit/commit.service.ts
  packages/amplication-server/src/core/commit/dto/CommitOrderByInput.ts
  packages/amplication-server/src/core/commit/dto/CommitWhereInput.ts
  packages/amplication-server/src/core/commit/dto/CommitWhereUniqueInput.ts
  packages/amplication-server/src/core/commit/dto/FindManyCommitArgs.ts
  packages/amplication-server/src/core/commit/dto/FindOneCommitArgs.ts
  packages/amplication-server/src/core/core.module.ts
  packages/amplication-server/src/enums/AuthorizableResourceParameter.ts
  packages/amplication-server/src/schema.graphql
Labels: type: enhancement

#833 DSG: Use namespace imports in controller template
  packages/amplication-data-service-generator/src/resource/controller/controller.template.ts
  packages/amplication-data-service-generator/src/resource/controller/to-many.template.ts
  packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
Labels: type: bug

#834 Server: Fix Remove Background Service Tests
  packages/amplication-server/src/core/build/build.service.spec.ts
  packages/amplication-server/src/core/build/build.service.ts
  packages/amplication-server/src/core/deployment/deployment.service.spec.ts
Labels: type: test

#830 Remove background service
  packages/amplication-server/src/core/background/background-auth.guard.ts
  packages/amplication-server/src/core/background/background-jwt.strategy.ts
  packages/amplication-server/src/core/background/background.module.ts
  packages/amplication-server/src/core/background/background.service.ts
  packages/amplication-server/src/core/build/build.controller.ts
  packages/amplication-server/src/core/build/build.module.ts
  packages/amplication-server/src/core/build/build.service.spec.ts
  packages/amplication-server/src/core/build/build.service.ts
  packages/amplication-server/src/core/deployment/deployment.controller.ts
  packages/amplication-server/src/core/deployment/deployment.module.ts
  packages/amplication-server/src/core/deployment/deployment.service.spec.ts
  packages/amplication-server/src/core/deployment/deployment.service.ts
Labels: enhancement

#831 Update build status
  packages/amplication-server/docker-compose.yml
  packages/amplication-server/src/core/build/build.controller.ts
  packages/amplication-server/src/core/build/build.service.ts
  packages/amplication-server/src/core/core.module.ts
  packages/amplication-server/src/core/system/system.controller.spec.ts
  packages/amplication-server/src/core/system/system.controller.ts
  packages/amplication-server/src/core/system/system.module.ts
Labels: type: enhancement

#835 Update deploy status
  packages/amplication-server/src/core/deployment/deployment.resolver.ts
  packages/amplication-server/src/core/deployment/deployment.service.ts
  packages/amplication-server/src/core/system/system.controller.ts
  packages/amplication-server/src/core/system/system.module.ts
Labels: type: enhancement

#840 Remove time and user from pending changes view
  packages/amplication-client/src/VersionControl/PendingChange.tsx
Labels: type: enhancement

#839 Deploy step name
  packages/amplication-server/migration-scripts/rename-deploy-step-name.ts
  packages/amplication-server/src/core/build/build.service.ts
  packages/amplication-server/src/core/deployment/deployment.service.spec.ts
  packages/amplication-server/src/core/deployment/deployment.service.ts
  packages/amplication-server/src/core/environment/dto/EnvironmentUpdateInput.ts
  packages/amplication-server/src/core/environment/dto/UpdateOneEnvironmentArgs.ts
  packages/amplication-server/src/core/environment/dto/index.ts
  packages/amplication-server/src/core/environment/environment.module.ts
  packages/amplication-server/src/core/environment/environment.resolver.ts
  packages/amplication-server/src/core/environment/environment.service.spec.ts
  packages/amplication-server/src/core/environment/environment.service.ts
  packages/amplication-server/src/schema.graphql
Labels: type: enhancement

#842 Commit builds
  packages/amplication-server/prisma/schema.prisma
  packages/amplication-server/src/core/app/dto/PendingChange.ts
  packages/amplication-server/src/core/build/dto/BuildWhereInput.ts
  packages/amplication-server/src/core/commit/commit.module.ts
  packages/amplication-server/src/core/commit/commit.resolver.spec.ts
  packages/amplication-server/src/core/commit/commit.resolver.ts
  packages/amplication-server/src/core/commit/commit.service.spec.ts
  packages/amplication-server/src/core/commit/commit.service.ts
  packages/amplication-server/src/core/entity/entity.service.ts
  packages/amplication-server/src/models/Commit.ts
  packages/amplication-server/src/schema.graphql
Labels: type: enhancement

#838 Fix RMWC Provider
  packages/amplication-client/config-overrides.js
  packages/amplication-client/package-lock.json
  packages/amplication-client/package.json
  packages/amplication-client/src/Application/Applications.tsx
  packages/amplication-client/src/Components/MultiStateToggle.tsx
  packages/amplication-client/src/Components/MultiStateToggleField.tsx
  packages/amplication-client/src/User/Signup.tsx
  packages/amplication-client/src/index.tsx
  packages/amplication-design-system/package-lock.json
  packages/amplication-design-system/package.json
  packages/amplication-design-system/rollup.config.js
  packages/amplication-design-system/src/components/Button.tsx
  packages/amplication-design-system/src/components/Provider.tsx
  packages/amplication-design-system/src/index.ts
Labels: type: bug

#844 Last Commit
  packages/amplication-client/src/Components/CircleIcon.scss
  packages/amplication-client/src/Components/ClickableId.scss
  packages/amplication-client/src/Components/ClickableId.tsx
  packages/amplication-client/src/Layout/MainLayout.scss
  packages/amplication-client/src/Layout/PageContent.scss
  packages/amplication-client/src/VersionControl/BuildHeader.tsx
  packages/amplication-client/src/VersionControl/BuildSteps.tsx
  packages/amplication-client/src/VersionControl/LastCommit.tsx
  packages/amplication-client/src/VersionControl/PendingChangesBar.scss
  packages/amplication-client/src/VersionControl/PendingChangesBar.tsx
  packages/amplication-client/src/models.ts
  packages/amplication-client/src/style/css-variables.css
  packages/amplication-data-service-generator/src/models.ts
  packages/amplication-data/src/models.ts
  packages/amplication-server/src/core/build/dto/Build.ts
  packages/amplication-server/src/schema.graphql
Labels: type: enhancement

#848 Build page
  packages/amplication-client/src/Components/ClickableId.tsx
  packages/amplication-client/src/Components/TruncatedId.tsx
  packages/amplication-client/src/VersionControl/ActionLog.tsx
  packages/amplication-client/src/VersionControl/BuildHeader.scss
  packages/amplication-client/src/VersionControl/BuildHeader.tsx
  packages/amplication-client/src/VersionControl/BuildPage.scss
  packages/amplication-client/src/VersionControl/BuildPage.tsx
  packages/amplication-client/src/VersionControl/BuildSteps.scss
  packages/amplication-client/src/VersionControl/BuildSteps.tsx
  packages/amplication-client/src/VersionControl/Commit.tsx
  packages/amplication-client/src/VersionControl/LastCommit.scss
  packages/amplication-client/src/VersionControl/LastCommit.tsx
  packages/amplication-client/src/VersionControl/constants.ts
  packages/amplication-client/src/style/css-variables.css
  packages/amplication-design-system/src/components/Button.scss
Labels: type: enhancement

#849 Commit resolver
  packages/amplication-server/src/core/app/app.resolver.spec.ts
  packages/amplication-server/src/core/app/app.resolver.ts
  packages/amplication-server/src/core/app/app.service.ts
  packages/amplication-server/src/core/commit/commit.resolver.spec.ts
  packages/amplication-server/src/core/commit/commit.resolver.ts
  packages/amplication-server/src/core/permissions/permissions.service.ts
  packages/amplication-server/src/schema.graphql
Labels: type: enhancement

#850 Commit page
  packages/amplication-client/src/Application/ApplicationLayout.tsx
  packages/amplication-client/src/VersionControl/CommitPage.scss
  packages/amplication-client/src/VersionControl/CommitPage.tsx
  packages/amplication-client/src/VersionControl/PendingChange.scss
  packages/amplication-client/src/VersionControl/PendingChange.tsx
  packages/amplication-client/src/VersionControl/PendingChanges.scss
  packages/amplication-client/src/VersionControl/PendingChanges.tsx
Labels: type: enhancement

#846 Server: Auto Deploy Tests
  packages/amplication-server/src/core/build/build.service.spec.ts
  packages/amplication-server/src/core/build/build.service.ts
  packages/amplication-server/src/core/deployment/deployment.service.spec.ts
  packages/amplication-server/src/core/environment/environment.service.spec.ts
Labels: type: test

#854 Client: Update icons
  packages/amplication-client/src/Application/ApplicationLayout.tsx
  packages/amplication-client/src/Entity/EntityList.tsx
  packages/amplication-client/src/Layout/MainLayout.tsx
  packages/amplication-client/src/VersionControl/BuildPage.scss
  packages/amplication-client/src/VersionControl/CommitPage.scss
  packages/amplication-client/src/VersionControl/CommitPage.tsx
  packages/amplication-client/src/VersionControl/LockStatusIcon.tsx
  packages/amplication-client/src/VersionControl/PendingChangeDiff.scss
  packages/amplication-client/src/VersionControl/PendingChangeDiff.tsx
  packages/amplication-client/src/VersionControl/PendingChangeWithCompare.scss
  packages/amplication-client/src/VersionControl/PendingChangeWithCompare.tsx
  packages/amplication-client/src/assets/fonts/amplicationicon.eot
  packages/amplication-client/src/assets/fonts/amplicationicon.svg
  packages/amplication-client/src/assets/fonts/amplicationicon.ttf
  packages/amplication-client/src/assets/fonts/amplicationicon.woff
  packages/amplication-client/src/style/mixin.scss
Labels: type: enhancement

#856 Download code when first step (generate code) completes
  packages/amplication-server/src/core/build/build.controller.spec.ts
  packages/amplication-server/src/core/build/build.controller.ts
  packages/amplication-server/src/core/build/build.service.spec.ts
  packages/amplication-server/src/core/build/build.service.ts
  packages/amplication-server/src/core/build/errors/BuildNotCompleteError.ts
  packages/amplication-server/src/core/build/errors/StepNotCompleteError.ts
  packages/amplication-server/src/core/build/errors/StepNotFoundError.ts
Labels: type: enhancement

#858 Update icons 2
  packages/amplication-client/src/VersionControl/PendingchangesPage.scss
Labels: type: style

#861 Build preview link
  packages/amplication-client/src/VersionControl/BuildSteps.tsx
  packages/amplication-client/src/VersionControl/LastCommit.tsx
Labels: type: enhancement

#863 Link to build
  packages/amplication-client/src/Components/ClickableId.tsx
  packages/amplication-client/src/VersionControl/BuildNewVersion.tsx
  packages/amplication-client/src/VersionControl/BuildPage.scss
  packages/amplication-client/src/VersionControl/CommitList.tsx
  packages/amplication-client/src/VersionControl/CommitListItem.tsx
  packages/amplication-client/src/VersionControl/CommitPage.tsx
  packages/amplication-client/src/VersionControl/LastBuild.tsx
  packages/amplication-client/src/VersionControl/LastCommit.tsx
  packages/amplication-client/src/VersionControl/PendingChangesPage.tsx
  packages/amplication-client/src/VersionControl/useBuildWatchStatus.tsx
  packages/amplication-client/src/index.scss
  packages/amplication-client/src/style/mixin.scss
Labels: type: enhancement

#865 fix test auto deployment
  packages/amplication-server/src/core/deployment/deployment.service.spec.ts
Labels: type: bug

#864 Build and commit header
  packages/amplication-client/src/Components/ClickableId.tsx
  packages/amplication-client/src/VersionControl/BuildPage.scss
  packages/amplication-client/src/VersionControl/BuildPage.tsx
  packages/amplication-client/src/VersionControl/CommitHeader.scss
  packages/amplication-client/src/VersionControl/CommitHeader.tsx
  packages/amplication-client/src/VersionControl/CommitPage.scss
  packages/amplication-client/src/VersionControl/CommitPage.tsx
Labels: type: enhancement

#866 deploy environment
  packages/amplication-server/src/core/environment/environment.service.spec.ts
  packages/amplication-server/src/core/environment/environment.service.ts
Labels: type: bug

#841 Server: Update Build Status Tests
  packages/amplication-server/src/core/action/dto/index.ts
  packages/amplication-server/src/core/build/build.service.spec.ts
  packages/amplication-server/src/core/build/build.service.ts
  packages/amplication-server/src/core/deployment/deployment.service.ts
  packages/amplication-server/src/core/system/system.controller.spec.ts
Labels: type: test

#869 Improve VSCode Exclude
  .vscode/settings.json
Labels: type: chore

#867 Client: Fix Commit Refresh
  packages/amplication-client/src/Application/ApplicationLayout.tsx
  packages/amplication-client/src/VersionControl/Commit.tsx
  packages/amplication-client/src/VersionControl/LastCommit.tsx
Labels: type: bug

#868 Client: Remove LockStatus
  packages/amplication-client/src/Entity/Entity.tsx
  packages/amplication-client/src/Layout/FloatingToolbar.tsx
  packages/amplication-client/src/VersionControl/LockStatus.tsx
  packages/amplication-client/src/VersionControl/PendingChanges.tsx
Labels: type: bug

#870 Fix client warnings
  packages/amplication-client/config-overrides.js
  packages/amplication-client/src/Entity/NewEntity.tsx
  packages/amplication-client/src/Roles/NewRole.tsx
Labels: type: bug

#874 DSG: Fix installation of generated apps locally
  packages/amplication-data-service-generator/src/prisma/create-prisma-schema-module.ts
  packages/amplication-data-service-generator/src/seed/create-seed.ts
  packages/amplication-data-service-generator/src/static/.env
  packages/amplication-data-service-generator/src/static/README.md
  packages/amplication-data-service-generator/src/static/package.json
  packages/amplication-data-service-generator/src/static/prisma/.env
  packages/amplication-data-service-generator/src/static/prisma/clean.ts
  packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
Labels: type: bug
