Repository amplication/amplication, pull requests merged in 2020-10, with the labels that each got.

#526 Discard pending changes
  packages/amplication-server/src/core/app/app.resolver.ts
  packages/amplication-server/src/core/app/app.service.ts
  packages/amplication-server/src/core/app/dto/DiscardPendingChangesArgs.ts
  packages/amplication-server/src/core/app/dto/PendingChangesDiscardInput.ts
  packages/amplication-server/src/core/app/dto/index.ts
  packages/amplication-server/src/core/entity/entity.service.spec.ts
  packages/amplication-server/src/core/entity/entity.service.ts
  packages/amplication-server/src/schema.graphql
Labels: type: enhancement

#528 Client: Discard changes
  packages/amplication-client/src/Components/Dialog.scss
  packages/amplication-client/src/Components/Dialog.tsx
  packages/amplication-client/src/VersionControl/DiscardChanges.scss
  packages/amplication-client/src/VersionControl/DiscardChanges.tsx
  packages/amplication-client/src/VersionControl/PendingChanges.tsx
  packages/amplication-client/src/assets/images/warning.svg
Labels: type: enhancement

#533 Entity List style
  packages/amplication-client/src/Entity/EntityList.tsx
  packages/amplication-client/src/Entity/EntityListItem.tsx
Labels: type: style

#534 Fix(client): Change button type to avoid submit
  packages/amplication-client/src/Entity/EntityForm.tsx
  packages/amplication-client/src/Permissions/PermissionsPreview.tsx
Labels: type: bug

#535 Fix entity field validation
  packages/amplication-client/src/Entity/EntityFieldForm.tsx
Labels: type: bug

#537 Option Set - Auto update value based on label
  packages/amplication-client/src/Components/TextField.tsx
  packages/amplication-client/src/Components/TextInput.scss
  packages/amplication-client/src/Entity/OptionSet.scss
  packages/amplication-client/src/style/mixin.scss
Labels: type: bug

#538 Update Amplitude key for prod
  terraform/envs/production/terraform.tfvars
Labels: type: chore

#539 Analytics events
  packages/amplication-client/src/Application/CurrentBuildTile.tsx
  packages/amplication-client/src/Application/EntitiesTile.tsx
  packages/amplication-client/src/Application/PendingChangesTile.tsx
  packages/amplication-client/src/Application/RolesTile.tsx
  packages/amplication-client/src/VersionControl/Build.tsx
Labels: type: enhancement

#540 update icons
  packages/amplication-client/src/Layout/MainLayout.tsx
  packages/amplication-client/src/assets/fonts/amplicationicon.eot
  packages/amplication-client/src/assets/fonts/amplicationicon.svg
  packages/amplication-client/src/assets/fonts/amplicationicon.ttf
  packages/amplication-client/src/assets/fonts/amplicationicon.woff
Labels: type: style

#541 Stop click event on multi-state-toggle
  packages/amplication-client/src/Components/MultiStateToggle.scss
  packages/amplication-client/src/Components/MultiStateToggle.tsx
Labels: type: bug

#525 Server: Docker Build generated app
  Dockerfile
  cloudbuild.yaml
  packages/amplication-container-builder/.gitignore
  packages/amplication-container-builder/README.md
  packages/amplication-container-builder/package-lock.json
  packages/amplication-container-builder/package.json
  packages/amplication-container-builder/src/builder/ContainerBuilder.spec.ts
  packages/amplication-container-builder/src/builder/ContainerBuilder.ts
  packages/amplication-container-builder/src/builder/InvalidDefaultError.ts
  packages/amplication-container-builder/src/builder/index.ts
  packages/amplication-container-builder/src/cloud-build/CloudBuildProvider.spec.ts
  packages/amplication-container-builder/src/cloud-build/CloudBuildProvider.ts
  packages/amplication-container-builder/src/cloud-build/config.spec.ts
  packages/amplication-container-builder/src/cloud-build/config.ts
  packages/amplication-container-builder/src/cloud-build/gcs.util.spec.ts
  packages/amplication-container-builder/src/cloud-build/gcs.util.ts
  packages/amplication-container-builder/src/cloud-build/index.ts
  packages/amplication-container-builder/src/docker/DockerProvider.spec.ts
  packages/amplication-container-builder/src/docker/DockerProvider.ts
  packages/amplication-container-builder/src/docker/index.ts
  packages/amplication-container-builder/src/index.ts
  packages/amplication-container-builder/src/nestjs/containerBuilder.module.ts
  packages/amplication-container-builder/src/nestjs/containerBuilder.service.ts
  packages/amplication-container-builder/src/nestjs/containerBuilderOptions.token.ts
  packages/amplication-container-builder/src/nestjs/index.ts
  packages/amplication-container-builder/src/types/BuildResult.ts
  packages/amplication-container-builder/src/types/IProvider.ts
  packages/amplication-container-builder/src/types/index.ts
  packages/amplication-container-builder/tsconfig.json
  packages/amplication-data-service-generator/.dockerignore
  packages/amplication-data-service-generator/Dockerfile
  packages/amplication-data-service-generator/src/static/.dockerignore
  packages/amplication-data-service-generator/src/static/Dockerfile
  packages/amplication-data-service-generator/src/static/package-lock.json
  packages/amplication-data-service-generator/src/static/package.json
  packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
  packages/amplication-data-service-generator/src/tests/create-data-service.spec.ts
  packages/amplication-server/.env
  packages/amplication-server/package-lock.json
  packages/amplication-server/package.json
  packages/amplication-server/src/core/action/action.service.spec.ts
  packages/amplication-server/src/core/action/action.service.ts
  packages/amplication-server/src/core/build/build.module.ts
  packages/amplication-server/src/core/build/build.service.spec.ts
  packages/amplication-server/src/core/build/build.service.ts
  packages/amplication-server/src/core/build/storage.ts
  packages/amplication-server/src/core/build/tar.spec.ts
  packages/amplication-server/src/core/build/tar.ts
  packages/amplication-server/src/core/containerBuilder/containerBuilderRoot.module.ts
  packages/amplication-server/test/app.resolver.e2e-spec.ts
  terraform/envs/dev/main.tf
  terraform/envs/dev/terraform.tfvars
  terraform/envs/dev/variables.tf
  terraform/envs/production/main.tf
  terraform/envs/production/terraform.tfvars
  terraform/envs/production/variables.tf
  terraform/modules/cd/main.tf
  terraform/modules/cd/variables.tf
  terraform/modules/env_baseline/main.tf
  terraform/modules/env_baseline/variables.tf
Labels: type: enhancement

#553 fix(e2e): amplication.com title test
  packages/amplication-e2e-tester/Title-test/title.test.js
Labels: type: test

#542 Permissions panel collapse
  packages/amplication-client/src/Components/PanelCollapsible.tsx
  packages/amplication-client/src/Permissions/EntityPermissionAction.tsx
Labels: type: bug

#544 Update images
  packages/amplication-client/src/Application/ApplicationLayout.tsx
  packages/amplication-client/src/VersionControl/PendingChanges.scss
  packages/amplication-client/src/VersionControl/PendingChanges.tsx
  packages/amplication-client/src/assets/images/commit-changes.svg
  packages/amplication-client/src/assets/images/done.svg
  packages/amplication-client/src/assets/images/logs.svg
  packages/amplication-client/src/assets/images/new-app.svg
  packages/amplication-client/src/assets/images/no-changes.svg
  packages/amplication-client/src/assets/images/notice.svg
Labels: type: style

#543 Style modals
  packages/amplication-client/src/Components/Dialog.scss
  packages/amplication-client/src/Layout/FloatingToolbar.scss
  packages/amplication-client/src/style/css-variables.css
Labels: type: style

#545 Commit & discard modals
  packages/amplication-client/src/VersionControl/Commit.scss
  packages/amplication-client/src/VersionControl/Commit.tsx
  packages/amplication-client/src/VersionControl/DiscardChanges.scss
  packages/amplication-client/src/VersionControl/DiscardChanges.tsx
  packages/amplication-client/src/VersionControl/PendingChanges.tsx
Labels: type: enhancement

#546 "New Entity" modal
  packages/amplication-client/src/Entity/Entity.scss
  packages/amplication-client/src/Entity/NewEntity.scss
  packages/amplication-client/src/Entity/NewEntity.tsx
Labels: type: enhancement

#549 Tiles loading state
  packages/amplication-client/src/Application/CurrentBuildTile.tsx
  packages/amplication-client/src/Application/EntitiesTile.tsx
  packages/amplication-client/src/Application/PendingChangesTile.tsx
  packages/amplication-client/src/Application/RolesTile.tsx
Labels: type: enhancement

#551 Select app color
  packages/amplication-client/src/Application/ApplicationForm.tsx
  packages/amplication-client/src/Application/ApplicationHome.scss
  packages/amplication-client/src/Application/ApplicationHome.tsx
  packages/amplication-client/src/Application/constants.ts
  packages/amplication-client/src/Components/Panel.tsx
  packages/amplication-client/src/Layout/MainLayout.scss
  packages/amplication-client/src/style/parameters.scss
Labels: type: enhancement

#556 Keyboard Shortcuts
  packages/amplication-client/package-lock.json
  packages/amplication-client/package.json
  packages/amplication-client/src/App.tsx
  packages/amplication-client/src/Application/ApplicationLayout.tsx
  packages/amplication-client/src/Application/NewApplication.tsx
  packages/amplication-client/src/Components/Dialog.scss
  packages/amplication-client/src/Entity/NewEntity.tsx
  packages/amplication-client/src/VersionControl/BuildNewVersion.tsx
  packages/amplication-client/src/VersionControl/Commit.tsx
  packages/amplication-client/src/VersionControl/PendingChangesStatus.tsx
  packages/amplication-client/src/index.scss
Labels: type: enhancement

#557 Fix client error messages
  packages/amplication-client/src/Application/NewApplication.tsx
  packages/amplication-client/src/Entity/NewEntity.tsx
  packages/amplication-client/src/VersionControl/BuildNewVersion.tsx
  packages/amplication-client/src/VersionControl/Commit.tsx
  packages/amplication-client/src/VersionControl/PendingChanges.tsx
  packages/amplication-client/src/index.scss
Labels: type: bug

#552 Create entity field by name
  packages/amplication-client/src/Application/ApplicationHome.scss
  packages/amplication-client/src/Entity/NewEntityField.tsx
  packages/amplication-server/src/core/entity/dto/CreateOneEntityFieldArgs.ts
  packages/amplication-server/src/core/entity/dto/CreateOneEntityFieldByDisplayNameArgs.ts
  packages/amplication-server/src/core/entity/dto/EntityFieldCreateByDisplayNameInput.ts
  packages/amplication-server/src/core/entity/dto/EntityFieldCreateInput.ts
  packages/amplication-server/src/core/entity/dto/index.ts
  packages/amplication-server/src/core/entity/entity.resolver.ts
  packages/amplication-server/src/core/entity/entity.service.ts
  packages/amplication-server/src/schema.graphql
Labels: type: enhancement

#560 Use GlobalHotKeys
  packages/amplication-client/src/App.tsx
  packages/amplication-client/src/Application/NewApplication.tsx
  packages/amplication-client/src/Entity/NewEntity.tsx
  packages/amplication-client/src/VersionControl/BuildNewVersion.tsx
  packages/amplication-client/src/VersionControl/Commit.tsx
Labels: type: enhancement

#561 Close sidebar with Esc shortcut
  packages/amplication-client/src/Layout/SidebarHeader.tsx
Labels: type: enhancement

#568 Command palette builds
  packages/amplication-client/src/CommandPalette/CommandPalette.tsx
Labels: type: bug

#562 Command palette shortcut & MenuItem tooltip
  packages/amplication-client/src/CommandPalette/CommandPalette.tsx
  packages/amplication-client/src/Layout/MainLayout.scss
  packages/amplication-client/src/Layout/MainLayout.tsx
  packages/amplication-client/src/Layout/MenuItem.scss
  packages/amplication-client/src/Layout/MenuItem.tsx
Labels: type: enhancement

#572 Update first-app.md
  docs/getting-started/first-app.md
Labels: type: docs

#566 Deployment
  packages/amplication-server/src/core/deployment/deployment.controller.ts
  packages/amplication-server/src/core/deployment/deployment.module.ts
  packages/amplication-server/src/core/deployment/deployment.resolver.ts
  packages/amplication-server/src/core/deployment/deployment.service.spec.ts
  packages/amplication-server/src/core/deployment/deployment.service.ts
  packages/amplication-server/src/core/deployment/dto/CreateDeploymentArgs.ts
  packages/amplication-server/src/core/deployment/dto/CreateDeploymentDTO.ts
  packages/amplication-server/src/core/deployment/dto/Deployment.ts
  packages/amplication-server/src/core/deployment/dto/DeploymentCreateInput.ts
  packages/amplication-server/src/core/deployment/dto/DeploymentOrderByInput.ts
  packages/amplication-server/src/core/deployment/dto/DeploymentWhereInput.ts
  packages/amplication-server/src/core/deployment/dto/EnumDeploymentStatus.ts
  packages/amplication-server/src/core/deployment/dto/EnumDeploymentStatusFilter.ts
  packages/amplication-server/src/core/deployment/dto/FindManyDeploymentArgs.ts
  packages/amplication-server/src/core/deployment/dto/FindOneDeploymentArgs.ts
  packages/amplication-server/src/core/permissions/permissions.service.spec.ts
  packages/amplication-server/src/core/permissions/permissions.service.ts
  packages/amplication-server/src/enums/AuthorizableResourceParameter.ts
Labels: type: enhancement

#571 Recover deleted entities after discard changes
  packages/amplication-server/src/core/entity/entity.service.spec.ts
  packages/amplication-server/src/core/entity/entity.service.ts
Labels: type: bug

#567 App resolve field environments
  packages/amplication-server/src/core/app/app.module.ts
  packages/amplication-server/src/core/app/app.resolver.ts
  packages/amplication-server/src/core/environment/dto/EnvironmentOrderByInput.ts
  packages/amplication-server/src/core/environment/dto/EnvironmentWhereInput.ts
  packages/amplication-server/src/core/environment/dto/FindManyEnvironmentArgs.ts
  packages/amplication-server/src/core/environment/dto/index.ts
  packages/amplication-server/src/core/environment/environment.service.spec.ts
  packages/amplication-server/src/core/environment/environment.service.ts
  packages/amplication-server/src/schema.graphql
Labels: type: enhancement

#554 Server: Refactor Sample App Creation
  packages/amplication-server/src/core/app/InvalidColorError.ts
  packages/amplication-server/src/core/app/app.service.spec.ts
  packages/amplication-server/src/core/app/app.service.ts
  packages/amplication-server/src/core/app/sampleApp.spec.ts
  packages/amplication-server/src/core/app/sampleApp.ts
  packages/amplication-server/src/core/auth/auth.service.spec.ts
  packages/amplication-server/src/core/auth/auth.service.ts
  packages/amplication-server/src/core/entity/constants.ts
  packages/amplication-server/src/core/entity/entity.service.ts
  packages/amplication-server/src/core/organization/initialAppData.ts
  packages/amplication-server/src/core/organization/organization.module.ts
  packages/amplication-server/src/core/organization/organization.service.spec.ts
  packages/amplication-server/src/core/organization/organization.service.ts
Labels: type: refactor

#578 Build process artifacts
  docs/build-process-artifacts.drawio
Labels: type: docs

#574 Code review fixes
  packages/amplication-client/src/App.tsx
  packages/amplication-client/src/Application/NewApplication.tsx
  packages/amplication-client/src/CommandPalette/CommandPalette.tsx
  packages/amplication-client/src/Entity/NewEntity.tsx
  packages/amplication-client/src/VersionControl/BuildNewVersion.tsx
  packages/amplication-client/src/VersionControl/Commit.tsx
  packages/amplication-client/src/util/hotkeys.ts
  packages/amplication-server/src/core/app/app.service.spec.ts
  packages/amplication-server/src/core/app/app.service.ts
  packages/amplication-server/src/core/deployment/deployment.controller.ts
  packages/amplication-server/src/core/deployment/deployment.service.ts
  packages/amplication-server/src/core/environment/environment.service.spec.ts
  packages/amplication-server/src/core/environment/environment.service.ts
Labels: type: refactor

#575 Added test to check Record not Found in entity service
  packages/amplication-server/src/core/entity/entity.service.spec.ts
Labels: type: enhancement

#580 Style menu
  packages/amplication-client/src/Application/ApplicationBadge.scss
  packages/amplication-client/src/Application/ApplicationBadge.tsx
  packages/amplication-client/src/Application/ApplicationHome.scss
  packages/amplication-client/src/Application/ApplicationIcon.scss
  packages/amplication-client/src/Application/ApplicationIcon.tsx
  packages/amplication-client/src/Application/ApplicationLayout.scss
  packages/amplication-client/src/Application/ApplicationLayout.tsx
  packages/amplication-client/src/CommandPalette/CommandPalette.scss
  packages/amplication-client/src/Components/DataGrid.scss
  packages/amplication-client/src/Layout/MainLayout.scss
  packages/amplication-client/src/Layout/MainLayout.tsx
  packages/amplication-client/src/Layout/MenuItem.scss
  packages/amplication-client/src/Layout/MenuItem.tsx
  packages/amplication-client/src/assets/fonts/amplicationicon.eot
  packages/amplication-client/src/assets/fonts/amplicationicon.svg
  packages/amplication-client/src/assets/fonts/amplicationicon.ttf
  packages/amplication-client/src/assets/fonts/amplicationicon.woff
  packages/amplication-client/src/assets/logo-textual.svg
  packages/amplication-client/src/style/css-variables.css
  packages/amplication-client/src/style/mixin.scss
  packages/amplication-client/src/style/parameters.scss
Labels: type: style

#584 Deployment dialog
  packages/amplication-client/src/VersionControl/Build.tsx
  packages/amplication-client/src/VersionControl/BuildList.scss
  packages/amplication-client/src/VersionControl/Deploy.scss
  packages/amplication-client/src/VersionControl/Deploy.tsx
  packages/amplication-client/src/models.ts
  packages/amplication-data-service-generator/src/models.ts
  packages/amplication-data/src/models.ts
  packages/amplication-server/src/core/core.module.ts
  packages/amplication-server/src/core/deployment/deployment.module.ts
  packages/amplication-server/src/core/deployment/dto/DeploymentCreateInput.ts
  packages/amplication-server/src/models/App.ts
  packages/amplication-server/src/schema.graphql
Labels: type: enhancement

#569 EntityResolver Tests
  packages/amplication-server/src/core/entity/entity.resolver.spec.ts
Labels: type: enhancement

#590 Watch build status
  packages/amplication-client/src/VersionControl/ActionLog.tsx
  packages/amplication-client/src/VersionControl/Build.tsx
  packages/amplication-client/src/VersionControl/BuildList.tsx
  packages/amplication-client/src/VersionControl/BuildNewVersion.tsx
  packages/amplication-client/src/VersionControl/useBuildWatchStatus.tsx
  packages/amplication-client/src/models.ts
  packages/amplication-data-service-generator/src/models.ts
  packages/amplication-data/src/models.ts
  packages/amplication-server/src/core/build/build.resolver.spec.ts
  packages/amplication-server/src/core/build/build.resolver.ts
  packages/amplication-server/src/core/build/build.service.ts
  packages/amplication-server/src/core/build/dto/Build.ts
  packages/amplication-server/src/schema.graphql
Labels: type: enhancement

#589 Command palette
  packages/amplication-client/src/Application/ApplicationIcon.scss
  packages/amplication-client/src/CommandPalette/CommandPalette.scss
  packages/amplication-client/src/CommandPalette/CommandPalette.spec.ts
  packages/amplication-client/src/CommandPalette/CommandPalette.tsx
Labels: type: enhancement

#595 Fix sample app
  packages/amplication-server/src/core/app/app.service.spec.ts
  packages/amplication-server/src/core/app/app.service.ts
  packages/amplication-server/src/core/entity/entity.service.ts
Labels: type: bug

#596 Simplify setting feature flags
  packages/amplication-client/.env
  packages/amplication-client/src/Application/ApplicationLayout.tsx
  packages/amplication-client/src/env.ts
  packages/amplication-client/src/feature-flags.ts
  terraform/envs/dev/main.tf
  terraform/envs/dev/terraform.tfvars
  terraform/envs/dev/variables.tf
  terraform/envs/production/main.tf
  terraform/envs/production/terraform.tfvars
  terraform/envs/production/variables.tf
  terraform/modules/env_baseline/main.tf
  terraform/modules/env_baseline/variables.tf
Labels: type: refactor

#607 Feature flag- SHOW_DEPLOYER
  packages/amplication-client/src/VersionControl/Build.tsx
  packages/amplication-client/src/feature-flags.ts
Labels: type: enhancement

#618 Publish modal
  packages/amplication-client/src/VersionControl/Deploy.scss
  packages/amplication-client/src/VersionControl/Deploy.tsx
  packages/amplication-client/src/assets/images/sandbox.svg
Labels: type: enhancement

#616 Build list style
  packages/amplication-client/src/VersionControl/BuildList.scss
  packages/amplication-client/src/VersionControl/BuildList.tsx
  packages/amplication-client/src/VersionControl/NextBuild.tsx
Labels: type: style

#620 Default build message based on last commits
  packages/amplication-client/src/VersionControl/BuildNewVersion.tsx
  packages/amplication-client/src/VersionControl/NextBuild.tsx
Labels: type: enhancement

#623 Extract roles page and components from "/settings"
  packages/amplication-client/src/Application/ApplicationLayout.tsx
  packages/amplication-client/src/Application/RolesTile.tsx
  packages/amplication-client/src/CommandPalette/CommandPalette.tsx
  packages/amplication-client/src/Roles/NewRole.tsx
  packages/amplication-client/src/Roles/Role.tsx
  packages/amplication-client/src/Roles/RoleForm.tsx
  packages/amplication-client/src/Roles/RoleList.scss
  packages/amplication-client/src/Roles/RoleList.tsx
  packages/amplication-client/src/Roles/RolesPage.tsx
Labels: type: refactor

#622 Clickable tiles
  packages/amplication-client/src/Application/CurrentBuildTile.tsx
  packages/amplication-client/src/Application/EntitiesTile.tsx
  packages/amplication-client/src/Application/PendingChangesTile.tsx
  packages/amplication-client/src/Application/RolesTile.tsx
  packages/amplication-client/src/Components/Panel.scss
  packages/amplication-client/src/Components/Panel.tsx
Labels: type: enhancement

#614 Deployment status - client
  packages/amplication-client/src/VersionControl/Build.scss
  packages/amplication-client/src/VersionControl/Build.tsx
  packages/amplication-client/src/VersionControl/BuildDeployments.scss
  packages/amplication-client/src/VersionControl/BuildDeployments.tsx
  packages/amplication-client/src/VersionControl/useBuildWatchStatus.tsx
Labels: type: enhancement

#626 Add tests to App Resolver
  packages/amplication-server/src/core/app/app.resolver.spec.ts
Labels: type: enhancement

#628 Add all tests to App Resolver
  packages/amplication-server/src/core/app/app.resolver.spec.ts
Labels: type: enhancement

#639 Normalize path
  packages/amplication-data-service-generator/src/create-data-service.ts
  packages/amplication-data-service-generator/src/util/module.ts
Labels: type: enhancement

#638 Add all tests to AppRole Resolver
  packages/amplication-server/src/core/appRole/appRole.resolver.spec.ts
Labels: type: enhancement

#636 Add all tests to Account Resolver
  packages/amplication-server/src/core/account/account.resolver.spec.ts
  packages/amplication-server/src/core/account/account.resolver.ts
  packages/amplication-server/src/core/account/account.service.spec.ts
  packages/amplication-server/src/core/account/account.service.ts
  packages/amplication-server/src/core/auth/auth.service.ts
Labels: type: enhancement

#630 Environment domain
  packages/amplication-client/src/VersionControl/BuildDeployments.tsx
  packages/amplication-client/src/VersionControl/BuildList.tsx
  packages/amplication-client/src/VersionControl/BuildNewVersion.tsx
  packages/amplication-client/src/VersionControl/Deploy.tsx
  packages/amplication-client/src/VersionControl/LastBuild.tsx
  packages/amplication-client/src/VersionControl/useBuildWatchStatus.tsx
  packages/amplication-client/src/models.ts
  packages/amplication-data-service-generator/src/models.ts
  packages/amplication-data/src/models.ts
  packages/amplication-server/src/core/environment/dto/Environment.ts
  packages/amplication-server/src/core/environment/environment.resolver.ts
  packages/amplication-server/src/schema.graphql
Labels: type: enhancement

#649 Sign in page
  packages/amplication-client/src/Layout/WelcomePage.scss
  packages/amplication-client/src/Layout/WelcomePage.tsx
  packages/amplication-client/src/User/Login.tsx
  packages/amplication-client/src/assets/images/signin-bg.svg
  packages/amplication-client/src/assets/images/signin-stripe.svg
  packages/amplication-client/src/assets/images/signin-top-stripe.svg
  packages/amplication-client/src/assets/logo-amplication-white.svg
  packages/amplication-client/src/assets/logo-amplication.svg
Labels: type: enhancement

#652 Delete auto-number migration script
  packages/amplication-server/migration-scripts/delete-auto-number.ts
Labels: type: chore

#651 Create VSCode Build Tasks
  .vscode/tasks.json
Labels: type: enhancement

#617 Add all tests for Entity Resolver
  packages/amplication-server/src/core/entity/entity.resolver.spec.ts
Labels: type: enhancement

#653 Feature/deploy status
  packages/amplication-client/src/VersionControl/ActionLog.tsx
  packages/amplication-client/src/VersionControl/Build.tsx
  packages/amplication-client/src/VersionControl/BuildDeployments.tsx
  packages/amplication-client/src/VersionControl/BuildNewVersion.tsx
  packages/amplication-client/src/VersionControl/Builds.tsx
  packages/amplication-client/src/VersionControl/Deploy.tsx
  packages/amplication-client/src/VersionControl/useBuildWatchStatus.tsx
  packages/amplication-client/src/models.ts
  packages/amplication-data-service-generator/src/models.ts
  packages/amplication-data/src/models.ts
  packages/amplication-server/src/core/deployment/deployment.resolver.ts
  packages/amplication-server/src/core/deployment/dto/Deployment.ts
  packages/amplication-server/src/schema.graphql
Labels: priority: high, type: enhancement

#658 Add logging to deployment
  packages/amplication-server/src/core/deployment/deployment.service.ts
Labels: type: enhancement

#655 Deployment list
  packages/amplication-client/src/VersionControl/Build.tsx
  packages/amplication-client/src/VersionControl/BuildDeployments.scss
  packages/amplication-client/src/VersionControl/BuildDeployments.tsx
  packages/amplication-client/src/VersionControl/BuildList.tsx
  packages/amplication-client/src/VersionControl/BuildNewVersion.tsx
  packages/amplication-client/src/VersionControl/Deployment.scss
  packages/amplication-client/src/VersionControl/Deployment.tsx
  packages/amplication-client/src/VersionControl/LastBuild.tsx
  packages/amplication-client/src/VersionControl/useBuildWatchStatus.tsx
  packages/amplication-server/src/core/build/build.resolver.ts
  packages/amplication-server/src/core/build/build.service.spec.ts
  packages/amplication-server/src/core/build/build.service.ts
  packages/amplication-server/src/schema.graphql
Labels: type: enhancement

#660 Fix build refresh issue
  packages/amplication-client/src/VersionControl/Build.tsx
  packages/amplication-client/src/VersionControl/BuildList.tsx
  packages/amplication-client/src/VersionControl/useBuildWatchStatus.tsx
Labels: type: bug

#667 Entity default permissions
  packages/amplication-server/src/core/entity/constants.ts
  packages/amplication-server/src/core/entity/entity.service.spec.ts
  packages/amplication-server/src/core/entity/entity.service.ts
Labels: type: bug

#670 Data Service Generator: Fix DTO Optional Fields
  packages/amplication-data-service-generator/src/resource/dto/create-dto.spec.ts
  packages/amplication-data-service-generator/src/resource/dto/create-dto.ts
  packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
Labels: type: bug

#672 Serve static files on generated app
  packages/amplication-data-service-generator/package-lock.json
  packages/amplication-data-service-generator/package.json
  packages/amplication-data-service-generator/src/static/package-lock.json
  packages/amplication-data-service-generator/src/static/package.json
  packages/amplication-data-service-generator/src/static/scripts/copy-files.ts
  packages/amplication-data-service-generator/src/static/serveStatic.module.ts
  packages/amplication-data-service-generator/src/static/static/assets/amplication-logo.svg
  packages/amplication-data-service-generator/src/static/static/css-reset.css
  packages/amplication-data-service-generator/src/static/static/index.html
  packages/amplication-data-service-generator/src/static/static/style.css
  packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
Labels: type: enhancement

#673 style(client): circle icon loading
  packages/amplication-client/src/Components/CircleIcon.scss
  packages/amplication-client/src/VersionControl/Build.tsx
Labels: type: style

#674 style(client):deploy modal
  packages/amplication-client/src/VersionControl/Deploy.scss
  packages/amplication-client/src/VersionControl/Deploy.tsx
  packages/amplication-client/src/style/css-variables.css
  packages/amplication-client/src/style/mixin.scss
Labels: type: style

#681 feat(client):action-log
  packages/amplication-client/src/Components/ProgressBar.tsx
  packages/amplication-client/src/Components/Timer.tsx
  packages/amplication-client/src/VersionControl/ActionLog.scss
  packages/amplication-client/src/VersionControl/ActionLog.tsx
  packages/amplication-client/src/VersionControl/Build.tsx
  packages/amplication-client/src/VersionControl/Builds.tsx
  packages/amplication-client/src/VersionControl/constants.ts
  packages/amplication-client/src/style/parameters.scss
Labels: type: enhancement

#687 Client: Deploy Button Style
  packages/amplication-client/src/Components/ProgressBar.scss
  packages/amplication-client/src/VersionControl/BuildDeployments.scss
  packages/amplication-client/src/VersionControl/BuildDeployments.tsx
Labels: type: style

#688 Update client/gitignore
  packages/amplication-client/.gitignore
Labels: type: chore

#694 Data Service Generator: Readme
  packages/amplication-data-service-generator/README.md
Labels: type: docs

#693 Fix - Build uncommitted changes
  packages/amplication-server/src/core/entity/entity.service.ts
Labels: type: bug

#706 Return deployment URL from amplication-deployer
  packages/amplication-client/src/VersionControl/BuildList.tsx
  packages/amplication-client/src/VersionControl/BuildNewVersion.tsx
  packages/amplication-client/src/VersionControl/Deploy.tsx
  packages/amplication-client/src/VersionControl/Deployment.tsx
  packages/amplication-client/src/VersionControl/LastBuild.tsx
  packages/amplication-client/src/VersionControl/useBuildWatchStatus.tsx
  packages/amplication-client/src/models.ts
  packages/amplication-data-service-generator/src/models.ts
  packages/amplication-data/src/models.ts
  packages/amplication-deployer/src/gcp/GCPProvider.ts
  packages/amplication-deployer/src/types/DeployResult.ts
  packages/amplication-server/src/core/deployment/deployment.service.ts
  packages/amplication-server/src/core/environment/dto/Environment.ts
  packages/amplication-server/src/core/environment/environment.resolver.ts
  packages/amplication-server/src/schema.graphql
Labels: type: enhancement

#702 Add missing auth fields for apps created in previous versions
  packages/amplication-data-service-generator/src/create-data-service.ts
  packages/amplication-data-service-generator/src/user-entity.spec.ts
  packages/amplication-data-service-generator/src/user-entity.ts
Labels: type: bug

#709 Allow permissionFieldRoles to be empty
  packages/amplication-data-service-generator/src/create-grants.spec.ts
  packages/amplication-data-service-generator/src/create-grants.ts
  packages/amplication-data-service-generator/src/types.ts
Labels: type: bug

#725 Fix Geographic Location display name
  packages/amplication-client/src/Entity/constants.ts
Labels: type: bug

#726 Update cache with new entity field
  packages/amplication-client/src/Entity/EntityFieldList.tsx
  packages/amplication-client/src/Entity/NewEntityField.tsx
  packages/amplication-client/src/Permissions/EntityPermissionFields.tsx
Labels: type: bug

#727 Update cache with new roles
  packages/amplication-client/src/Permissions/EntityPermissionAction.tsx
  packages/amplication-client/src/Roles/NewRole.tsx
Labels: type: bug

#730 Delete entity field
  packages/amplication-client/src/Entity/EntityFieldList.tsx
  packages/amplication-client/src/Entity/EntityFieldListItem.tsx
  packages/amplication-server/src/core/entity/dto/DeleteEntityFieldArgs.ts
  packages/amplication-server/src/core/entity/dto/index.ts
  packages/amplication-server/src/core/entity/entity.service.ts
Labels: type: enhancement

#731 Related entity display name
  packages/amplication-client/src/Entity/SchemaField.tsx
  packages/amplication-data/src/schemas/lookup.json
Labels: type: bug

#704 Data Service Generator: Create To Many Relationships
  .github/workflows/e2e.yml
  .vscode/launch.json
  packages/amplication-data-service-generator/src/resource/controller/controller.template.ts
  packages/amplication-data-service-generator/src/resource/controller/create-controller.ts
  packages/amplication-data-service-generator/src/resource/controller/to-many.template.ts
  packages/amplication-data-service-generator/src/resource/create-resource.ts
  packages/amplication-data-service-generator/src/static/Dockerfile
  packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
  packages/amplication-data-service-generator/src/tests/entities.ts
  packages/amplication-data-service-generator/src/types.ts
  packages/amplication-data-service-generator/src/util/ast.ts
  packages/amplication-data-service-generator/test/data-service-generator.e2e-spec.ts
  packages/amplication-data-service-generator/test/seed.ts
Labels: type: enhancement
