Repository amplication/amplication, pull requests merged in 2020-12, with the labels that each got.

#883 Design System : Add SearchField
  packages/amplication-design-system/src/components/SearchField/SearchField.scss
  packages/amplication-design-system/src/components/SearchField/SearchField.stories.tsx
  packages/amplication-design-system/src/components/SearchField/SearchField.tsx
  packages/amplication-design-system/src/index.ts
Labels: type: enhancement

#880 Fix deploy order
  packages/amplication-server/src/core/build/build.service.spec.ts
  packages/amplication-server/src/core/build/build.service.ts
Labels: type: bug

#885 Design system - select menu
  packages/amplication-design-system/src/components/Provider.tsx
  packages/amplication-design-system/src/components/SelectMenu/SelectMenu.scss
  packages/amplication-design-system/src/components/SelectMenu/SelectMenu.stories.tsx
  packages/amplication-design-system/src/components/SelectMenu/SelectMenu.tsx
  packages/amplication-design-system/src/index.ts
Labels: type: enhancement

#888 Design system : Data Grid
  packages/amplication-design-system/package-lock.json
  packages/amplication-design-system/package.json
  packages/amplication-design-system/src/components/DataGrid/DataGrid.scss
  packages/amplication-design-system/src/components/DataGrid/DataGrid.stories.tsx
  packages/amplication-design-system/src/components/DataGrid/DataGrid.tsx
  packages/amplication-design-system/src/components/DataGrid/DataGridCell.tsx
  packages/amplication-design-system/src/components/DataGrid/DataGridRow.tsx
  packages/amplication-design-system/src/index.ts
  packages/amplication-design-system/src/style/css-variables.css
Labels: type: chore

#894 Fix structure issues in data grid
  packages/amplication-client/src/Blocks/BlockList.tsx
  packages/amplication-client/src/Components/DataGrid.scss
  packages/amplication-client/src/Components/DataGrid.tsx
  packages/amplication-client/src/Components/DataGridRow.tsx
  packages/amplication-client/src/Components/SearchField.scss
  packages/amplication-client/src/Components/SearchField.tsx
  packages/amplication-client/src/Components/SelectMenu.scss
  packages/amplication-client/src/Components/SelectMenu.tsx
  packages/amplication-client/src/Entity/EntityFieldList.tsx
  packages/amplication-client/src/Entity/EntityFieldListItem.tsx
  packages/amplication-client/src/Entity/EntityList.tsx
  packages/amplication-client/src/Entity/EntityListItem.tsx
  packages/amplication-client/src/Permissions/EntityPermissionFields.tsx
  packages/amplication-client/src/Roles/RoleList.tsx
  packages/amplication-client/src/VersionControl/CommitList.tsx
  packages/amplication-client/src/VersionControl/CommitListItem.tsx
  packages/amplication-design-system/src/components/DataGrid/DataGrid.stories.tsx
  packages/amplication-design-system/src/components/DataGrid/DataGrid.tsx
  packages/amplication-design-system/src/components/DataGrid/DataGridCell.tsx
  packages/amplication-design-system/src/components/DataGrid/DataGridSortableHeader.tsx
  packages/amplication-design-system/src/index.ts
Labels: type: enhancement

#782 DSG: Admin UI
  .vscode/tasks.json
  packages/amplication-data-service-generator/.eslintrc.js
  packages/amplication-data-service-generator/package-lock.json
  packages/amplication-data-service-generator/package.json
  packages/amplication-data-service-generator/scripts/copy-files.ts
  packages/amplication-data-service-generator/src/admin/app/App.template.tsx
  packages/amplication-data-service-generator/src/admin/app/create-app.ts
  packages/amplication-data-service-generator/src/admin/create-admin.ts
  packages/amplication-data-service-generator/src/admin/create-dto-modules.ts
  packages/amplication-data-service-generator/src/admin/entity/create-entities-components.ts
  packages/amplication-data-service-generator/src/admin/entity/create-entity-component-module.ts
  packages/amplication-data-service-generator/src/admin/entity/create-entity-components-modules.ts
  packages/amplication-data-service-generator/src/admin/entity/create-entity-components.ts
  packages/amplication-data-service-generator/src/admin/entity/create/create-create-entity.ts
  packages/amplication-data-service-generator/src/admin/entity/create/create-entity.template.tsx
  packages/amplication-data-service-generator/src/admin/entity/list/create-entity-list.ts
  packages/amplication-data-service-generator/src/admin/entity/list/entity-list.template.tsx
  packages/amplication-data-service-generator/src/admin/entity/update/create-update-entity.ts
  packages/amplication-data-service-generator/src/admin/entity/update/update-entity.template.tsx
  packages/amplication-data-service-generator/src/admin/navigation/Navigation.template.tsx
  packages/amplication-data-service-generator/src/admin/navigation/create-navigation.ts
  packages/amplication-data-service-generator/src/admin/public-files/create-public-files.ts
  packages/amplication-data-service-generator/src/admin/public-files/index.template.html
  packages/amplication-data-service-generator/src/admin/public-files/manifest.json
  packages/amplication-data-service-generator/src/admin/static/.gitignore
  packages/amplication-data-service-generator/src/admin/static/README.md
  packages/amplication-data-service-generator/src/admin/static/package-lock.json
  packages/amplication-data-service-generator/src/admin/static/package.json
  packages/amplication-data-service-generator/src/admin/static/public/favicon.ico
  packages/amplication-data-service-generator/src/admin/static/public/logo192.png
  packages/amplication-data-service-generator/src/admin/static/public/logo512.png
  packages/amplication-data-service-generator/src/admin/static/public/robots.txt
  packages/amplication-data-service-generator/src/admin/static/src/App.test.tsx
  packages/amplication-data-service-generator/src/admin/static/src/Login.tsx
  packages/amplication-data-service-generator/src/admin/static/src/api.ts
  packages/amplication-data-service-generator/src/admin/static/src/api.util.ts
  packages/amplication-data-service-generator/src/admin/static/src/auth.ts
  packages/amplication-data-service-generator/src/admin/static/src/http.util.ts
  packages/amplication-data-service-generator/src/admin/static/src/index.css
  packages/amplication-data-service-generator/src/admin/static/src/index.tsx
  packages/amplication-data-service-generator/src/admin/static/src/reportWebVitals.ts
  packages/amplication-data-service-generator/src/admin/static/src/setupTests.ts
  packages/amplication-data-service-generator/src/admin/static/tsconfig.json
  packages/amplication-data-service-generator/src/admin/types.ts
  packages/amplication-data-service-generator/src/create-data-service.ts
  packages/amplication-data-service-generator/src/create-server.ts
  packages/amplication-data-service-generator/src/resource/dto/create-dto-module.ts
  packages/amplication-data-service-generator/src/static/package-lock.json
  packages/amplication-data-service-generator/src/static/tsconfig.build.json
  packages/amplication-data-service-generator/src/static/tsconfig.json
  packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
  packages/amplication-data-service-generator/src/util/ast.spec.ts
  packages/amplication-data-service-generator/src/util/ast.ts
  packages/amplication-data-service-generator/src/util/module.ts
  packages/amplication-data-service-generator/src/util/parser.ts
  packages/amplication-data-service-generator/tsconfig.json
  packages/amplication-server/src/core/build/build.service.spec.ts
  packages/amplication-server/src/core/build/build.service.ts
Labels: type: enhancement

#897 Design system: checkbox
  packages/amplication-client/src/Pages/EntityFieldMultiSelect.tsx
  packages/amplication-client/src/Pages/EntityPageForm.tsx
  packages/amplication-design-system/src/components/Checkbox/Checkbox.stories.tsx
  packages/amplication-design-system/src/components/Checkbox/CheckboxField.scss
  packages/amplication-design-system/src/components/Checkbox/CheckboxField.tsx
  packages/amplication-design-system/src/components/Checkbox/CheckboxList.stories.tsx
  packages/amplication-design-system/src/components/Checkbox/CheckboxListField.tsx
  packages/amplication-design-system/src/index.ts
Labels: type: enhancement

#902 Use CircleIcon from design system
  packages/amplication-client/src/Components/CircleIcon.scss
  packages/amplication-client/src/Entity/EntityFieldListItem.tsx
  packages/amplication-client/src/VersionControl/ActionLog.tsx
  packages/amplication-client/src/VersionControl/Deployment.tsx
  packages/amplication-client/src/VersionControl/constants.ts
  packages/amplication-design-system/src/components/CircleIcon.stories.tsx
  packages/amplication-design-system/src/components/CircleIcon.tsx
  packages/amplication-design-system/src/components/CircleIcon/CircleIcon.scss
  packages/amplication-design-system/src/components/CircleIcon/CircleIcon.stories.tsx
  packages/amplication-design-system/src/components/CircleIcon/CircleIcon.tsx
  packages/amplication-design-system/src/components/TextInput.tsx
  packages/amplication-design-system/src/index.ts
Labels: type: enhancement

#903 Design System: Dialog
  packages/amplication-client/src/Application/Applications.tsx
  packages/amplication-client/src/Components/DisplayNameField.tsx
  packages/amplication-client/src/Components/PluralDisplayNameField.tsx
  packages/amplication-client/src/Entity/EntityFieldListItem.tsx
  packages/amplication-client/src/Entity/EntityList.tsx
  packages/amplication-client/src/Entity/EntityListItem.tsx
  packages/amplication-client/src/VersionControl/BuildDeployments.tsx
  packages/amplication-client/src/VersionControl/PendingChanges.tsx
  packages/amplication-design-system/package-lock.json
  packages/amplication-design-system/package.json
  packages/amplication-design-system/src/components/ConfirmationDialog/ConfirmationDialog.scss
  packages/amplication-design-system/src/components/ConfirmationDialog/ConfirmationDialog.stories.tsx
  packages/amplication-design-system/src/components/ConfirmationDialog/ConfirmationDialog.tsx
  packages/amplication-design-system/src/components/Dialog/Dialog.scss
  packages/amplication-design-system/src/components/Dialog/Dialog.stories.tsx
  packages/amplication-design-system/src/components/Dialog/Dialog.tsx
  packages/amplication-design-system/src/components/TextInput.tsx
  packages/amplication-design-system/src/index.ts
Labels: type: enhancement

#905 Design system : Multi state toggle
  packages/amplication-client/src/Pages/EntityPageForm.tsx
  packages/amplication-client/src/Permissions/EntityPermissionAction.tsx
  packages/amplication-client/src/VersionControl/BuildNewVersion.tsx
  packages/amplication-client/src/VersionControl/PendingChangeDiff.tsx
  packages/amplication-design-system/src/components/MultiStateToggle/MultiStateToggle.scss
  packages/amplication-design-system/src/components/MultiStateToggle/MultiStateToggle.stories.tsx
  packages/amplication-design-system/src/components/MultiStateToggle/MultiStateToggle.tsx
  packages/amplication-design-system/src/components/MultiStateToggle/MultiStateToggleField.stories.tsx
  packages/amplication-design-system/src/components/MultiStateToggle/MultiStateToggleField.tsx
  packages/amplication-design-system/src/index.ts
Labels: type: enhancement

#906 Design system : Panel
  packages/amplication-client/src/Application/ApplicationHome.tsx
  packages/amplication-client/src/Application/CurrentBuildTile.tsx
  packages/amplication-client/src/Application/EntitiesTile.tsx
  packages/amplication-client/src/Application/PendingChangesTile.tsx
  packages/amplication-client/src/Application/RolesTile.tsx
  packages/amplication-client/src/Entity/Entity.tsx
  packages/amplication-client/src/Entity/EntityForm.tsx
  packages/amplication-client/src/Layout/WelcomePage.tsx
  packages/amplication-client/src/Permissions/EntityPermissionAction.tsx
  packages/amplication-client/src/Permissions/EntityPermissionField.tsx
  packages/amplication-client/src/VersionControl/Build.tsx
  packages/amplication-client/src/VersionControl/LastCommit.tsx
  packages/amplication-client/src/VersionControl/PendingChangeWithCompare.tsx
  packages/amplication-design-system/package-lock.json
  packages/amplication-design-system/package.json
  packages/amplication-design-system/src/components/Panel/Panel.scss
  packages/amplication-design-system/src/components/Panel/Panel.stories.tsx
  packages/amplication-design-system/src/components/Panel/Panel.tsx
  packages/amplication-design-system/src/components/PanelCollapsible/PanelCollapsible.scss
  packages/amplication-design-system/src/components/PanelCollapsible/PanelCollapsible.stories.tsx
  packages/amplication-design-system/src/components/PanelCollapsible/PanelCollapsible.tsx
  packages/amplication-design-system/src/index.ts
Labels: type: enhancement

#907 Design System: Toggle Button
  packages/amplication-client/src/Permissions/ActionRole.tsx
  packages/amplication-design-system/src/components/ToggleButton/ToggleButton.scss
  packages/amplication-design-system/src/components/ToggleButton/ToggleButton.stories.tsx
  packages/amplication-design-system/src/components/ToggleButton/ToggleButton.tsx
  packages/amplication-design-system/src/index.ts
Labels: type: enhancement

#908 Design System: Toggle Field
  packages/amplication-client/src/Entity/EntityFieldForm.tsx
  packages/amplication-client/src/Entity/SchemaField.tsx
  packages/amplication-client/src/Permissions/EntityPermissionAction.tsx
  packages/amplication-design-system/src/components/Toggle/Toggle.scss
  packages/amplication-design-system/src/components/Toggle/Toggle.stories.tsx
  packages/amplication-design-system/src/components/Toggle/Toggle.tsx
  packages/amplication-design-system/src/components/Toggle/ToggleField.stories.tsx
  packages/amplication-design-system/src/components/Toggle/ToggleField.tsx
  packages/amplication-design-system/src/index.ts
Labels: type: enhancement

#909 Client: remove text field
  packages/amplication-client/src/Components/TextField.tsx
Labels: type: enhancement

#910 Design system : UserAvatar
  packages/amplication-client/src/Components/UserBadge.tsx
  packages/amplication-design-system/src/components/UserAvatar/UserAvatar.scss
  packages/amplication-design-system/src/components/UserAvatar/UserAvatar.stories.tsx
  packages/amplication-design-system/src/components/UserAvatar/UserAvatar.tsx
  packages/amplication-design-system/src/index.ts
Labels: type: enhancement

#911 Design System: UserAndTime
  packages/amplication-client/src/Application/CurrentBuildTile.tsx
  packages/amplication-client/src/Entity/EntityListItem.tsx
  packages/amplication-client/src/VersionControl/Build.tsx
  packages/amplication-client/src/VersionControl/CommitHeader.tsx
  packages/amplication-client/src/VersionControl/CommitListItem.tsx
  packages/amplication-client/src/VersionControl/LastCommit.tsx
  packages/amplication-design-system/package-lock.json
  packages/amplication-design-system/package.json
  packages/amplication-design-system/src/components/UserAndTime/UserAndTime.scss
  packages/amplication-design-system/src/components/UserAndTime/UserAndTime.stories.tsx
  packages/amplication-design-system/src/components/UserAndTime/UserAndTime.tsx
  packages/amplication-design-system/src/index.ts
  packages/amplication-design-system/src/style/css-variables.scss
Labels: type: enhancement

#912 Design System: Time Since
  packages/amplication-design-system/src/components/TimeSince/TimeSince.scss
  packages/amplication-design-system/src/components/TimeSince/TimeSince.stories.tsx
  packages/amplication-design-system/src/components/TimeSince/TimeSince.tsx
  packages/amplication-design-system/src/index.ts
Labels: type: enhancement

#913 Design system: menu
  packages/amplication-design-system/package-lock.json
  packages/amplication-design-system/package.json
  packages/amplication-design-system/src/assets/fonts/amplicationicon.eot
  packages/amplication-design-system/src/assets/fonts/amplicationicon.svg
  packages/amplication-design-system/src/assets/fonts/amplicationicon.ttf
  packages/amplication-design-system/src/assets/fonts/amplicationicon.woff
  packages/amplication-design-system/src/components/CircleBadge/CircleBadge.scss
  packages/amplication-design-system/src/components/CircleBadge/CircleBadge.stories.tsx
  packages/amplication-design-system/src/components/CircleBadge/CircleBadge.tsx
  packages/amplication-design-system/src/components/Menu/Menu.scss
  packages/amplication-design-system/src/components/Menu/Menu.tsx
  packages/amplication-design-system/src/components/Menu/MenuItem.scss
  packages/amplication-design-system/src/components/Menu/MenuItem.tsx
  packages/amplication-design-system/src/components/Menu/Meun.stories.tsx
  packages/amplication-design-system/src/index.ts
  packages/amplication-design-system/src/style/parameters.scss
Labels: type: enhancement

#914 Design System: Create button folder
  packages/amplication-design-system/src/components/Button/Button.scss
  packages/amplication-design-system/src/components/Button/Button.stories.tsx
  packages/amplication-design-system/src/components/Button/Button.tsx
  packages/amplication-design-system/src/components/ConfirmationDialog/ConfirmationDialog.tsx
  packages/amplication-design-system/src/components/DataGrid/DataGrid.stories.tsx
  packages/amplication-design-system/src/components/DataGrid/DataGrid.tsx
  packages/amplication-design-system/src/components/Dialog/Dialog.tsx
  packages/amplication-design-system/src/components/Menu/MenuItem.tsx
  packages/amplication-design-system/src/components/Panel/Panel.stories.tsx
  packages/amplication-design-system/src/components/PanelCollapsible/PanelCollapsible.tsx
  packages/amplication-design-system/src/components/SelectMenu/SelectMenu.stories.tsx
  packages/amplication-design-system/src/components/SelectMenu/SelectMenu.tsx
  packages/amplication-design-system/src/components/TextInput.tsx
  packages/amplication-design-system/src/index.ts
Labels: type: enhancement

#915 Design System: Create TextInput folder
  packages/amplication-design-system/src/components/TextField/TextField.tsx
  packages/amplication-design-system/src/components/TextInput/TextInput.scss
  packages/amplication-design-system/src/components/TextInput/TextInput.stories.tsx
  packages/amplication-design-system/src/components/TextInput/TextInput.tsx
  packages/amplication-design-system/src/index.ts
Labels: type: enhancement

#916 Design System: Fix DataGrid types reference
  packages/amplication-design-system/src/components/DataGrid/DataGrid.stories.tsx
  packages/amplication-design-system/src/components/DataGrid/DataGrid.tsx
  packages/amplication-design-system/src/components/DataGrid/DataGridSortableHeader.tsx
  packages/amplication-design-system/src/components/DataGrid/types.ts
  packages/amplication-design-system/src/index.ts
Labels: type: bug

#917 Design System : Layout and Page
  packages/amplication-client/__mocks__/styleMock.js
  packages/amplication-client/package.json
  packages/amplication-client/src/Application/ApplicationBadge.scss
  packages/amplication-client/src/Application/ApplicationBadge.tsx
  packages/amplication-client/src/Application/ApplicationIcon.scss
  packages/amplication-client/src/Application/ApplicationIcon.tsx
  packages/amplication-client/src/Application/ApplicationLayout.tsx
  packages/amplication-client/src/CommandPalette/CommandPalette.scss
  packages/amplication-client/src/CommandPalette/CommandPalette.tsx
  packages/amplication-design-system/.storybook/preview.js
  packages/amplication-design-system/package-lock.json
  packages/amplication-design-system/package.json
  packages/amplication-design-system/src/components/DataGrid/DataGrid.stories.tsx
  packages/amplication-design-system/src/components/MainLayout/MainLayout.scss
  packages/amplication-design-system/src/components/MainLayout/MainLayout.stories.tsx
  packages/amplication-design-system/src/components/MainLayout/MainLayout.tsx
  packages/amplication-design-system/src/components/Menu/Meun.stories.tsx
  packages/amplication-design-system/src/components/Page/Page.scss
  packages/amplication-design-system/src/components/Page/Page.tsx
  packages/amplication-design-system/src/components/Panel/Panel.stories.tsx
  packages/amplication-design-system/src/components/PanelCollapsible/PanelCollapsible.stories.tsx
  packages/amplication-design-system/src/components/SelectMenu/SelectMenu.stories.tsx
Labels: type: enhancement

#918 Remove client unused packages
  packages/amplication-client/package-lock.json
  packages/amplication-client/package.json
  packages/amplication-client/src/Entity/EntityFieldList.tsx
  packages/amplication-client/src/Entity/EntityList.tsx
  packages/amplication-client/src/VersionControl/CommitList.tsx
  packages/amplication-design-system/src/components/Menu/Meun.stories.tsx
  packages/amplication-design-system/src/components/Panel/Panel.stories.tsx
  packages/amplication-design-system/src/components/PanelCollapsible/PanelCollapsible.stories.tsx
  packages/amplication-design-system/src/components/SelectMenu/SelectMenu.stories.tsx
Labels: type: enhancement

#919 DSG: admin UI navigation
  packages/amplication-data-service-generator/src/admin/app/App.template.tsx
  packages/amplication-data-service-generator/src/admin/app/create-app.ts
  packages/amplication-data-service-generator/src/admin/navigation/Navigation.template.tsx
  packages/amplication-data-service-generator/src/admin/static/src/Login.tsx
  packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
Labels: type: enhancement

#920 DSG: admin UI input label
  packages/amplication-data-service-generator/src/admin/entity/create-field-input.ts
  packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
Labels: type: enhancement

#921 DSG: Admin UI list view
  packages/amplication-data-service-generator/src/admin/entity/create-field-value.ts
  packages/amplication-data-service-generator/src/admin/entity/entity-list-component/create-entity-list-component.ts
  packages/amplication-data-service-generator/src/admin/entity/entity-list-component/entity-list-component.template.tsx
  packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
Labels: type: enhancement

#926 Design-system: export Page and MainLayout
  packages/amplication-design-system/src/components/MainLayout/MainLayout.tsx
  packages/amplication-design-system/src/components/Page/Page.tsx
  packages/amplication-design-system/src/index.ts
Labels: type: enhancement

#927 Design system: bump version
  packages/amplication-data-service-generator/src/admin/static/package.json
  packages/amplication-design-system/package-lock.json
Labels: type: enhancement

#922 DSG: admin UI layout
  packages/amplication-data-service-generator/src/admin/app/App.template.tsx
  packages/amplication-data-service-generator/src/admin/app/create-app.ts
  packages/amplication-data-service-generator/src/admin/create-admin.ts
  packages/amplication-data-service-generator/src/admin/navigation/Navigation.template.tsx
  packages/amplication-data-service-generator/src/admin/static/src/index.tsx
  packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
Labels: type: enhancement

#929 Design system: align logo in menu
  packages/amplication-design-system/src/components/Menu/Menu.scss
Labels: type: style

#928 Admin UI navigation style
  packages/amplication-data-service-generator/src/admin/navigation/Navigation.template.tsx
  packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
Labels: type: enhancement

#931 Design system: Form
  packages/amplication-data-service-generator/src/admin/static/src/index.tsx
  packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
  packages/amplication-design-system/src/components/Form/Form.scss
  packages/amplication-design-system/src/components/Form/Form.stories.tsx
  packages/amplication-design-system/src/components/Form/Form.tsx
  packages/amplication-design-system/src/components/SelectField/SelectField.tsx
  packages/amplication-design-system/src/components/TextInput/TextInput.tsx
  packages/amplication-design-system/src/components/Toggle/Toggle.scss
  packages/amplication-design-system/src/components/Toggle/Toggle.tsx
  packages/amplication-design-system/src/components/constants.ts
  packages/amplication-design-system/src/index.ts
  packages/amplication-design-system/src/style/css-variables.scss
  packages/amplication-design-system/src/style/mixin.scss
Labels: type: enhancement

#933 Admin UI forms
  packages/amplication-data-service-generator/src/admin/entity/create-field-input.ts
  packages/amplication-data-service-generator/src/admin/entity/entity-component/create-entity-component.ts
  packages/amplication-data-service-generator/src/admin/entity/entity-component/entity-component.template.tsx
  packages/amplication-data-service-generator/src/admin/entity/new-entity-component/new-entity-component.template.tsx
  packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
Labels: type: enhancement

#938 Design system : mobile width
  packages/amplication-client/src/index.scss
  packages/amplication-design-system/src/components/MainLayout/MainLayout.scss
  packages/amplication-design-system/src/components/Page/Page.scss
Labels: type: style

#935 Admin UI : Entity select components
  packages/amplication-data-service-generator/src/admin/create-admin.ts
  packages/amplication-data-service-generator/src/admin/entity/create-entities-components.ts
  packages/amplication-data-service-generator/src/admin/entity/create-entity-components-modules.ts
  packages/amplication-data-service-generator/src/admin/entity/create-entity-components.ts
  packages/amplication-data-service-generator/src/admin/entity/create-entity-select-components.ts
  packages/amplication-data-service-generator/src/admin/entity/create-field-input.ts
  packages/amplication-data-service-generator/src/admin/entity/entity-component/create-entity-component.ts
  packages/amplication-data-service-generator/src/admin/entity/entity-select-component/create-entity-select-component.ts
  packages/amplication-data-service-generator/src/admin/entity/entity-select-component/entity-select-component.template.tsx
  packages/amplication-data-service-generator/src/admin/entity/new-entity-component/create-new-entity-component.ts
  packages/amplication-data-service-generator/src/create-data-service.ts
  packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
Labels: type: enhancement

#936 Admin UI : Option Set
  packages/amplication-data-service-generator/src/admin/entity/create-field-input.ts
  packages/amplication-data-service-generator/src/admin/entity/entity-component/entity-component.template.tsx
  packages/amplication-data-service-generator/src/admin/entity/new-entity-component/new-entity-component.template.tsx
  packages/amplication-data-service-generator/src/types.ts
Labels: type: enhancement

#937 Admin UI : Entity list
  packages/amplication-data-service-generator/src/admin/entity/entity-list-component/create-entity-list-component.ts
  packages/amplication-data-service-generator/src/admin/entity/entity-list-component/entity-list-component.template.tsx
Labels: type: bug

#939 Admin UI - field value
  packages/amplication-data-service-generator/src/admin/entity/create-field-value.ts
  packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
  packages/amplication-data-service-generator/src/util/ast.ts
Labels: type: enhancement

#940 Admin UI breadcrumbs
  packages/amplication-data-service-generator/src/admin/app/App.template.tsx
  packages/amplication-data-service-generator/src/admin/entity/create-field-input.ts
  packages/amplication-data-service-generator/src/admin/entity/entity-component/entity-component.template.tsx
  packages/amplication-data-service-generator/src/admin/entity/entity-list-component/entity-list-component.template.tsx
  packages/amplication-data-service-generator/src/admin/static/src/components/breadcrumbs/BreadcrumbsContext.ts
  packages/amplication-data-service-generator/src/admin/static/src/components/breadcrumbs/BreadcrumbsProvider.tsx
  packages/amplication-data-service-generator/src/admin/static/src/components/breadcrumbs/use-breadcrumbs.ts
Labels: type: enhancement

#941 Design system: Breadcrumbs
  lerna.json
  packages/amplication-client/package-lock.json
  packages/amplication-client/package.json
  packages/amplication-data-service-generator/package-lock.json
  packages/amplication-data-service-generator/package.json
  packages/amplication-design-system/package-lock.json
  packages/amplication-design-system/package.json
  packages/amplication-design-system/src/components/Breadcrumbs/Breadcrumbs.scss
  packages/amplication-design-system/src/components/Breadcrumbs/Breadcrumbs.stories.tsx
  packages/amplication-design-system/src/components/Breadcrumbs/Breadcrumbs.tsx
  packages/amplication-design-system/src/index.ts
  packages/amplication-server/package-lock.json
  packages/amplication-server/package.json
Labels: type: enhancement

#951 Admin UI: Boolean
  packages/amplication-data-service-generator/src/admin/entity/create-field-input.ts
  packages/amplication-data-service-generator/src/admin/entity/create-field-value.ts
  packages/amplication-data-service-generator/src/admin/entity/entity-component/entity-component.template.tsx
  packages/amplication-data-service-generator/src/admin/entity/entity-list-component/entity-list-component.template.tsx
  packages/amplication-data-service-generator/src/admin/entity/new-entity-component/new-entity-component.template.tsx
  packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
  packages/amplication-data-service-generator/src/tests/entities.ts
Labels: type: enhancement

#955 Design System: Style data grid header
  packages/amplication-design-system/src/components/DataGrid/DataGrid.scss
Labels: type: style

#956 Design system: Toggle margins
  packages/amplication-design-system/src/components/Form/Form.stories.tsx
  packages/amplication-design-system/src/components/Toggle/Toggle.scss
Labels: type: style

#958 Design System: link style
  packages/amplication-design-system/src/components/DataGrid/DataGrid.stories.tsx
  packages/amplication-design-system/src/index.scss
Labels: type: style

#959 Design system: Base CSS
  packages/amplication-client/src/index.scss
  packages/amplication-client/src/style/css-variables.css
  packages/amplication-design-system/.storybook/preview.js
  packages/amplication-design-system/src/index.scss
  packages/amplication-design-system/src/index.ts
  packages/amplication-design-system/src/style/css-variables.scss
  packages/amplication-design-system/src/style/index.scss
Labels: type: perf

#953 Admin UI - Role select
  packages/amplication-data-service-generator/src/admin/create-admin.ts
  packages/amplication-data-service-generator/src/admin/create-roles-module.ts
  packages/amplication-data-service-generator/src/admin/entity/create-field-input.ts
  packages/amplication-data-service-generator/src/admin/entity/create-field-value.ts
  packages/amplication-data-service-generator/src/admin/entity/entity-component/entity-component.template.tsx
  packages/amplication-data-service-generator/src/admin/entity/new-entity-component/new-entity-component.template.tsx
  packages/amplication-data-service-generator/src/admin/static/src/user/RoleSelect.tsx
  packages/amplication-data-service-generator/src/server/resource/dto/create-field-class-property.spec.ts
  packages/amplication-data-service-generator/src/server/resource/dto/create-field-class-property.ts
  packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
  packages/amplication-data-service-generator/src/tests/entities.ts
  packages/amplication-data-service-generator/src/tests/roles.ts
  packages/amplication-data-service-generator/src/util/ast.ts
Labels: type: enhancement

#960 Design System: Form Header
  packages/amplication-design-system/src/components/Form/Form.stories.tsx
  packages/amplication-design-system/src/components/Form/FormHeader.scss
  packages/amplication-design-system/src/components/Form/FormHeader.tsx
  packages/amplication-design-system/src/index.ts
Labels: type: enhancement

#962 DSG: Admin UI Design System version bump
  packages/amplication-data-service-generator/src/admin/static/package-lock.json
  packages/amplication-data-service-generator/src/admin/static/package.json
  packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
Labels: type: enhancement

#968 Design system: Form header content
  packages/amplication-design-system/src/components/Form/Form.scss
  packages/amplication-design-system/src/components/Form/Form.stories.tsx
  packages/amplication-design-system/src/components/Form/Form.tsx
Labels: type: enhancement

#969 Admin UI: Bump design system to alpha.8
  packages/amplication-data-service-generator/src/admin/static/package-lock.json
  packages/amplication-data-service-generator/src/admin/static/package.json
  packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
Labels: type: enhancement

#971 Admin UI form header
  packages/amplication-data-service-generator/src/admin/entity/entity-component/entity-component.template.tsx
  packages/amplication-data-service-generator/src/admin/entity/new-entity-component/new-entity-component.template.tsx
  packages/amplication-data-service-generator/src/admin/static/src/index.css
  packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
Labels: type: enhancement

#972 Admin UI breadcrumbs
  packages/amplication-data-service-generator/src/admin/entity/entity-component/create-entity-component.ts
  packages/amplication-data-service-generator/src/admin/entity/entity-component/entity-component.template.tsx
  packages/amplication-data-service-generator/src/admin/entity/new-entity-component/create-new-entity-component.ts
  packages/amplication-data-service-generator/src/admin/entity/new-entity-component/new-entity-component.template.tsx
Labels: type: enhancement

#977 Admin UI - Breadcrumbs hierarchy
  packages/amplication-data-service-generator/src/admin/entity/entity-component/create-entity-component.ts
  packages/amplication-data-service-generator/src/admin/entity/entity-component/entity-component.template.tsx
  packages/amplication-data-service-generator/src/admin/entity/entity-index-component/create-entity-index-component.ts
  packages/amplication-data-service-generator/src/admin/entity/entity-index-component/entity-index-component.template.tsx
  packages/amplication-data-service-generator/src/admin/entity/entity-list-component/create-entity-list-component.ts
  packages/amplication-data-service-generator/src/admin/entity/entity-list-component/entity-list-component.template.tsx
  packages/amplication-data-service-generator/src/admin/entity/new-entity-component/create-new-entity-component.ts
  packages/amplication-data-service-generator/src/admin/entity/new-entity-component/new-entity-component.template.tsx
  packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
Labels: type: enhancement

#978 Design System: Snackbar
  packages/amplication-design-system/package-lock.json
  packages/amplication-design-system/package.json
  packages/amplication-design-system/src/components/Snackbar/Snackbar.scss
  packages/amplication-design-system/src/components/Snackbar/Snackbar.stories.tsx
  packages/amplication-design-system/src/components/Snackbar/Snackbar.tsx
  packages/amplication-design-system/src/index.ts
Labels: type: enhancement

#980 Design system: form responsive
  packages/amplication-design-system/src/components/Form/Form.scss
Labels: type: bug, type: style

#981 Admin UI: Error Handling
  packages/amplication-data-service-generator/src/admin/entity/entity-component/entity-component.template.tsx
  packages/amplication-data-service-generator/src/admin/entity/entity-list-component/entity-list-component.template.tsx
  packages/amplication-data-service-generator/src/admin/entity/new-entity-component/new-entity-component.template.tsx
  packages/amplication-data-service-generator/src/admin/static/package-lock.json
  packages/amplication-data-service-generator/src/admin/static/package.json
  packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
Labels: type: enhancement

#983 Test More Fields in default user entity
  packages/amplication-data-service-generator/src/server/resource/controller/controller.template.ts
  packages/amplication-data-service-generator/src/server/resource/test/create-controller-spec.ts
  packages/amplication-data-service-generator/src/server/seed/create-seed.ts
  packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
  packages/amplication-data-service-generator/src/tests/entities.ts
Labels: type: bug, type: test

#744 Data Service Generator: Add password hashing to services
  packages/amplication-data-service-generator/package-lock.json
  packages/amplication-data-service-generator/package.json
  packages/amplication-data-service-generator/src/server/resource/create-resource.ts
  packages/amplication-data-service-generator/src/server/resource/service/create-service.ts
  packages/amplication-data-service-generator/src/server/resource/service/service.template.ts
  packages/amplication-data-service-generator/src/server/static/.env
  packages/amplication-data-service-generator/src/server/static/package-lock.json
  packages/amplication-data-service-generator/src/server/static/package.json
  packages/amplication-data-service-generator/src/server/static/src/auth/auth.module.ts
  packages/amplication-data-service-generator/src/server/static/src/auth/auth.service.ts
  packages/amplication-data-service-generator/src/server/static/src/auth/password.service.spec.ts
  packages/amplication-data-service-generator/src/server/static/src/auth/password.service.ts
  packages/amplication-data-service-generator/src/server/static/src/prisma.util.ts
  packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
  packages/amplication-data-service-generator/src/util/ast.spec.ts
  packages/amplication-data-service-generator/src/util/ast.ts
  packages/amplication-data-service-generator/src/util/nestjs-code-generation.ts
  packages/amplication-data-service-generator/src/util/parser.ts
  packages/amplication-data-service-generator/src/util/partial-parser.spec.ts
  packages/amplication-data-service-generator/src/util/partial-parser.ts
  packages/amplication-data-service-generator/test/data-service-generator.e2e-spec.ts
Labels: type: enhancement

#984 DSG: Fix creation of enum array DTO fields
  packages/amplication-data-service-generator/src/server/resource/dto/create-field-class-property.ts
  packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
Labels: type: bug

#988 Prevent required lookup user
  packages/amplication-client/src/Entity/EntityFieldForm.tsx
  packages/amplication-server/src/core/entity/entity.service.ts
Labels: type: enhancement

#871 Server: Add tests to Deployment Service
  packages/amplication-server/src/core/deployment/deployment.service.spec.ts
Labels: type: test

#1004 Admin UI: List column order
  packages/amplication-data-service-generator/src/admin/entity/entity-list-component/create-entity-list-component.ts
  packages/amplication-data-service-generator/src/server/static/src/auth/auth.service.ts
  packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
  packages/amplication-data-service-generator/src/tests/entities.ts
Labels: type: bug

#1006 DSG: Admin UI Redirect After Create
  packages/amplication-data-service-generator/src/admin/entity/new-entity-component/new-entity-component.template.tsx
  packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
Labels: type: enhancement

#1007 DSG: Admin UI: Empty Title
  packages/amplication-data-service-generator/src/admin/entity/entity-component/entity-component.template.tsx
  packages/amplication-data-service-generator/src/admin/entity/entity-select-component/entity-select-component.template.tsx
  packages/amplication-data-service-generator/src/admin/entity/entity-title-component/entity-title-component.template.tsx
  packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
Labels: type: bug

#1009 Admin UI: delete button
  packages/amplication-data-service-generator/src/admin/entity/entity-component/entity-component.template.tsx
  packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
Labels: type: enhancement

#1017 DSG: Fix readme and local run of generated app
  package.json
  packages/amplication-data-service-generator/src/server/static/.env
  packages/amplication-data-service-generator/src/server/static/README.md
  packages/amplication-data-service-generator/src/server/static/docker-compose.db.yml
  packages/amplication-data-service-generator/src/server/static/package.json
  packages/amplication-data-service-generator/src/static/README.md
  packages/amplication-data-service-generator/src/static/docker-compose.yml
  packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
Labels: type: bug, type: enhancement

#1020 Admin UI default password
  packages/amplication-data-service-generator/src/admin/static/src/Login.tsx
  packages/amplication-data-service-generator/src/admin/static/src/login.scss
  packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
Labels: type: enhancement

#1025 DSG: GraphQL
  packages/amplication-data-service-generator/package-lock.json
  packages/amplication-data-service-generator/package.json
  packages/amplication-data-service-generator/src/create-data-service.ts
  packages/amplication-data-service-generator/src/server/app-module/create-app-module.ts
  packages/amplication-data-service-generator/src/server/resource/controller/create-controller.ts
  packages/amplication-data-service-generator/src/server/resource/create-dtos.ts
  packages/amplication-data-service-generator/src/server/resource/create-resource.ts
  packages/amplication-data-service-generator/src/server/resource/dto/create-create-input.spec.ts
  packages/amplication-data-service-generator/src/server/resource/dto/create-create-input.ts
  packages/amplication-data-service-generator/src/server/resource/dto/create-dto-module.spec.ts
  packages/amplication-data-service-generator/src/server/resource/dto/create-dto-module.ts
  packages/amplication-data-service-generator/src/server/resource/dto/create-entity-dto.spec.ts
  packages/amplication-data-service-generator/src/server/resource/dto/create-entity-dto.ts
  packages/amplication-data-service-generator/src/server/resource/dto/create-enum-dto-module.ts
  packages/amplication-data-service-generator/src/server/resource/dto/create-field-class-property.spec.ts
  packages/amplication-data-service-generator/src/server/resource/dto/create-field-class-property.ts
  packages/amplication-data-service-generator/src/server/resource/dto/create-input.ts
  packages/amplication-data-service-generator/src/server/resource/dto/create-update-input.spec.ts
  packages/amplication-data-service-generator/src/server/resource/dto/create-update-input.ts
  packages/amplication-data-service-generator/src/server/resource/dto/create-where-input.spec.ts
  packages/amplication-data-service-generator/src/server/resource/dto/create-where-input.ts
  packages/amplication-data-service-generator/src/server/resource/dto/create-where-unique-input.spec.ts
  packages/amplication-data-service-generator/src/server/resource/dto/create-where-unique-input.ts
  packages/amplication-data-service-generator/src/server/resource/dto/graphql/create/create-args.template.ts
  packages/amplication-data-service-generator/src/server/resource/dto/graphql/create/create-create-args.ts
  packages/amplication-data-service-generator/src/server/resource/dto/graphql/delete/create-delete-args.ts
  packages/amplication-data-service-generator/src/server/resource/dto/graphql/delete/delete-args.template.ts
  packages/amplication-data-service-generator/src/server/resource/dto/graphql/find-many/create-find-many-args.ts
  packages/amplication-data-service-generator/src/server/resource/dto/graphql/find-many/find-many-args.template.ts
  packages/amplication-data-service-generator/src/server/resource/dto/graphql/find-one/create-find-one-args.ts
  packages/amplication-data-service-generator/src/server/resource/dto/graphql/find-one/find-one-args.template.ts
  packages/amplication-data-service-generator/src/server/resource/dto/graphql/update/create-update-args.ts
  packages/amplication-data-service-generator/src/server/resource/dto/graphql/update/update-args.template.ts
  packages/amplication-data-service-generator/src/server/resource/dto/nestjs-graphql.util.ts
  packages/amplication-data-service-generator/src/server/resource/module/create-module.ts
  packages/amplication-data-service-generator/src/server/resource/module/module.template.ts
  packages/amplication-data-service-generator/src/server/resource/resolver/create-resolver.ts
  packages/amplication-data-service-generator/src/server/resource/resolver/resolver.template.ts
  packages/amplication-data-service-generator/src/server/resource/resolver/to-many.template.ts
  packages/amplication-data-service-generator/src/server/resource/resolver/to-one.template.ts
  packages/amplication-data-service-generator/src/server/resource/service/create-service.ts
  packages/amplication-data-service-generator/src/server/static/package-lock.json
  packages/amplication-data-service-generator/src/server/static/package.json
  packages/amplication-data-service-generator/src/server/static/src/auth/gqlAC.guard.ts
  packages/amplication-data-service-generator/src/server/static/src/auth/gqlBasicAuth.guard.ts
  packages/amplication-data-service-generator/src/server/static/src/auth/gqlUserRoles.decorator.ts
  packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
  packages/amplication-data-service-generator/src/util/ast.spec.ts
  packages/amplication-data-service-generator/src/util/ast.ts
  packages/amplication-data-service-generator/src/util/field.ts
  packages/amplication-data-service-generator/src/util/prisma-code-generation.ts
  packages/amplication-data-service-generator/test/data-service-generator.e2e-spec.ts
Labels: type: enhancement

#1027 Client: update poll time
  packages/amplication-client/src/VersionControl/PendingChanges.tsx
  packages/amplication-client/src/VersionControl/useBuildWatchStatus.tsx
Labels: type: enhancement

#1028 App dashboard
  packages/amplication-client/src/Application/ApplicationForm.tsx
  packages/amplication-client/src/Application/ApplicationHome.scss
  packages/amplication-client/src/Application/ApplicationHome.tsx
  packages/amplication-client/src/Application/CurrentBuildTile.tsx
  packages/amplication-client/src/Application/EntitiesTile.tsx
  packages/amplication-client/src/Application/PendingChangesTile.tsx
  packages/amplication-client/src/Application/RolesTile.tsx
  packages/amplication-client/src/Application/constants.ts
  packages/amplication-client/src/Components/ColorSelectButton.scss
  packages/amplication-client/src/Components/ColorSelectButton.tsx
  packages/amplication-client/src/assets/app-banner/app-banner-bg.svg
  packages/amplication-client/src/style/css-variables.css
  packages/amplication-client/src/style/mixin.scss
Labels: type: enhancement

#1034 Last commit tile
  packages/amplication-client/src/Application/ApplicationHome.tsx
  packages/amplication-client/src/Application/LastCommitTile.scss
  packages/amplication-client/src/Application/LastCommitTile.tsx
Labels: type: enhancement

#1046 Server: Entity Service Spec Coverage
  packages/amplication-server/src/core/entity/entity.service.spec.ts
  packages/amplication-server/src/core/entity/entity.service.ts
Labels: type: test

#1044 Remove app version display
  packages/amplication-client/src/Application/ApplicationCard.tsx
Labels: type: bug

#1048 Server: entity service spec coverage
  packages/amplication-server/src/core/entity/entity.service.spec.ts
  packages/amplication-server/src/core/entity/entity.service.ts
Labels: type: test

#1043 Delete user button
  packages/amplication-client/src/Entity/EntityFieldListItem.tsx
  packages/amplication-client/src/Entity/EntityListItem.tsx
  packages/amplication-client/src/Entity/constants.ts
Labels: type: bug

#1041 Align button on grid
  packages/amplication-client/src/Entity/EntityFieldListItem.tsx
  packages/amplication-client/src/Entity/EntityListItem.tsx
Labels: type: bug

#1038 New field shortcut
  packages/amplication-client/src/Entity/NewEntityField.tsx
Labels: type: bug

#1039 Fix disabled textbox style
  packages/amplication-design-system/src/style/mixin.scss
Labels: type: bug

#1040 Remove links to publish page
  packages/amplication-client/src/CommandPalette/CommandPalette.tsx
Labels: type: bug

#1055 DSG: Make GraphQL Where Input Optional
  packages/amplication-data-service-generator/src/server/resource/dto/graphql/find-many/create-find-many-args.spec.ts
  packages/amplication-data-service-generator/src/server/resource/dto/graphql/find-many/find-many-args.template.ts
  packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
Labels: type: enhancement

#1057 DSG: Fix GraphQL DTOs
  packages/amplication-client/.prettierignore
  packages/amplication-data-service-generator/.eslintignore
  packages/amplication-data-service-generator/.prettierignore
  packages/amplication-data-service-generator/src/server/resource/controller/create-controller.ts
  packages/amplication-data-service-generator/src/server/resource/controller/create-data-mapping.spec.ts
  packages/amplication-data-service-generator/src/server/resource/controller/create-data-mapping.ts
  packages/amplication-data-service-generator/src/server/resource/dto/create-field-class-property.ts
  packages/amplication-data-service-generator/src/server/resource/dto/graphql/find-many/create-find-many-args.spec.ts
  packages/amplication-data-service-generator/src/server/resource/dto/graphql/find-many/find-many-args.template.ts
  packages/amplication-data-service-generator/src/server/resource/resolver/create-resolver.ts
  packages/amplication-data-service-generator/src/server/resource/resolver/resolver.template.ts
  packages/amplication-data-service-generator/src/server/static/.pretttierignore
  packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
  packages/amplication-data/.prettierignore
  packages/amplication-design-system/.eslintignore
  packages/amplication-design-system/.prettierignore
  packages/amplication-e2e-tester/.prettierignore
  packages/amplication-server/.prettierignore
Labels: type: bug

#1064 DSG: ast test coverage
  packages/amplication-data-service-generator/src/util/ast.spec.ts
  packages/amplication-data-service-generator/src/util/ast.ts
  packages/amplication-data-service-generator/src/util/nestjs-code-generation.ts
Labels: type: enhancement, type: test

#1066 DSG: ast test coverage
  packages/amplication-data-service-generator/src/util/ast.spec.ts
Labels: type: enhancement, type: test

#1069 Pending changes badge
  packages/amplication-client/src/Application/ApplicationLayout.tsx
  packages/amplication-client/src/Layout/MenuItem.scss
  packages/amplication-client/src/Layout/MenuItemWithFixedPanel.tsx
  packages/amplication-client/src/VersionControl/PendingChangesBar.scss
  packages/amplication-client/src/style/css-variables.css
  packages/amplication-client/src/style/mixin.scss
Labels: type: enhancement

#1071 Server & Container Builder: Utilise Caching
  packages/amplication-container-builder/src/builder/ContainerBuilder.spec.ts
  packages/amplication-container-builder/src/builder/ContainerBuilder.ts
  packages/amplication-container-builder/src/cloud-build/CloudBuildProvider.spec.ts
  packages/amplication-container-builder/src/cloud-build/CloudBuildProvider.ts
  packages/amplication-container-builder/src/cloud-build/config.spec.ts
  packages/amplication-container-builder/src/cloud-build/config.ts
  packages/amplication-container-builder/src/docker/DockerProvider.spec.ts
  packages/amplication-container-builder/src/docker/DockerProvider.ts
  packages/amplication-container-builder/src/logging/index.ts
  packages/amplication-container-builder/src/logging/logging.ts
  packages/amplication-container-builder/src/types/BuildRequest.ts
  packages/amplication-container-builder/src/types/IProvider.ts
  packages/amplication-container-builder/src/types/index.ts
  packages/amplication-server/src/core/build/build.service.spec.ts
  packages/amplication-server/src/core/build/build.service.ts
Labels: type: enhancement

#1074 Remove docs
  docs/.gitbook/assets/0 (1).png
  docs/.gitbook/assets/0.png
  docs/.gitbook/assets/1.png
  docs/.gitbook/assets/2.png
  docs/.gitbook/assets/image (1) (1).png
  docs/.gitbook/assets/image (1).png
  docs/.gitbook/assets/image (10) (1).png
  docs/.gitbook/assets/image (10).png
  docs/.gitbook/assets/image (11).png
  docs/.gitbook/assets/image (12) (1).png
  docs/.gitbook/assets/image (12).png
  docs/.gitbook/assets/image (13) (1).png
  docs/.gitbook/assets/image (13).png
  docs/.gitbook/assets/image (14).png
  docs/.gitbook/assets/image (15) (1).png
  docs/.gitbook/assets/image (15).png
  docs/.gitbook/assets/image (16) (1).png
  docs/.gitbook/assets/image (16).png
  docs/.gitbook/assets/image (17) (1).png
  docs/.gitbook/assets/image (17).png
  docs/.gitbook/assets/image (2) (1).png
  docs/.gitbook/assets/image (2).png
  docs/.gitbook/assets/image (3).png
  docs/.gitbook/assets/image (4).png
  docs/.gitbook/assets/image (5) (1).png
  docs/.gitbook/assets/image (5).png
  docs/.gitbook/assets/image (6) (1).png
  docs/.gitbook/assets/image (6).png
  docs/.gitbook/assets/image (7) (1).png
  docs/.gitbook/assets/image (7).png
  docs/.gitbook/assets/image (8) (1).png
  docs/.gitbook/assets/image (8).png
  docs/.gitbook/assets/image (9) (1).png
  docs/.gitbook/assets/image (9).png
  docs/.gitbook/assets/image.png
  docs/.gitbook/assets/pic-1 (1).jpg
  docs/.gitbook/assets/pic-1.jpg
  docs/.gitbook/assets/pic-2.jpg
  docs/.gitbook/assets/pic-3.jpg
  docs/.gitbook/assets/pic-4.jpg
  docs/.gitbook/assets/pic-5.jpg
  docs/.gitbook/assets/pic0 (1).jpg
  docs/.gitbook/assets/pic0.jpg
  docs/.gitbook/assets/pic10.jpg
  docs/.gitbook/assets/pic11.jpg
  docs/.gitbook/assets/pic12.jpg
  docs/.gitbook/assets/pic13.jpg
  docs/.gitbook/assets/pic6.jpg
  docs/.gitbook/assets/pic7.jpg
  docs/.gitbook/assets/pic8 (1).jpg
  docs/.gitbook/assets/pic8 (2).jpg
  docs/.gitbook/assets/pic8 (3).jpg
  docs/.gitbook/assets/pic8.jpg
  docs/.gitbook/assets/pic9.jpg
  docs/README.md
  docs/SUMMARY.md
  docs/_config.yml
  docs/getting-started/first-app.md
  docs/getting-started/using-the-generated-app.md
Labels: type: docs

#1075 docs: system topology
  docs/system-topolgy.drawio
Labels: type: docs

#1077 Last commit status after commit
  packages/amplication-client/src/Application/ApplicationLayout.tsx
  packages/amplication-client/src/VersionControl/Commit.tsx
  packages/amplication-client/src/VersionControl/LastCommit.scss
  packages/amplication-client/src/VersionControl/LastCommit.tsx
  packages/amplication-client/src/VersionControl/PendingChangesContext.ts
Labels: type: enhancement

#1060 Admin UI - APIs page
  packages/amplication-data-service-generator/src/admin/static/src/Login.tsx
  packages/amplication-data-service-generator/src/admin/static/src/login.scss
  packages/amplication-data-service-generator/src/server/static/src/swagger/swagger.css
  packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
Labels: type: enhancement
