Repository amplication/amplication, pull requests merged in 2021-11, with the labels that each got.

#1854 feat(dsg): add static comments to generated base folder files
  packages/amplication-data-service-generator/src/server/resource/controller/create-controller.ts
  packages/amplication-data-service-generator/src/server/resource/dto/create-dto-module.spec.ts
  packages/amplication-data-service-generator/src/server/resource/dto/create-dto-module.ts
  packages/amplication-data-service-generator/src/server/resource/dto/create-enum-dto-module.ts
  packages/amplication-data-service-generator/src/server/resource/module/create-module.ts
  packages/amplication-data-service-generator/src/server/resource/resolver/create-resolver.ts
  packages/amplication-data-service-generator/src/server/resource/service/create-service.ts
  packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
  packages/amplication-data-service-generator/src/util/ast.ts
  packages/amplication-data-service-generator/src/version.ts
Labels: help wanted, hacktoberfest-accepted

#1881 Deps/versions anchor
  package-lock.json
  package.json
  packages/amplication-cli/package-lock.json
  packages/amplication-cli/package.json
  packages/amplication-client/package-lock.json
  packages/amplication-client/package.json
  packages/amplication-container-builder/package-lock.json
  packages/amplication-container-builder/package.json
  packages/amplication-data-service-generator/package-lock.json
  packages/amplication-data-service-generator/package.json
  packages/amplication-deployer/package-lock.json
  packages/amplication-deployer/package.json
  packages/amplication-design-system/package-lock.json
  packages/amplication-design-system/package.json
  packages/amplication-scheduler/package-lock.json
  packages/amplication-scheduler/package.json
Labels: needs review

#1986 Update README.md
  README.md
Labels: type: docs

#1987 Update server README.md
  packages/amplication-server/README.md
Labels: type: docs

#1797 enhancement(data-service-generator): graphql schema file
  packages/amplication-data-service-generator/src/server/app-module/create-app-module.ts
  packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
Labels: type: enhancement, priority: medium, type: feature request

#2012 Fix/locked entity error
  packages/amplication-server/README.md
  packages/amplication-server/src/core/entity/entity.service.ts
Labels: needs review
