Repository amplication/amplication, pull requests merged in 2021-09, with the labels that each got.

#1713 Auth provider
  .vscode/settings.json
  packages/amplication-data-service-generator/package-lock.json
  packages/amplication-data-service-generator/package.json
  packages/amplication-data-service-generator/src/admin/create-admin.ts
  packages/amplication-data-service-generator/src/create-data-service-impl.ts
  packages/amplication-data-service-generator/src/server/create-dotenv.template.env
  packages/amplication-data-service-generator/src/server/static/package.json
  packages/amplication-data-service-generator/src/server/static/src/auth/UserInfo.ts
  packages/amplication-data-service-generator/src/server/static/src/auth/auth.module.ts
  packages/amplication-data-service-generator/src/server/static/src/auth/jwt/guards/gqlJwtAuth.guard.ts
  packages/amplication-data-service-generator/src/server/static/src/auth/jwt/guards/jwt-auth.guard.ts
  packages/amplication-data-service-generator/src/server/static/src/auth/jwt/jwt.strategy.ts
  packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
Labels: type: enhancement

#1733 Changing from jwt default to basic
  packages/amplication-server/src/core/appSettings/appSettings.service.spec.ts
  packages/amplication-server/src/core/appSettings/appSettings.service.ts
  packages/amplication-server/src/core/appSettings/constants.ts
  packages/amplication-server/src/core/build/build.service.spec.ts
Labels: type: bug

#1731 Adding sass to admin ui package.json
  packages/amplication-data-service-generator/src/admin/static/package.json
Labels: type: bug

#1735 DSG - remove comment from .env
  packages/amplication-data-service-generator/src/server/create-dotenv.template.env
  packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
Labels: type: enhancement

#1737 fix(dsg): inject the services
  packages/amplication-data-service-generator/src/server/static/src/auth/auth.module.ts
  packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
Labels: type: bug

#1738 fix(dsg): add default title to Entity title component admin-ui
  packages/amplication-data-service-generator/src/admin/entity/entity-title-component/entity-title-component.template.tsx
  packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
Labels: type: bug

#1739 fix(dsg): removeing the pkg in the package lock flow
  packages/amplication-data-service-generator/src/admin/static/package-lock.json
  packages/amplication-data-service-generator/src/update-package-jsons.ts
Labels: type: bug, type: docs

#1743 Fix/env data and docker
  packages/amplication-data-service-generator/src/create-dotenv.template.env
  packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
Labels: type: docs, priority: high

#1745 fix(dsg): add the jwt secret to the docker file and test
  packages/amplication-data-service-generator/src/static/docker-compose.yml
  packages/amplication-data-service-generator/test/data-service-generator.e2e-spec.ts
Labels: type: bug, priority: critical

#1746 fix/(client): adding auth selection
  packages/amplication-client/src/Application/ApplicationAuthSettingForm.tsx
Labels: priority: high

#1747 refctor/(dsg): generate test data service
  packages/amplication-data-service-generator/scripts/generate-test-data-service.ts
  packages/amplication-data-service-generator/test/data-service-generator.e2e-spec.ts
Labels: type: refactor

#1748 fix(dsg): e2e test
  packages/amplication-data-service-generator/test/data-service-generator.e2e-spec.ts
Labels: type: bug
