Repository amplication/amplication, pull requests merged in 2021-05, with the labels that each got.

#1334 fix(client):entities canvas scale
  packages/amplication-client/src/Application/CreateAppFromExcel.scss
Labels: type: style

#1336 Chore/server pluralize
  packages/amplication-client/public/index.html
  packages/amplication-server/package.json
Labels: type: bug, type: chore

#1338 fix(client):update code for ajv validation
  packages/amplication-client/src/util/formikValidateJsonSchema.ts
Labels: type: bug

#1339 style(client):create app flow style
  packages/amplication-client/src/Application/CreateAppFromExcel.scss
  packages/amplication-client/src/Application/CreateAppFromExcel.tsx
  packages/amplication-client/src/style/mixin.scss
Labels: type: style

#1341 Rebuild without commit
  packages/amplication-client/src/VersionControl/Commit.scss
  packages/amplication-client/src/VersionControl/Commit.tsx
  packages/amplication-client/src/VersionControl/CommitValidation.scss
  packages/amplication-client/src/VersionControl/CommitValidation.tsx
  packages/amplication-client/src/VersionControl/LastCommit.scss
  packages/amplication-client/src/VersionControl/LastCommit.tsx
  packages/amplication-client/src/VersionControl/PendingChanges.tsx
  packages/amplication-server/src/core/app/app.service.ts
Labels: type: enhancement

#1344 feat(client):show last build status on app card
  packages/amplication-client/src/Application/ApplicationCard.tsx
  packages/amplication-client/src/Application/Applications.tsx
  packages/amplication-client/src/VersionControl/BuildStatusIcons.scss
  packages/amplication-client/src/VersionControl/BuildStatusIcons.tsx
  packages/amplication-client/src/VersionControl/CommitListItem.scss
  packages/amplication-client/src/VersionControl/CommitListItem.tsx
Labels: type: enhancement

#1347 Changing Readme.md Line 25
  README.md
Labels: type: docs

#1348 Fix/swagger types
  packages/amplication-data-service-generator/package.json
  packages/amplication-data-service-generator/src/server/resource/controller/controller.base.template.ts
  packages/amplication-data-service-generator/src/server/resource/controller/create-controller.ts
  packages/amplication-data-service-generator/src/server/resource/controller/to-many.template.ts
  packages/amplication-data-service-generator/src/server/static/package.json
  packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
  packages/amplication-data-service-generator/src/version.ts
Labels: type: bug, type: enhancement

#1351 DSG: add support for order by in APIs
  packages/amplication-data-service-generator/src/server/resource/create-dtos.ts
  packages/amplication-data-service-generator/src/server/resource/dto/create-dto-module.ts
  packages/amplication-data-service-generator/src/server/resource/dto/graphql/find-many/create-find-many-args.spec.ts
  packages/amplication-data-service-generator/src/server/resource/dto/graphql/find-many/create-find-many-args.ts
  packages/amplication-data-service-generator/src/server/resource/dto/graphql/find-many/find-many-args.template.ts
  packages/amplication-data-service-generator/src/server/resource/dto/graphql/order-by-input/order-by-input.spec.ts
  packages/amplication-data-service-generator/src/server/resource/dto/graphql/order-by-input/order-by-input.template.ts
  packages/amplication-data-service-generator/src/server/resource/dto/graphql/order-by-input/order-by-input.ts
  packages/amplication-data-service-generator/src/server/resource/dto/sort-order.util.ts
  packages/amplication-data-service-generator/src/server/static/src/util/SortOrder.ts
  packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
Labels: type: enhancement

#1352 DSG: searchable fields
  packages/amplication-data-service-generator/src/server/resource/dto/create-where-input.spec.ts
  packages/amplication-data-service-generator/src/server/resource/dto/create-where-input.ts
  packages/amplication-data-service-generator/src/server/resource/util/test-data.ts
  packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
  packages/amplication-data-service-generator/src/tests/entities.ts
Labels: type: enhancement

#1355 Remove order by properties for to-many relations
  packages/amplication-data-service-generator/src/server/resource/dto/graphql/order-by-input/order-by-input.ts
  packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
Labels: type: enhancement

#1356 fix: return empty array when parent resource does not exist
  packages/amplication-data-service-generator/src/server/resource/resolver/to-many.template.ts
  packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
Labels: type: bug

#1357 Add missing nullable for gql decorators
  packages/amplication-data-service-generator/src/server/resource/dto/create-field-class-property.ts
  packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
Labels: type: bug

#1363 Fix DSG e2e
  packages/amplication-data-service-generator/src/admin/create-admin.ts
  packages/amplication-data-service-generator/src/admin/entity/entity-create-component/create-entity-create-component.ts
  packages/amplication-data-service-generator/src/admin/entity/entity-edit-component/create-edit-entity-component.ts
  packages/amplication-data-service-generator/src/admin/entity/react-admin.util.ts
  packages/amplication-data-service-generator/src/admin/navigation/Navigation.template.tsx
  packages/amplication-data-service-generator/src/admin/navigation/create-navigation.ts
  packages/amplication-data-service-generator/src/static/Dockerfile
  packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
Labels: type: bug, type: test

#1365 docs(dsg): updated generated app readme
  packages/amplication-data-service-generator/src/static/README.md
Labels: type: docs

#1366 Fix/admin UI server url
  packages/amplication-data-service-generator/src/admin/static/src/data-provider/graphqlDataProvider.ts
  packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
Labels: type: bug

#1369 fix(client): handle invalid time
  packages/amplication-client/src/Application/ApplicationCard.tsx
Labels: type: bug

#1370 Style(client): Entities diagram
  packages/amplication-client/src/Application/CreateAppFromExcel.scss
  packages/amplication-client/src/Application/CreateAppFromExcelForm.tsx
  packages/amplication-client/src/EntitiesDiagram/EntitiesDiagram.scss
  packages/amplication-client/src/style/mixin.scss
Labels: type: style

#1371 Feat(client):remove entity from diagram
  packages/amplication-client/src/Application/CreateAppFromExcelForm.tsx
  packages/amplication-client/src/EntitiesDiagram/EntitiesDiagram.scss
  packages/amplication-client/src/EntitiesDiagram/EntitiesDiagram.tsx
  packages/amplication-client/src/EntitiesDiagram/EntitiesDiagramEntity.tsx
Labels: type: enhancement

#1372 Fix: entity permissions bug
  packages/amplication-cli/src/models.ts
  packages/amplication-client/src/Permissions/EntityPermissionField.tsx
  packages/amplication-client/src/Permissions/EntityPermissionFields.tsx
  packages/amplication-client/src/Permissions/PermissionsForm.tsx
  packages/amplication-client/src/VersionControl/PendingChangeDiff.tsx
  packages/amplication-client/src/models.ts
  packages/amplication-data-service-generator/src/models.ts
  packages/amplication-data-service-generator/src/server/create-grants.spec.ts
  packages/amplication-data-service-generator/src/server/create-grants.ts
  packages/amplication-data-service-generator/src/types.ts
  packages/amplication-data/src/models.ts
  packages/amplication-server/src/core/entity/entity.service.ts
  packages/amplication-server/src/models/EntityPermissionField.ts
  packages/amplication-server/src/schema.graphql
Labels: type: bug

#1375 fix(client):apps without build
  packages/amplication-client/src/Application/ApplicationCard.tsx
Labels: type: bug

#1378 chore(dsg):bump ra-data-graphql-amplication to 0.0.6
  packages/amplication-data-service-generator/package.json
  packages/amplication-data-service-generator/src/admin/static/package-lock.json
  packages/amplication-data-service-generator/src/admin/static/package.json
Labels: type: bug, type: chore

#1380 Fix(DSG) : Do not generate reference list view for many-to-many relationship
  packages/amplication-data-service-generator/src/admin/create-admin.ts
  packages/amplication-data-service-generator/src/admin/entity/create-entities-components.ts
  packages/amplication-data-service-generator/src/admin/entity/create-entity-components.ts
  packages/amplication-data-service-generator/src/admin/entity/entity-show-component/create-entity-show-component.ts
  packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
  packages/amplication-data-service-generator/src/tests/entities.ts
  packages/amplication-data-service-generator/src/version.ts
Labels: type: bug

#1382 Fix(client): Prevent duplicate and empty names in the entity diagram
  packages/amplication-client/src/Application/CreateAppFromExcel.tsx
Labels: type: bug

#1385 fix(server): make searchable true by default
  packages/amplication-server/src/core/entity/entity.service.ts
Labels: type: enhancement
