Repository amplication/amplication, pull requests merged in 2021-01, with the labels that each got.

#1086 Refactor entity service
  packages/amplication-server/src/core/entity/entity.service.spec.ts
  packages/amplication-server/src/core/entity/entity.service.ts
Labels: type: enhancement

#1088 DSG: Add start:debug and start:watch to server
  packages/amplication-data-service-generator/src/server/static/package.json
Labels: type: enhancement

#1082 Commits menu item
  packages/amplication-client/src/Application/ApplicationLayout.tsx
  packages/amplication-client/src/VersionControl/LastCommit.tsx
  packages/amplication-design-system/icons/amplicationicon.eot
  packages/amplication-design-system/icons/amplicationicon.svg
  packages/amplication-design-system/icons/amplicationicon.ttf
  packages/amplication-design-system/icons/amplicationicon.woff
Labels: type: enhancement

#1092 Style: app tiles
  packages/amplication-client/src/Application/ApplicationForm.tsx
  packages/amplication-client/src/Application/ApplicationHome.scss
Labels: type: style

#1093 Client: support links
  packages/amplication-client/src/Layout/MainLayout.tsx
  packages/amplication-client/src/Layout/SupportMenu.scss
  packages/amplication-client/src/Layout/SupportMenu.tsx
  packages/amplication-design-system/package.json
  packages/amplication-design-system/src/components/Popover/Popover.scss
  packages/amplication-design-system/src/components/Popover/Popover.stories.tsx
  packages/amplication-design-system/src/components/Popover/Popover.tsx
  packages/amplication-design-system/src/index.ts
Labels: type: enhancement

#1094 Pending changes popover
  packages/amplication-client/src/Application/ApplicationLayout.tsx
  packages/amplication-client/src/VersionControl/PendingChangesMenuItem.scss
  packages/amplication-client/src/VersionControl/PendingChangesMenuItem.tsx
Labels: type: enhancement

#1096 Update admin UI sign-in page
  packages/amplication-data-service-generator/src/admin/static/src/Login.tsx
  packages/amplication-data-service-generator/src/admin/static/src/login.scss
  packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
Labels: type: enhancement

#1102 Related field dialog
  packages/amplication-client/src/Entity/RelatedFieldDialog.scss
  packages/amplication-client/src/Entity/RelatedFieldDialog.tsx
Labels: type: enhancement

#1098 Container Builder: Document and add a prepare command for it
  README.md
  packages/amplication-container-builder/README.md
  packages/amplication-container-builder/package.json
Labels: type: docs

#1106 Update sample app
  packages/amplication-server/src/core/app/app.service.ts
  packages/amplication-server/src/core/app/sampleApp.ts
  packages/amplication-server/src/core/entity/entity.service.ts
Labels: type: enhancement

#1108 Fix menu item title bug
  packages/amplication-client/src/Layout/MenuItem.tsx
Labels: type: bug

#1110 Style: align the loader on the new app dialog
  packages/amplication-client/src/Application/NewApplication.scss
  packages/amplication-client/src/Application/NewApplication.tsx
Labels: type: style

#1111 Download Code Button and build summary
  packages/amplication-client/src/Application/ApplicationLayout.tsx
  packages/amplication-client/src/Application/EntitiesTile.tsx
  packages/amplication-client/src/VersionControl/BuildStepStatus.scss
  packages/amplication-client/src/VersionControl/BuildSteps.scss
  packages/amplication-client/src/VersionControl/BuildSteps.tsx
  packages/amplication-client/src/VersionControl/BuildStepsStatus.tsx
  packages/amplication-client/src/VersionControl/BuildSummary.scss
  packages/amplication-client/src/VersionControl/BuildSummary.tsx
  packages/amplication-client/src/VersionControl/CommitListItem.tsx
  packages/amplication-client/src/VersionControl/LastCommit.scss
  packages/amplication-client/src/VersionControl/LastCommit.tsx
  packages/amplication-client/src/VersionControl/PendingChanges.scss
  packages/amplication-client/src/VersionControl/PendingChanges.tsx
  packages/amplication-client/src/VersionControl/PendingChangesBar.scss
  packages/amplication-server/src/core/build/build.service.ts
Labels: type: enhancement

#1112 add amplitude events
  packages/amplication-client/src/Application/ApplicationCard.tsx
  packages/amplication-client/src/Application/ApplicationForm.tsx
  packages/amplication-client/src/Application/Applications.scss
  packages/amplication-client/src/Application/LastCommitTile.tsx
  packages/amplication-client/src/Components/ClickableId.tsx
  packages/amplication-client/src/VersionControl/BuildHeader.tsx
  packages/amplication-client/src/VersionControl/BuildPage.tsx
  packages/amplication-client/src/VersionControl/BuildSummary.tsx
  packages/amplication-client/src/VersionControl/CommitHeader.tsx
  packages/amplication-client/src/VersionControl/CommitListItem.tsx
  packages/amplication-client/src/VersionControl/CommitPage.scss
  packages/amplication-client/src/VersionControl/CommitPage.tsx
  packages/amplication-client/src/VersionControl/LastCommit.tsx
Labels: type: enhancement

#1115 chore: fix terraform variables
  terraform/envs/dev/terraform.tfvars
  terraform/envs/production/terraform.tfvars
Labels: type: chore

#1116 Sync with GitHub flow
  packages/amplication-client/src/Application/ApplicationHome.tsx
  packages/amplication-client/src/Application/ApplicationLayout.tsx
  packages/amplication-client/src/Application/SyncWithGithubTile.scss
  packages/amplication-client/src/Application/SyncWithGithubTile.tsx
  packages/amplication-client/src/Settings/AuthAppWithGithub.scss
  packages/amplication-client/src/Settings/AuthAppWithGithub.tsx
  packages/amplication-client/src/Settings/GithubRepoItem.scss
  packages/amplication-client/src/Settings/GithubRepoItem.tsx
  packages/amplication-client/src/Settings/GithubRepos.scss
  packages/amplication-client/src/Settings/GithubRepos.tsx
  packages/amplication-client/src/Settings/GithubSyncDetails.scss
  packages/amplication-client/src/Settings/GithubSyncDetails.tsx
  packages/amplication-client/src/VersionControl/BuildSteps.tsx
  packages/amplication-client/src/VersionControl/BuildSummary.scss
  packages/amplication-client/src/VersionControl/BuildSummary.tsx
  packages/amplication-client/src/VersionControl/LastCommit.scss
  packages/amplication-client/src/assets/images/sync-with-github-no-margin.svg
  packages/amplication-client/src/style/mixin.scss
  packages/amplication-design-system/icons/amplicationicon.eot
  packages/amplication-design-system/icons/amplicationicon.svg
  packages/amplication-design-system/icons/amplicationicon.ttf
  packages/amplication-design-system/icons/amplicationicon.woff
  packages/amplication-server/src/core/build/build.service.ts
Labels: type: enhancement

#1117 GitHub events
  packages/amplication-client/src/Application/ApplicationLayout.tsx
  packages/amplication-client/src/Settings/AuthAppWithGithub.scss
  packages/amplication-client/src/Settings/AuthAppWithGithub.tsx
  packages/amplication-client/src/Settings/AuthAppWithGithubCallback.tsx
  packages/amplication-client/src/Settings/GithubRepoItem.tsx
  packages/amplication-client/src/Settings/GithubSyncDetails.tsx
  packages/amplication-client/src/Settings/Settings.scss
  packages/amplication-client/src/VersionControl/Commit.tsx
  packages/amplication-client/src/VersionControl/PendingChange.scss
  packages/amplication-client/src/VersionControl/PendingChanges.scss
  packages/amplication-client/src/VersionControl/PendingChanges.tsx
  packages/amplication-client/src/style/mixin.scss
  packages/amplication-design-system/icons/amplicationicon.eot
  packages/amplication-design-system/icons/amplicationicon.svg
  packages/amplication-design-system/icons/amplicationicon.ttf
  packages/amplication-design-system/icons/amplicationicon.woff
Labels: type: enhancement

#1121 Fix GitHub Authentication
  packages/amplication-client/package-lock.json
  packages/amplication-client/package.json
  packages/amplication-client/src/User/GitHubLoginButton.tsx
  packages/amplication-client/src/User/Login.scss
  packages/amplication-client/src/User/Login.tsx
  packages/amplication-server/package-lock.json
  packages/amplication-server/package.json
  packages/amplication-server/src/core/auth/auth.controller.ts
  packages/amplication-server/src/core/auth/auth.module.ts
  packages/amplication-server/src/core/auth/auth.service.ts
  packages/amplication-server/src/core/auth/github.strategy.spec.ts
  packages/amplication-server/src/core/auth/github.strategy.ts
  packages/amplication-server/src/core/auth/githubStrategyConfig.service.ts
  packages/amplication-server/src/filters/exceptionFilters.module.ts
  packages/amplication-server/src/filters/github-auth-exception.filter.ts
Labels: type: bug

#1123 Style: welcome page
  packages/amplication-client/public/index.html
  packages/amplication-client/src/Layout/WelcomePage.scss
  packages/amplication-client/src/Layout/WelcomePage.tsx
  packages/amplication-client/src/User/Login.scss
  packages/amplication-client/src/User/Login.tsx
  packages/amplication-client/src/assets/images/discord-button.svg
  packages/amplication-client/src/style/css-variables.css
  packages/amplication-client/src/style/mixin.scss
Labels: type: style

#1129 update prod terraform
  terraform/envs/production/terraform.tfvars
  terraform/modules/env_baseline/main.tf
Labels: type: chore

#1133 Refresh pending changes on trigger instead of polling
  packages/amplication-client/src/Application/ApplicationLayout.tsx
  packages/amplication-client/src/VersionControl/BuildSummary.tsx
  packages/amplication-client/src/VersionControl/PendingChanges.tsx
Labels: type: perf

#1134 Disable publish for new apps
  packages/amplication-server/src/core/app/app.service.spec.ts
  packages/amplication-server/src/core/app/app.service.ts
  packages/amplication-server/src/core/build/build.service.ts
Labels: type: enhancement

#1135 Deployer machine type
  packages/amplication-container-builder/src/cloud-build/config.spec.ts
  packages/amplication-container-builder/src/cloud-build/config.ts
  packages/amplication-deployer/src/gcp/config.spec.ts
  packages/amplication-deployer/src/gcp/config.ts
Labels: type: chore

#1138 New deployment projects for generated apps
  terraform/envs/dev/main.tf
  terraform/envs/dev/terraform.tfvars
  terraform/envs/dev/variables.tf
  terraform/envs/production/main.tf
  terraform/envs/production/terraform.tfvars
  terraform/envs/production/variables.tf
  terraform/modules/env_baseline/main.tf
  terraform/modules/env_baseline/variables.tf
Labels: type: chore

#1141 Connect to GitHub on build summary
  packages/amplication-client/src/Settings/AuthAppWithGithub.scss
  packages/amplication-client/src/VersionControl/BuildSummary.scss
  packages/amplication-client/src/VersionControl/BuildSummary.tsx
Labels: type: enhancement

#1145 Adjust prod scale
  terraform/envs/production/terraform.tfvars
  terraform/modules/env_baseline/main.tf
Labels: type: chore

#1146 Design System: Use less packages in devDependencies
  packages/amplication-design-system/package-lock.json
  packages/amplication-design-system/package.json
Labels: type: chore

#1165 Repo list refresh and sort by last updated
  packages/amplication-client/src/Settings/GithubRepos.scss
  packages/amplication-client/src/Settings/GithubRepos.tsx
  packages/amplication-server/src/core/github/github.service.ts
Labels: type: enhancement

#1169 fix design system build command - npx rollup
  packages/amplication-design-system/package.json
Labels: type: chore

#1172 Remove Prisma from Gql context
  packages/amplication-server/src/app.module.ts
Labels: type: perf

#1175 Fix data type CreatedAt
  packages/amplication-data-service-generator/src/admin/entity/create-field-input.ts
Labels: type: bug

#1180 Fix Design-System CSS load order
  packages/amplication-client/src/assets/fonts/amplicationicon.eot
  packages/amplication-client/src/assets/fonts/amplicationicon.svg
  packages/amplication-client/src/assets/fonts/amplicationicon.ttf
  packages/amplication-client/src/assets/fonts/amplicationicon.woff
  packages/amplication-design-system/rollup.config.js
  packages/amplication-design-system/src/assets/app-banner/blue.svg
  packages/amplication-design-system/src/assets/app-banner/green.svg
  packages/amplication-design-system/src/assets/app-banner/pink.svg
  packages/amplication-design-system/src/assets/app-banner/red.svg
  packages/amplication-design-system/src/assets/app-banner/turquoise.svg
  packages/amplication-design-system/src/assets/app-banner/yellow.svg
  packages/amplication-design-system/src/assets/images/app-home-bg.svg
  packages/amplication-design-system/src/assets/images/commit-changes.svg
  packages/amplication-design-system/src/assets/images/commits.svg
  packages/amplication-design-system/src/assets/images/done.svg
  packages/amplication-design-system/src/assets/images/logs.svg
  packages/amplication-design-system/src/assets/images/mobile-message-white.svg
  packages/amplication-design-system/src/assets/images/mobile-message.svg
  packages/amplication-design-system/src/assets/images/my-apps-bg.svg
  packages/amplication-design-system/src/assets/images/new-app.svg
  packages/amplication-design-system/src/assets/images/no-changes.svg
  packages/amplication-design-system/src/assets/images/notice.svg
  packages/amplication-design-system/src/assets/images/publish.svg
  packages/amplication-design-system/src/assets/images/sandbox.svg
  packages/amplication-design-system/src/assets/images/signin-bg.svg
  packages/amplication-design-system/src/assets/images/signin-stripe.svg
  packages/amplication-design-system/src/assets/images/signin-top-stripe.svg
  packages/amplication-design-system/src/assets/images/tile-changes.svg
  packages/amplication-design-system/src/assets/images/tile-entities.svg
  packages/amplication-design-system/src/assets/images/tile-publish.svg
  packages/amplication-design-system/src/assets/images/tile-roles.svg
  packages/amplication-design-system/src/assets/images/warning.svg
  packages/amplication-design-system/src/assets/logo-amplication.svg
  packages/amplication-design-system/src/assets/logo-textual.svg
  packages/amplication-design-system/src/assets/logo.svg
Labels: type: bug

#1182 Fix pending changes count
  packages/amplication-client/src/Application/ApplicationLayout.tsx
  packages/amplication-client/src/Entity/EntityField.tsx
Labels: type: bug

#1183 Fix dark mode rejects
  packages/amplication-client/src/Components/UserBadge.tsx
  packages/amplication-client/src/Layout/DarkModeTheme.tsx
  packages/amplication-client/src/Layout/DarkModeToggle.scss
  packages/amplication-client/src/Layout/DarkModeToggle.tsx
  packages/amplication-client/src/Layout/MainLayout.scss
  packages/amplication-client/src/Layout/MainLayout.tsx
  packages/amplication-client/src/Layout/PageContent.scss
  packages/amplication-client/src/Layout/SupportMenu.scss
  packages/amplication-client/src/Layout/ThemeProvider.tsx
  packages/amplication-client/src/index.scss
  packages/amplication-client/src/style/css-variables.css
  packages/amplication-client/src/style/dark-css-variables.css
  packages/amplication-client/src/style/light-css-variables.css
  packages/amplication-client/src/style/mixin.scss
Labels: type: style

#1185 Add annotations to Credentials
  packages/amplication-data-service-generator/src/server/static/src/auth/Credentials.ts
  packages/amplication-data-service-generator/src/server/static/src/auth/LoginArgs.ts
  packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
Labels: type: enhancement

#1186 Update icons
  packages/amplication-design-system/icons/amplicationicon.eot
  packages/amplication-design-system/icons/amplicationicon.svg
  packages/amplication-design-system/icons/amplicationicon.ttf
  packages/amplication-design-system/icons/amplicationicon.woff
Labels: type: style

#1188 Application home tab URL
  packages/amplication-client/src/Application/ApplicationHome.tsx
Labels: type: bug

#1190 Role list - select first role
  packages/amplication-client/src/Roles/RoleList.tsx
  packages/amplication-client/src/Roles/RolesPage.tsx
  packages/amplication-client/src/index.scss
  packages/amplication-client/src/style/mixin.scss
  packages/amplication-design-system/src/components/SelectField/SelectField.scss
Labels: type: enhancement

#1191 style fixes
  packages/amplication-client/src/Application/Applications.scss
  packages/amplication-client/src/VersionControl/DiscardChanges.tsx
  packages/amplication-client/src/style/light-css-variables.css
  packages/amplication-design-system/src/components/Panel/Panel.scss
  packages/amplication-design-system/src/components/PanelCollapsible/PanelCollapsible.scss
  packages/amplication-design-system/src/components/SearchField/SearchField.scss
  packages/amplication-design-system/src/components/TextInput/TextInput.scss
  packages/amplication-design-system/src/components/TextInput/TextInput.tsx
  packages/amplication-design-system/src/style/css-variables.scss
Labels: type: style

#1192 Github signin button url
  packages/amplication-client/src/User/GitHubLoginButton.tsx
Labels: type: bug

#1194 datatype icons
  packages/amplication-client/src/Entity/constants.ts
  packages/amplication-client/src/Layout/DarkModeToggle.tsx
  packages/amplication-client/src/Layout/ThemeProvider.tsx
  packages/amplication-client/src/Layout/WelcomePage.scss
  packages/amplication-client/src/User/GitHubLoginButton.scss
  packages/amplication-client/src/User/GitHubLoginButton.tsx
  packages/amplication-client/src/style/dark-css-variables.css
  packages/amplication-client/src/style/light-css-variables.css
Labels: type: style
