Repository amplication/amplication, pull requests merged in 2021-10, with the labels that each got.

#1740 Client auth generation
  packages/amplication-data-service-generator/src/admin/app/App.template.tsx
  packages/amplication-data-service-generator/src/admin/app/create-app.ts
  packages/amplication-data-service-generator/src/admin/constants.ts
  packages/amplication-data-service-generator/src/admin/create-admin.ts
  packages/amplication-data-service-generator/src/admin/static/src/auth-provider/basic-auth.util.ts
  packages/amplication-data-service-generator/src/admin/static/src/auth-provider/ra-auth-http.ts
  packages/amplication-data-service-generator/src/admin/static/src/auth-provider/ra-auth-jwt.ts
  packages/amplication-data-service-generator/src/admin/static/src/auth.ts
  packages/amplication-data-service-generator/src/admin/static/src/constants.ts
  packages/amplication-data-service-generator/src/admin/static/src/data-provider/graphqlDataProvider.ts
  packages/amplication-data-service-generator/src/admin/static/src/types.ts
  packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
Labels: type: feature request

#1757 Submit from
  packages/amplication-client/src/User/Signup.tsx
Labels: type: enhancement

#1760 Refactor/switching to jwt
  packages/amplication-server/src/core/appSettings/constants.ts
Labels: priority: high, Epic, Hacktoberfest

#1756 Fix/dynamic swagger auth
  packages/amplication-data-service-generator/src/server/create-server.ts
  packages/amplication-data-service-generator/src/server/resource/controller/controller.base.template.ts
  packages/amplication-data-service-generator/src/server/resource/controller/controller.template.ts
  packages/amplication-data-service-generator/src/server/resource/controller/create-controller.ts
  packages/amplication-data-service-generator/src/server/resource/create-resource.ts
  packages/amplication-data-service-generator/src/server/swagger/create-swagger.ts
  packages/amplication-data-service-generator/src/server/swagger/swagger.template.ts
  packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
  packages/amplication-server/src/core/appSettings/constants.ts
Labels: type: bug, priority: medium

#1767 Start From Scratch to Start from scratch
  packages/amplication-client/src/Application/CreateAppFromExcel.tsx
Labels: type: bug, hacktoberfest-accepted

#1844 Add a tutorial on how to deploy the server on Digital Ocean
  tutorials/deploy-to-digital-ocean-2.md
Labels: hacktoberfest-accepted, under review

#1834 Fixes #1833 : fixing npm run command in dockerfile
  Dockerfile
  tutorials/deploy-to-digital-ocean-2.md
Labels: hacktoberfest-accepted, under review

#1840 Fix/jwt in restfull controller
  packages/amplication-data-service-generator/src/server/static/src/auth/auth.controller.ts
  packages/amplication-data-service-generator/src/server/static/src/auth/auth.resolver.ts
  packages/amplication-data-service-generator/src/server/static/src/auth/auth.service.spec.ts
  packages/amplication-data-service-generator/src/server/static/src/auth/auth.service.ts
  packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
Labels: needs review

#1851 Fix/dynamic auth service
  packages/amplication-data-service-generator/src/server/auth/createAuth.ts
  packages/amplication-data-service-generator/src/server/auth/token/createTokenSerivceTests.ts
  packages/amplication-data-service-generator/src/server/auth/token/createTokenService.ts
  packages/amplication-data-service-generator/src/server/auth/token/templates/basicToken.service.spec.ts
  packages/amplication-data-service-generator/src/server/auth/token/templates/basicToken.service.ts
  packages/amplication-data-service-generator/src/server/auth/token/templates/jwtToken.service.spec.ts
  packages/amplication-data-service-generator/src/server/auth/token/templates/jwtToken.service.ts
  packages/amplication-data-service-generator/src/server/create-server.ts
  packages/amplication-data-service-generator/src/server/static/src/auth/ITokenService.ts
  packages/amplication-data-service-generator/src/server/static/src/auth/auth.module.ts
  packages/amplication-data-service-generator/src/server/static/src/auth/auth.service.spec.ts
  packages/amplication-data-service-generator/src/server/static/src/auth/auth.service.ts
  packages/amplication-data-service-generator/src/server/static/src/auth/constants.ts
  packages/amplication-data-service-generator/src/server/static/src/auth/token.service.ts
  packages/amplication-data-service-generator/src/server/static/src/tests/auth/constants.ts
  packages/amplication-data-service-generator/src/server/static/src/tests/auth/token.service.ts
  packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
  packages/amplication-data-service-generator/src/version.ts
Labels: needs review
