Repository amplication/amplication, pull requests merged in 2022-10, with the labels that each got.

#3997 fix: pluralize text based on count
  packages/amplication-client/src/Entity/EntityFieldList.tsx
  packages/amplication-client/src/Entity/EntityList.tsx
  packages/amplication-client/src/Roles/RoleList.tsx
  packages/amplication-client/src/Topics/TopicList.tsx
  packages/amplication-client/src/Workspaces/MemberList.tsx
  packages/amplication-client/src/Workspaces/ResourceList.tsx
  packages/amplication-client/src/util/pluralize.ts
Labels: hacktoberfest-accepted

#4049 Advocacy: Twitter Thread and Linkedin Post talking about Amplication
  tutorials/social_post.md
Labels: hacktoberfest-accepted, hacktoberfest-two-pointer

#4047 Medium Post - Amplication
  tutorials/blog-post.md
Labels: hacktoberfest-accepted, hacktoberfest-two-pointer

#4051 Updated README.md
  README.md
Labels: hacktoberfest-accepted

#4058 Added Posts About Amplication
  tutorials/_social-post.md
Labels: hacktoberfest-accepted, hacktoberfest-two-pointer

#4067 Create social_post_ArnabC27.md
  tutorials/social_post_ArnabC27.md
Labels: hacktoberfest-accepted, hacktoberfest-two-pointer

#4066 Created Blog for Amplication
  tutorials/amplication-intro.md
Labels: hacktoberfest-accepted, hacktoberfest-two-pointer

#4052 Added description text for Base Directory
  packages/amplication-client/src/Resource/resourceSettings/DirectoriesProjectConfigurationSettingsForm.tsx
Labels: hacktoberfest-accepted

#4072 fix: correct grammar on resources, resource word
  packages/amplication-cli/README.md
  packages/amplication-cli/src/commands/entities/index.ts
  packages/amplication-cli/src/commands/resources/info.ts
  packages/amplication-cli/src/commands/resources/update.ts
  packages/amplication-server/src/core/build/utils/BuildFilesSaver/BuildFilesSaver.spec.ts
  packages/amplication-server/src/core/resource/resource.resolver.spec.ts
  packages/amplication-server/src/core/resource/resource.service.spec.ts
  packages/amplication-server/src/core/resourceRole/resourceRole.resolver.spec.ts
  packages/amplication-server/src/core/resourceRole/resourceRole.service.spec.ts
Labels: hacktoberfest-accepted

#4081 Created a blog post on Amplication
  tutorials/Amp_Introduction.md
Labels: hacktoberfest-accepted, hacktoberfest-two-pointer

#4089 Create blog_post_ArnabC27.md
  tutorials/Amp_Introduction.md
  tutorials/amplication-intro.md
  tutorials/blog_post_ArnabC27.md
  tutorials/social_post_ArnabC27.md
  tutorials/social_posts.md
Labels: hacktoberfest-accepted, hacktoberfest-two-pointer

#4091 chore(tutorials): add a youtube video link
  tutorials/youtube_video.md
Labels: hacktoberfest-accepted, hacktoberfest-two-pointer

#4092 Propose some Grammatical changes in the README
  README.md
Labels: hacktoberfest-accepted

#4086 fix: #3935 ResourceListItem Wrong Hover Effect
  packages/amplication-design-system/src/components/Panel/Panel.scss
Labels: hacktoberfest-accepted

#4088 fix(server): More information in PR error message.
  packages/amplication-data-service-generator/src/version.ts
  packages/amplication-server/src/core/queue/queue.service.ts
Labels: hacktoberfest-accepted

#4084 mv div ErrorMessage
  packages/amplication-client/src/Components/NameField.tsx
  packages/amplication-client/src/Components/TopicNameField.tsx
Labels: hacktoberfest-accepted

#4055 use amplication nest logger module in amplication-git-service
  packages/amplication-git-service/package-lock.json
  packages/amplication-git-service/package.json
  packages/amplication-git-service/src/git.module.ts
  packages/amplication-git-service/src/utils/constants.ts
Labels: hacktoberfest-accepted

#3921 fix: loading state while navigating between projects
  packages/amplication-client/src/Workspaces/ResourceList.tsx
Labels: Hacktoberfest

#4130 blog created on amplication
  tutorials/significance of amplication blog.md
Labels: hacktoberfest-accepted, hacktoberfest-two-pointer

#4132 Issue 3268: Added $schema property for all .prettierrc files
  .github/actions/get-services-hash/.prettierrc
  ee/packages/amplication-git-pull-service/.prettierrc
  ee/packages/amplication-git-push-webhook-service/.prettierrc
  packages/amplication-cli/.prettierrc
  packages/amplication-git-pull-request-service/.prettierrc
  packages/amplication-git-service/.prettierrc
  packages/amplication-prisma-db/.prettierrc
  packages/amplication-server/.prettierrc
Labels: hacktoberfest-accepted

#4087 Create social_media_post.md
  tutorials/social_media_post.md
Labels: hacktoberfest-accepted

#4143 Create social-post-toukir.md
  tutorials/social-post-toukir.md
Labels: hacktoberfest-accepted

#4170 Added my video
  tutorials/Amplication-Intro.md
Labels: hacktoberfest-accepted, hacktoberfest-two-pointer

#4169 Created My amplication blog
  tutorials/My_amplication_blog.md
Labels: hacktoberfest-accepted, hacktoberfest-two-pointer

#4167 Create two social posts about amplication
  tutorials/social_post_chirag8023.md
Labels: hacktoberfest-accepted

#4205 chore:add blog post
  tutorials/blog-post-2.md
Labels: hacktoberfest-accepted, hacktoberfest-two-pointer

#4179 docs: Update CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: hacktoberfest-accepted

#4228 added the link to my Amplication blog
  tutorials/Medium-blog-post.md
Labels: hacktoberfest-accepted, hacktoberfest-two-pointer

#4181 Social Media Advocacy
  tutorials/social_post_gokul.md
Labels: hacktoberfest-accepted

#4197 docs (Readme): Convert logo to clickable Link
  README.md
Labels: hacktoberfest-accepted

#4220 Create My_Amplication_Blog_post.md
  tutorials/My_Amplication_Blog_post.md
Labels: hacktoberfest-accepted, hacktoberfest-two-pointer

#4189 fix(data-service-gen): add slash in dockerfile
  packages/amplication-data-service-generator/src/server/static/Dockerfile
Labels: type: bug, hacktoberfest-accepted
