Repository amplication/amplication, pull requests merged in 2022-06, with the labels that each got.

#2833 fix(amplication-git-pull-service) add readme
  ee/packages/amplication-git-pull-service/README.md
Labels: @amplication/git-pull-service, 0.13.0

#2860 add prettierrc and run format
  ee/packages/amplication-git-pull-service/.prettierrc
  ee/packages/amplication-git-pull-service/README.md
  ee/packages/amplication-git-pull-service/scripts/clean.ts
  ee/packages/amplication-git-pull-service/scripts/customSeed.ts
  ee/packages/amplication-git-pull-service/scripts/seed.ts
  ee/packages/amplication-git-pull-service/src/__mocks__/core/gitPullEventService.ts
  ee/packages/amplication-git-pull-service/src/__mocks__/providers/gitClient/gitClientService.ts
  ee/packages/amplication-git-pull-service/src/__mocks__/providers/gitProvider/gitHubProviderService.ts
  ee/packages/amplication-git-pull-service/src/__mocks__/providers/gitProvider/gitProviderFactory.ts
  ee/packages/amplication-git-pull-service/src/__mocks__/providers/storage/storageService.ts
  ee/packages/amplication-git-pull-service/src/__mocks__/repositories/gitPullEventRepository.ts
  ee/packages/amplication-git-pull-service/src/__mocks__/stubs/eventRepository.stub.ts
  ee/packages/amplication-git-pull-service/src/__mocks__/stubs/gitClient.stub.ts
  ee/packages/amplication-git-pull-service/src/__mocks__/stubs/gitProvider.stub.ts
  ee/packages/amplication-git-pull-service/src/__tests__/core/gitPullEvent.service.spec.ts
  ee/packages/amplication-git-pull-service/src/__tests__/health/health.service.spec.ts
  ee/packages/amplication-git-pull-service/src/__tests__/providers/gitClient/gitClient.service.spec.ts
  ee/packages/amplication-git-pull-service/src/__tests__/providers/gitProvider/gitProvider.service.spec.ts
  ee/packages/amplication-git-pull-service/src/__tests__/providers/storage/storage.service.spec.ts
  ee/packages/amplication-git-pull-service/src/__tests__/repositories/gitPullEventRepository.spec.ts
  ee/packages/amplication-git-pull-service/src/app.module.ts
  ee/packages/amplication-git-pull-service/src/constants/errorMessages.ts
  ee/packages/amplication-git-pull-service/src/constants/loggerMessages.ts
  ee/packages/amplication-git-pull-service/src/constants/variables.ts
  ee/packages/amplication-git-pull-service/src/contracts/enums/gitFetchType.enum.ts
  ee/packages/amplication-git-pull-service/src/contracts/enums/gitProvider.enum.ts
  ee/packages/amplication-git-pull-service/src/contracts/enums/gitPullEventStatus.enum.ts
  ee/packages/amplication-git-pull-service/src/contracts/interfaces/eventData.ts
  ee/packages/amplication-git-pull-service/src/contracts/interfaces/gitClient.interface.ts
  ee/packages/amplication-git-pull-service/src/contracts/interfaces/gitHostProviderFactory.interface.ts
  ee/packages/amplication-git-pull-service/src/contracts/interfaces/gitPullEvent.interface.ts
  ee/packages/amplication-git-pull-service/src/contracts/interfaces/gitPullEventRepository.interface.ts
  ee/packages/amplication-git-pull-service/src/contracts/interfaces/pushEventMessage.ts
  ee/packages/amplication-git-pull-service/src/core/gitPullEvent/gitPullEvent.controller.ts
  ee/packages/amplication-git-pull-service/src/core/gitPullEvent/gitPullEvent.module.ts
  ee/packages/amplication-git-pull-service/src/core/gitPullEvent/gitPullEvent.service.ts
  ee/packages/amplication-git-pull-service/src/errors.ts
  ee/packages/amplication-git-pull-service/src/health/base/health.controller.base.ts
  ee/packages/amplication-git-pull-service/src/health/base/health.service.base.ts
  ee/packages/amplication-git-pull-service/src/health/health.controller.ts
  ee/packages/amplication-git-pull-service/src/health/health.module.ts
  ee/packages/amplication-git-pull-service/src/health/health.service.ts
  ee/packages/amplication-git-pull-service/src/main.ts
  ee/packages/amplication-git-pull-service/src/prisma.util.spec.ts
  ee/packages/amplication-git-pull-service/src/prisma.util.ts
  ee/packages/amplication-git-pull-service/src/providers/gitClient/gitClient.service.ts
  ee/packages/amplication-git-pull-service/src/providers/gitProvider/gitHostProvider.service.ts
  ee/packages/amplication-git-pull-service/src/providers/secrets/base/secretsManager.service.base.spec.ts
  ee/packages/amplication-git-pull-service/src/providers/secrets/base/secretsManager.service.base.ts
  ee/packages/amplication-git-pull-service/src/providers/secrets/secretsManager.module.ts
  ee/packages/amplication-git-pull-service/src/providers/secrets/secretsManager.service.ts
  ee/packages/amplication-git-pull-service/src/providers/storage/storage.service.ts
  ee/packages/amplication-git-pull-service/src/repositories/gitPullEvent.repository.ts
  ee/packages/amplication-git-pull-service/src/services/environmentVariables.ts
  ee/packages/amplication-git-pull-service/src/services/root-winston.module.ts
  ee/packages/amplication-git-pull-service/src/services/winstonConfig.service.ts
  ee/packages/amplication-git-pull-service/src/types.ts
  ee/packages/amplication-git-pull-service/src/utils/convertToNumber.ts
  ee/packages/amplication-git-pull-service/src/utils/gitHostProviderFactory/gitHostProviderFactory.ts
Labels: @amplication/git-pull-service, 0.13.0

#2817 FIX #2731 (issue Doc Adding System requirements ) changes added system requirement part in readme.md
  README.md
Labels: type: docs

#2906 fix #2902 onboarding npm run start:db failing
  packages/amplication-server/README.md
  script/setup.ts
Labels: setup, 0.13.1

#2927 @amplication/server: updated sendCreateGitPullRequest function in que…
  packages/amplication-server/src/core/build/build.service.ts
  packages/amplication-server/src/core/queue/queue.service.ts
Labels: 0.13.1

#2886 Fixed-Lodash-library-In-Server
  packages/amplication-container-builder/package.json
  packages/amplication-deployer/package.json
  packages/amplication-server/package.json
  packages/amplication-server/src/core/block/block.service.ts
  packages/amplication-server/src/core/entity/entity.service.ts
  packages/amplication-server/src/guards/gql-auth.guard.ts
  packages/amplication-server/src/interceptors/inject-context.interceptor.ts
  packages/amplication-server/src/services/diff.service.ts
  packages/amplication-server/test/gql-auth-mock.ts
Labels: 0.13.2

#2806 bugfix: Imported lodash as a single library(dsg)
  packages/amplication-data-service-generator/package.json
  packages/amplication-data-service-generator/src/server/prisma/create-prisma-schema.ts
  packages/amplication-data-service-generator/src/server/resource/create-resource.ts
  packages/amplication-data-service-generator/src/tests/server/resource/dto/create-input-dto/jsonfield-tests.spec.ts
  packages/amplication-data-service-generator/src/tests/server/resource/dto/entity-dto.spec.ts
  packages/amplication-data-service-generator/src/util/ast.ts
  packages/amplication-data-service-generator/src/util/module.ts
  packages/amplication-data-service-generator/test/data-service-generator.e2e-spec.ts
Labels: @amplication/data-service-generator, 0.13.2

#2956 added boolean value hard coded false to not trigger email notification
  packages/amplication-server/src/core/deployment/deployment.service.ts
  packages/amplication-server/src/core/mail/mail.service.ts
Labels: @amplication/server, 0.13.2

#2950 fix(server): Dynamically generated date in tests
  packages/amplication-server/src/core/workspace/workspace.resolver.spec.ts
Labels: 0.13.2

#2941 feat: add health check endpoint in amplication-server
  packages/amplication-server/src/core/core.module.ts
  packages/amplication-server/src/core/health/health.controller.ts
  packages/amplication-server/src/core/health/health.e2e-spec.ts
  packages/amplication-server/src/core/health/health.module.ts
Labels: 0.13.2

#2900 2895 code generation remove ampconfig.json
  packages/amplication-cli/src/models.ts
  packages/amplication-client/src/VersionControl/Commit.tsx
  packages/amplication-client/src/VersionControl/CommitValidation.tsx
  packages/amplication-client/src/models.ts
  packages/amplication-data-service-generator/src/create-root-modules.ts
  packages/amplication-data-service-generator/src/models.ts
  packages/amplication-data-service-generator/src/types.ts
  packages/amplication-data-service-generator/src/util/module.ts
  packages/amplication-data-service-generator/src/version.ts
  packages/amplication-data/src/models.ts
  packages/amplication-git-pull-request-service/src/models.ts
  packages/amplication-server/src/core/app/app.resolver.ts
  packages/amplication-server/src/core/app/app.service.ts
  packages/amplication-server/src/schema.graphql
Labels: 0.13.2

#2988 amit env
  .github/workflows/cd-aws.yml
  helm/charts/amplication/values-amit.yaml
  packages/amplication-server/src/core/app/app.resolver.ts
  packages/amplication-server/src/core/app/app.service.ts
Labels: 0.13.2

#3003 fix prisma migration project hierarchy
  packages/amplication-prisma-db/prisma/migrations/20220630105056_new_project_hierarchy_nullable_project/migration.sql
  packages/amplication-prisma-db/prisma/schema.prisma
Labels: @amplication/prisma-db, 0.13.2
