Repository amplication/amplication, pull requests merged in 2022-05, with the labels that each got.

#2657 feat(dsg) move use guards to the top of the controller
  packages/amplication-data-service-generator/src/server/resource/controller/controller.base.template.ts
  packages/amplication-data-service-generator/src/server/resource/controller/to-many.template.ts
  packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
Labels: 0.12.7

#2663 feat(dsg) changed the functions names on controller base template and…
  packages/amplication-data-service-generator/src/server/resource/controller/controller.base.template.ts
  packages/amplication-data-service-generator/src/server/resource/controller/create-controller.ts
Labels: 0.12.7

#2656 feat(dsg) move nest morgan interceptor to be global and make it reque…
  packages/amplication-data-service-generator/src/server/app-module/app.module.template.ts
  packages/amplication-data-service-generator/src/server/resource/controller/controller.base.template.ts
  packages/amplication-data-service-generator/src/server/resource/controller/to-many.template.ts
  packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
Labels: 0.12.7

#2661 feat(dsg) move swagger api auth from class to every method
  packages/amplication-data-service-generator/src/server/resource/controller/controller.base.template.ts
  packages/amplication-data-service-generator/src/server/resource/controller/to-many.template.ts
  packages/amplication-data-service-generator/src/server/static/src/decorators/public.decorator.ts
  packages/amplication-data-service-generator/src/server/static/src/main.ts
  packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
Labels: 0.12.7

#2644 Release/0.12.6
  lerna.json
  packages/amplication-cli/package-lock.json
  packages/amplication-cli/package.json
  packages/amplication-client/package-lock.json
  packages/amplication-client/package.json
  packages/amplication-client/src/Application/ApplicationDatabaseSettingsForms.scss
  packages/amplication-client/src/Application/ApplicationDatabaseSettingsForms.tsx
  packages/amplication-client/src/VersionControl/CommitList.scss
  packages/amplication-container-builder/package-lock.json
  packages/amplication-container-builder/package.json
  packages/amplication-data-service-generator/package-lock.json
  packages/amplication-data-service-generator/package.json
  packages/amplication-data-service-generator/src/admin/static/package-lock.json
  packages/amplication-data-service-generator/src/admin/static/package.json
  packages/amplication-data-service-generator/src/server/resource/controller/controller.base.template.ts
  packages/amplication-data-service-generator/src/server/resource/controller/create-controller.ts
  packages/amplication-data-service-generator/src/server/resource/controller/to-many.template.ts
  packages/amplication-data-service-generator/src/server/resource/resolver/resolver.base.template.ts
  packages/amplication-data-service-generator/src/server/resource/resolver/to-many.template.ts
  packages/amplication-data-service-generator/src/server/resource/resolver/to-one.template.ts
  packages/amplication-data-service-generator/src/server/static/package-lock.json
  packages/amplication-data-service-generator/src/server/static/package.json
  packages/amplication-data-service-generator/src/server/static/src/interceptors/aclFilterResponse.interceptor.ts
  packages/amplication-data-service-generator/src/server/static/src/interceptors/aclValidateRequest.interceptor.ts
  packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
  packages/amplication-data-service-generator/src/version.ts
  packages/amplication-data/package-lock.json
  packages/amplication-data/package.json
  packages/amplication-deployer/package-lock.json
  packages/amplication-deployer/package.json
  packages/amplication-design-system/package-lock.json
  packages/amplication-design-system/package.json
  packages/amplication-git-service/package-lock.json
  packages/amplication-git-service/package.json
  packages/amplication-scheduler/package-lock.json
  packages/amplication-scheduler/package.json
  packages/amplication-server/package-lock.json
  packages/amplication-server/package.json
Labels: 0.12.6

#2651 Add font smoothing to improve readability
  packages/amplication-client/src/index.scss
Labels: @amplication/client, 0.12.7

#2671 fix(dsg): passport
  packages/amplication-data-service-generator/package-lock.json
  packages/amplication-data-service-generator/package.json
Labels: @amplication/data-service-generator, 0.12.7

#2673 fix(main): add .server-id to gitignore
  .gitignore
Labels: 0.12.7

#2689 feat(dsg) add logic for handling public queries and mutation for reso…
  packages/amplication-data-service-generator/src/server/resource/resolver/create-resolver.ts
  packages/amplication-data-service-generator/src/server/resource/resolver/resolver.base.template.ts
  packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
Labels: 0.12.7

#2682 Feat/2006 public routes
  packages/amplication-client/src/Permissions/EntityPermissionAction.scss
  packages/amplication-client/src/Permissions/EntityPermissionAction.tsx
  packages/amplication-client/src/models.ts
  packages/amplication-data-service-generator/src/models.ts
  packages/amplication-data-service-generator/src/server/auth/guards/defaultAuth.guard.template.ts
  packages/amplication-data-service-generator/src/server/create-grants.ts
  packages/amplication-data-service-generator/src/server/resource/controller/create-controller.ts
  packages/amplication-data-service-generator/src/server/resource/resolver/create-resolver.ts
  packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
  packages/amplication-data-service-generator/src/tests/entities.ts
  packages/amplication-data-service-generator/src/util/ast.ts
  packages/amplication-data-service-generator/src/util/create-decorators-imports.ts
  packages/amplication-data-service-generator/src/util/create-public-decorator.ts
  packages/amplication-data-service-generator/src/util/nestjs-code-generation.ts
  packages/amplication-data-service-generator/src/util/set-endpoint-permission.ts
  packages/amplication-design-system/src/components/MultiStateToggle/MultiStateToggle.scss
  packages/amplication-design-system/src/style/css-variables.scss
  packages/amplication-server/prisma/migrations/20220501150832_add_public_to_enum_entity_permission_type/migration.sql
  packages/amplication-server/prisma/schema.prisma
  packages/amplication-server/src/enums/EnumEntityPermissionType.ts
  packages/amplication-server/src/schema.graphql
Labels: 0.12.7

#2631 Feat/common kafka
  .gitignore
  packages/amplication-git-pull-service/Dockerfile
  packages/amplication-git-pull-service/package.json
  packages/amplication-git-pull-service/src/main.ts
  packages/amplication-git-push-webhook-service/Dockerfile
  packages/amplication-git-service/package-lock.json
  packages/amplication-git-service/package.json
  packages/amplication-git-service/tsconfig.json
  packages/amplication-kafka/package-lock.json
  packages/amplication-kafka/package.json
  packages/amplication-kafka/src/createNestjsKafkaConfig.spec.ts
  packages/amplication-kafka/src/createNestjsKafkaConfig.ts
  packages/amplication-kafka/src/index.ts
  packages/amplication-kafka/src/utils/constants.ts
  packages/amplication-kafka/src/utils/environmentVariables.spec.ts
  packages/amplication-kafka/src/utils/environmentVariables.ts
  packages/amplication-kafka/src/utils/index.ts
  packages/amplication-kafka/src/utils/kafkaEnv.ts
  packages/amplication-kafka/tsconfig.json
  packages/amplication-pull-request/package-lock.json
  packages/amplication-pull-request/package.json
  packages/amplication-pull-request/src/main.ts
  packages/amplication-server/Dockerfile
  packages/amplication-server/package.json
  packages/amplication-server/src/core/queue/queue.module.ts
Labels: 0.13.0

#2698 Fix/2695 import interceptors dynamically
  packages/amplication-data-service-generator/src/server/resource/controller/controller.base.template.ts
  packages/amplication-data-service-generator/src/server/resource/controller/create-controller.ts
  packages/amplication-data-service-generator/src/server/resource/resolver/create-resolver.ts
  packages/amplication-data-service-generator/src/server/resource/resolver/resolver.base.template.ts
  packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
  packages/amplication-data-service-generator/src/util/create-decorators-imports.ts
  packages/amplication-data-service-generator/src/util/identifiers-imports.ts
  packages/amplication-data-service-generator/src/util/set-endpoint-permission.ts
Labels: generated server, 0.12.7

#2696 fix: remove unused imports
  packages/amplication-data-service-generator/src/server/resource/controller/controller.base.template.ts
  packages/amplication-data-service-generator/src/server/resource/resolver/resolver.base.template.ts
  packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
Labels: generated server, 0.12.7

#2704 fix(server): update const
  packages/amplication-server/src/core/deployment/deployment.service.ts
Labels: @amplication/server, 0.12.7

#2690 feat: add cli loader in setup script
  package-lock.json
  package.json
  packages/amplication-data-service-generator/src/version.ts
  script/setup.ts
Labels: 0.12.8

#2748 fix(client): lodash imports
  packages/amplication-client/package-lock.json
  packages/amplication-client/package.json
  packages/amplication-client/src/Entity/EntityFieldForm.tsx
  packages/amplication-client/src/Permissions/permissionUtil.ts
  packages/amplication-client/src/Roles/RoleForm.tsx
  packages/amplication-client/src/util/formikAutoSave.tsx
Labels: @amplication/client

#2699 Fix - navigating to the correct entity from a related field
  packages/amplication-client/src/Entity/EntityRelationFieldsChart.tsx
Labels: @amplication/client, 0.12.8

#2786 fix(dsg): npm i get-port --save-exact
  packages/amplication-data-service-generator/package-lock.json
Labels: 0.12.8
