Repository amplication/amplication, pull requests merged in 2022-03, with the labels that each got.

#2389 Fix/2366 sorting order
  packages/amplication-data-service-generator/src/server/resource/dto/graphql/find-many/create-find-many-args.spec.ts
  packages/amplication-data-service-generator/src/server/resource/dto/graphql/find-many/find-many-args.template.ts
  packages/amplication-data-service-generator/src/server/resource/dto/graphql/order-by-input/order-by-input.spec.ts
  packages/amplication-data-service-generator/src/server/resource/dto/graphql/order-by-input/order-by-input.template.ts
  packages/amplication-data-service-generator/src/server/resource/dto/sort-order.util.ts
  packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
Labels: @amplication/data-service-generator, 0.12.1

#2418 fix(client): cancel organization reset
  packages/amplication-client/src/Application/git/AuthAppWithGit.tsx
  packages/amplication-client/src/Application/git/GitActions/RepositoryActions/RepositoryActions.scss
  packages/amplication-client/src/Application/git/GitActions/RepositoryActions/RepositoryActions.tsx
Labels: @amplication/client

#2393 [2386] - create new repository popup shows error message on first keystroke
  packages/amplication-client/src/Application/git/dialogs/GitCreateRepo/GitCreateRepo.tsx
Labels: status: approved, 0.12.1

#2424 [2401] - When role is applied to a field it jumps to the top of the list.
  packages/amplication-client/src/Permissions/EntityPermissionField.tsx
Labels: 0.12.2

#2452 Deps/ra data graphql amplication
  packages/amplication-data-service-generator/package-lock.json
  packages/amplication-data-service-generator/package.json
  packages/amplication-data-service-generator/src/admin/static/package-lock.json
  packages/amplication-data-service-generator/src/admin/static/package.json
Labels: @amplication/data-service-generator

#2456 fix(dsg) admin ui added m2m relation
  packages/amplication-data-service-generator/src/admin/entity/create-field-input.ts
  packages/amplication-data-service-generator/src/admin/entity/entity-create-component/create-entity-create-component.ts
  packages/amplication-data-service-generator/src/admin/entity/entity-edit-component/create-edit-entity-component.ts
  packages/amplication-data-service-generator/src/admin/entity/react-admin.util.ts
  packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
  packages/amplication-data-service-generator/src/version.ts
Labels: 0.12.2

#2483 Update ra-data-graphql-amplication test's
  packages/amplication-data-service-generator/package-lock.json
  packages/amplication-data-service-generator/package.json
  packages/amplication-data-service-generator/src/admin/static/package-lock.json
  packages/amplication-data-service-generator/src/admin/static/package.json
Labels: @amplication/data-service-generator, 0.12.2

#2443 fix(client): Change colors
  packages/amplication-client/src/Layout/SupportMenu.scss
Labels: type: bug, type: style, 0.12.2

#2448 fix: width fix when error shown in git create repo
  packages/amplication-client/src/Application/git/dialogs/GitCreateRepo/GitCreateRepo.scss
Labels: 0.12.2

#2453 Bug 2019 - Disabled input has an hover state behaving
  packages/amplication-design-system/src/components/TextInput/TextInput.scss
Labels: type: bug, type: style, 0.12.2

#2455 fix: change rgb color codes to css variables
  packages/amplication-client/src/Application/ApplicationAuthSettingForm.scss
  packages/amplication-client/src/Application/git/GitActions/ExistingConnectionsMenu.scss
  packages/amplication-client/src/Application/git/dialogs/GitCreateRepo/GitCreateRepo.scss
  packages/amplication-design-system/src/components/Toggle/Toggle.scss
  packages/amplication-design-system/src/style/css-variables.scss
Labels: 0.12.2

#2494 feat(dsg admin ui saved changes on m2m relation
  packages/amplication-data-service-generator/src/admin/entity/create-field-input.ts
  packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
Labels: 0.12.2

#2506 hotfix(dsg) react admin ui fix source attribute
  packages/amplication-data-service-generator/src/admin/entity/create-field-input.ts
  packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
  packages/amplication-data-service-generator/src/version.ts
Labels: 0.12.3

#2522 fix(data-service-gen): update outdated/deprecated code
  packages/amplication-data-service-generator/src/admin/static/src/Login.tsx
  packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
Labels: 0.12.3

#2517 fix(client): api token text container
  packages/amplication-client/src/Settings/ApiTokenListItem.scss
Labels: 0.12.3

#2527 Issue #2467
  CONTRIBUTING.md
Labels: 0.12.3

#2504 Fix/2423 info popup state always open
  packages/amplication-client/src/Layout/MainLayout.tsx
Labels: 0.12.3

#2528 deps(dsg): update ra
  packages/amplication-data-service-generator/package-lock.json
  packages/amplication-data-service-generator/package.json
  packages/amplication-data-service-generator/src/admin/static/package-lock.json
  packages/amplication-data-service-generator/src/admin/static/package.json
  packages/amplication-server/src/util/jsonHelper.ts
  packages/amplication-server/src/util/sendServerLoadEvent.ts
Labels: @amplication/data-service-generator, 0.12.3

#2454 fix: add icon position in button
  packages/amplication-data-service-generator/src/version.ts
  packages/amplication-design-system/src/components/Button/Button.tsx
  packages/amplication-design-system/src/index.ts
Labels: 0.12.3
