Repository amplication/amplication, pull requests merged in 2022-11, with the labels that each got.

#4271 fix(client): commitListItem className
  packages/amplication-client/src/Entity/EntityFieldLinkList.tsx
  packages/amplication-client/src/Layout/InnerTabLink.scss
  packages/amplication-client/src/VersionControl/CommitListItem.tsx
  packages/amplication-data-service-generator/README.md
  packages/amplication-design-system/src/components/CircularProgress/CircularProgress.scss
Labels: hacktoberfest-accepted

#4229 Added my Blog Post
  tutorials/Amplication-Intro-Blog.md
Labels: hacktoberfest-accepted, hacktoberfest-two-pointer

#4281 swaggersetup fix
  packages/amplication-data-service-generator/src/server/swagger/swagger.template.ts
Labels: hacktoberfest-accepted

#3928 Use Event Pattern instead of Message Pattern in Create Pull Request Flow
  packages/amplication-git-pull-request-service/.env
  packages/amplication-git-pull-request-service/src/core/pull-request/dto/sendPullRequestResponse.ts
  packages/amplication-git-pull-request-service/src/core/pull-request/pull-request.controller.ts
  packages/amplication-git-pull-request-service/src/core/pull-request/pull-request.module.ts
  packages/amplication-git-pull-request-service/src/core/pull-request/pull-request.service.ts
  packages/amplication-git-pull-request-service/src/core/pull-request/queue.service.ts
  packages/amplication-server/.env
  packages/amplication-server/src/constants.ts
  packages/amplication-server/src/core/build/build.controller.ts
  packages/amplication-server/src/core/build/build.service.ts
  packages/amplication-server/src/core/build/dto/sendPullRequestResponse.ts
  packages/amplication-server/src/core/queue/queue.service.ts
Labels: PR: do not merge

#4276 fix(client): project configuration UI
  packages/amplication-client/src/Resource/ResourceHome.scss
Labels: hacktoberfest-accepted

#4353 Feat/4044 delete topic
  packages/amplication-cli/src/models.ts
  packages/amplication-client/src/ServiceConnections/ServiceConnectionsList.tsx
  packages/amplication-client/src/ServiceConnections/ServiceConnectionsPage.tsx
  packages/amplication-client/src/ServiceConnections/hooks/useServiceConnection.ts
  packages/amplication-client/src/ServiceConnections/topics/TopicsList.tsx
  packages/amplication-client/src/ServiceConnections/topics/queries/topicsQueries.ts
  packages/amplication-client/src/Topics/DeleteTopic.tsx
  packages/amplication-client/src/Topics/Topic.scss
  packages/amplication-client/src/Topics/Topic.tsx
  packages/amplication-client/src/Topics/hooks/useTopic.tsx
  packages/amplication-client/src/models.ts
  packages/amplication-code-gen-types/src/models.ts
  packages/amplication-data-service-generator/src/models.ts
  packages/amplication-git-pull-request-service/src/models.ts
  packages/amplication-server/src/core/block/block.service.ts
  packages/amplication-server/src/core/block/blockType.resolver.ts
  packages/amplication-server/src/core/block/blockType.service.spec.ts
  packages/amplication-server/src/core/block/blockType.service.ts
  packages/amplication-server/src/core/block/dto/DeleteBlockArgs.ts
  packages/amplication-server/src/core/connectorRestApi/connectorRestApi.resolver.ts
  packages/amplication-server/src/core/connectorRestApi/connectorRestApi.service.ts
  packages/amplication-server/src/core/connectorRestApiCall/connectorRestApiCall.resolver.ts
  packages/amplication-server/src/core/connectorRestApiCall/connectorRestApiCall.service.ts
  packages/amplication-server/src/core/entityPage/dto/DeleteEntityPageArgs.ts
  packages/amplication-server/src/core/entityPage/entityPage.resolver.ts
  packages/amplication-server/src/core/entityPage/entityPage.service.ts
  packages/amplication-server/src/core/pluginInstallation/dto/DeletePluginOrderArgs.ts
  packages/amplication-server/src/core/pluginInstallation/pluginInstallation.resolver.ts
  packages/amplication-server/src/core/pluginInstallation/pluginInstallation.service.ts
  packages/amplication-server/src/core/pluginInstallation/pluginOrder.service.ts
  packages/amplication-server/src/core/serviceTopics/dto/DeleteServiceTopicsArgs.ts
  packages/amplication-server/src/core/serviceTopics/serviceTopics.resolver.ts
  packages/amplication-server/src/core/serviceTopics/serviceTopics.service.ts
  packages/amplication-server/src/core/topic/dto/DeleteTopicArgs.ts
  packages/amplication-server/src/core/topic/topic.module.ts
  packages/amplication-server/src/core/topic/topic.resolver.ts
  packages/amplication-server/src/core/topic/topic.service.ts
  packages/amplication-server/src/models/IBlock.ts
  packages/amplication-server/src/schema.graphql
Labels: PR: do not merge

#4219 fix: Update pending changes not refreshing on new project
  packages/amplication-client/src/Workspaces/hooks/usePendingChanges.ts
Labels: hacktoberfest-accepted

#4282 fix(client): add message broker empty state
  packages/amplication-client/src/Components/SvgThemeImage.tsx
  packages/amplication-client/src/ServiceConnections/ServiceConnectionsList.tsx
  packages/amplication-client/src/ServiceConnections/ServiceConnectionsPage.tsx
  packages/amplication-client/src/ServiceConnections/topics/TopicsList.tsx
  packages/amplication-client/src/assets/images/mono/message-broker-empty-state-dark.svg
  packages/amplication-client/src/style/dark-css-variables.css
Labels: hacktoberfest-accepted

#4280 fix(client): update last commit text breaks by changing status display settings
  packages/amplication-client/src/VersionControl/LastCommit.scss
Labels: hacktoberfest-accepted

#4383 refactor(client): rename variable to match real use
  helm/charts/amplication/values-common.yaml
  helm/charts/amplication/values-mor.yaml
  helm/charts/services/amplication-client/values.yaml
  packages/amplication-client/.env
  packages/amplication-client/src/User/Login.tsx
  packages/amplication-client/src/env.ts
Labels: type: refactor

#4364 chore: add health check on postgresql
  docker-compose.dev.yml
Labels: type: chore

#3536 fix(server) : fix unique property violation
  packages/amplication-data-service-generator/src/server/resource/test/controller.spec.template.ts
  packages/amplication-data-service-generator/src/server/static/src/filters/HttpExceptions.filter.ts
  packages/amplication-data-service-generator/src/server/static/src/main.ts
  packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service-custom-path.spec.ts.snap
  packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service-numeric-user-id.spec.ts.snap
  packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service-with-kafka.spec.ts.snap
  packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service-without-graphql.spec.ts.snap
  packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service-without-restApi.spec.ts.snap
  packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
Labels: PR: do not merge

#3553 Refactor `amplication-server` to use `@amplication/nest-logger-module`
  packages/amplication-nest-logger-module/src/index.ts
  packages/amplication-server/src/app.module.ts
  packages/amplication-server/src/constants.ts
  packages/amplication-server/src/core/account/account.resolver.spec.ts
  packages/amplication-server/src/core/action/action.service.spec.ts
  packages/amplication-server/src/core/action/action.service.ts
  packages/amplication-server/src/core/auth/auth.controller.ts
  packages/amplication-server/src/core/auth/auth.resolver.spec.ts
  packages/amplication-server/src/core/build/build.controller.ts
  packages/amplication-server/src/core/build/build.resolver.spec.ts
  packages/amplication-server/src/core/build/build.service.ts
  packages/amplication-server/src/core/build/utils/BuildFilesSaver/BuildFilesSaver.ts
  packages/amplication-server/src/core/commit/commit.resolver.spec.ts
  packages/amplication-server/src/core/entity/entity.resolver.spec.ts
  packages/amplication-server/src/core/project/project.resolver.spec.ts
  packages/amplication-server/src/core/resource/resource.resolver.spec.ts
  packages/amplication-server/src/core/resourceRole/resourceRole.resolver.spec.ts
  packages/amplication-server/src/core/workspace/workspace.resolver.spec.ts
  packages/amplication-server/src/filters/GqlResolverExceptions.filter.spec.ts
  packages/amplication-server/src/filters/GqlResolverExceptions.filter.ts
  packages/amplication-server/src/filters/exceptionFilters.module.ts
  packages/amplication-server/src/filters/github-auth-exception.filter.ts
  packages/amplication-server/src/services/root-winston.module.ts
  packages/amplication-server/src/services/winstonConfig.service.spec.ts
  packages/amplication-server/src/services/winstonConfig.service.ts
Labels: type: chore

#4482 Open to community
  CONTRIBUTING.md
Labels: type: docs
