Repository amplication/amplication, pull requests merged in 2022-01, with the labels that each got.

#2098 #2091 remove from @amplication/data-service-generator @amplication/de…
  .github/workflows/generated-app-tests.yml
Labels: needs review

#2189 bug fix: tooltip cut on small screen
  packages/amplication-design-system/src/components/UserAndTime/UserAndTime.tsx
Labels: under review, 0.11.2

#2203 bug(apmlication-client): no error message rename to an existing app name
  .gitignore
  packages/amplication-client/src/Application/ApplicationForm.tsx
Labels: 0.11.2

#1871 Feat(DSG): auto-gen message
  packages/amplication-data-service-generator/src/server/resource/controller/create-controller.ts
  packages/amplication-data-service-generator/src/server/resource/dto/create-dto-module.spec.ts
  packages/amplication-data-service-generator/src/server/resource/dto/create-dto-module.ts
  packages/amplication-data-service-generator/src/server/resource/dto/create-enum-dto-module.ts
  packages/amplication-data-service-generator/src/server/resource/module/create-module.ts
  packages/amplication-data-service-generator/src/server/resource/resolver/create-resolver.ts
  packages/amplication-data-service-generator/src/server/resource/service/create-service.ts
  packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
  packages/amplication-data-service-generator/src/util/ast.ts
Labels: needs review, 0.11.2

#2195 feat(server): Add @amplication/server Dockerfile
  packages/amplication-server/Dockerfile
Labels: @amplication/server, 0.11.2, WIP

#2213 Style/update icons
  packages/amplication-client/src/Application/ApplicationForm.scss
  packages/amplication-client/src/Application/git/AuthAppWithGithub.scss
  packages/amplication-client/src/Application/git/AuthAppWithGithub.tsx
  packages/amplication-client/src/Components/ErrorMessage.tsx
  packages/amplication-client/src/Layout/InnerTabLink.tsx
  packages/amplication-client/src/Layout/NavigationTabs.tsx
  packages/amplication-client/src/User/Login.tsx
  packages/amplication-client/src/VersionControl/BuildStatusIcons.scss
  packages/amplication-client/src/VersionControl/BuildStepStatus.scss
  packages/amplication-client/src/VersionControl/BuildSummary.tsx
  packages/amplication-client/src/VersionControl/CommitValidation.tsx
  packages/amplication-client/src/VersionControl/PendingChanges.scss
  packages/amplication-client/src/VersionControl/PendingChangesMenuItem.tsx
  packages/amplication-client/src/style/dark-css-variables.css
  packages/amplication-client/src/style/light-css-variables.css
  packages/amplication-design-system/icons/amplicationicon.eot
  packages/amplication-design-system/icons/amplicationicon.svg
  packages/amplication-design-system/icons/amplicationicon.ttf
  packages/amplication-design-system/icons/amplicationicon.woff
  packages/amplication-design-system/icons/amplicationicon.woff2
  packages/amplication-design-system/src/components/Button/Button.scss
  packages/amplication-design-system/src/components/Button/Button.tsx
  packages/amplication-design-system/src/components/Dialog/Dialog.scss
  packages/amplication-design-system/src/components/Dialog/Dialog.tsx
  packages/amplication-design-system/src/components/Icon/Icon.tsx
  packages/amplication-design-system/src/style/css-variables.scss
  packages/amplication-design-system/src/style/icon.scss
Labels: type: style, status: approved, 0.11.2

#2221 Feat/2220 update issues template
  .github/ISSUE_TEMPLATE/bug.yaml
  .github/ISSUE_TEMPLATE/documentation.yaml
  .github/ISSUE_TEMPLATE/feature.yml
Labels: 0.11.2

#2218 feat/1862 add a PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 0.11.2

#2101 Fix conflicting flags
  packages/amplication-cli/src/flags/field-flag.ts
Labels: type: bug, @amplication/cli, 0.11.2
