Repository amplication/amplication, pull requests merged in 2022-07, with the labels that each got.

#3013 Bug/0.14.0-handleSubmit-settings
  packages/amplication-client/src/Application/ApplicationAuthSettingForm.tsx
  packages/amplication-client/src/Application/ApplicationDatabaseSettingsForms.tsx
  packages/amplication-client/src/Application/appSettings/DirectoriesSettingsForm.tsx
  packages/amplication-client/src/Application/appSettings/GenerationSettingsForm.tsx
  packages/amplication-client/src/Application/appSettings/formSchema.ts
  packages/amplication-client/src/Application/useSettingsHook.ts
Labels: type: bug, @amplication/client, 0.14.0

#3022 Fix linter error in CI process
  packages/amplication-server/package-lock.json
Labels: 0.14.0

#3015 3014 client page title
  packages/amplication-client/package-lock.json
  packages/amplication-client/package.json
  packages/amplication-client/src/Application/ApplicationHome.tsx
  packages/amplication-client/src/Application/appSettings/AppSettingsPage.tsx
  packages/amplication-client/src/Application/code-view/CodeViewPage.tsx
  packages/amplication-client/src/Application/git/SyncWithGithubPage.tsx
  packages/amplication-client/src/Entity/Entity.tsx
  packages/amplication-client/src/Entity/EntityList.tsx
  packages/amplication-client/src/Entity/RelatedFieldsMigrationFix.tsx
  packages/amplication-client/src/Layout/PageContent.tsx
  packages/amplication-client/src/Layout/RouteWithAnalytics.tsx
  packages/amplication-client/src/Roles/RolesPage.tsx
  packages/amplication-client/src/VersionControl/BuildPage.tsx
  packages/amplication-client/src/VersionControl/CommitList.tsx
  packages/amplication-client/src/VersionControl/CommitPage.tsx
  packages/amplication-client/src/VersionControl/Commits.tsx
  packages/amplication-client/src/VersionControl/PendingChangesPage.tsx
Labels: type: feature request, @amplication/client, 0.14.0

#3017 Feat/3016 generated app => update readme files for the server and the admin-ui
  packages/amplication-data-service-generator/src/admin/static/README.md
  packages/amplication-data-service-generator/src/admin/static/package.json
  packages/amplication-data-service-generator/src/server/static/README.md
  packages/amplication-data-service-generator/src/server/static/docker-compose.yml
  packages/amplication-data-service-generator/src/server/static/package-lock.json.bak
  packages/amplication-data-service-generator/src/server/static/package.json
  packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service-custom-path.spec.ts.snap
  packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service-without-graphql.spec.ts.snap
  packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service-without-restApi.spec.ts.snap
  packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
Labels: 0.14.0

#3025 Fix/3024 renaming app caused error
  packages/amplication-server/src/core/app/app.service.ts
Labels: @amplication/server, 0.14.0

#3030 Fix a bug where generated markdown files were ignored
  .dockerignore
Labels: 0.14.1

#3032 Fix/3031 Adjust UI in Base Directories settings
  packages/amplication-client/src/Application/appSettings/DirectoriesSettingsForm.tsx
  packages/amplication-client/src/Application/appSettings/GenerationSettingsForm.scss
  packages/amplication-data-service-generator/src/version.ts
Labels: 0.14.0

#2751 Fix conflicting shortcut (CMD+SHIFT+P) [Firefox]
  packages/amplication-client/src/CommandPalette/CommandPalette.tsx
  packages/amplication-client/src/Layout/MainLayout.tsx
Labels: @amplication/client, 0.15.0

#3056 2989 app routes change structure
  packages/amplication-client/src/App.tsx
  packages/amplication-client/src/Resource/CreateResourceFromExcel.tsx
  packages/amplication-client/src/Workspaces/WorkspaceLayout.tsx
  packages/amplication-client/src/appRoutes.tsx
  packages/amplication-client/src/routesUtil.tsx
  packages/amplication-data-service-generator/src/version.ts
Labels: @amplication/client, 0.15.0

#3064 refactor(server & client): rename resourceType
  packages/amplication-cli/src/api/resources-create.ts
  packages/amplication-cli/src/models.ts
  packages/amplication-client/src/Resource/CreateResourceFromExcel.tsx
  packages/amplication-client/src/Resource/constants.ts
  packages/amplication-client/src/models.ts
  packages/amplication-data-service-generator/src/models.ts
  packages/amplication-data/src/models.ts
  packages/amplication-git-pull-request-service/src/models.ts
  packages/amplication-prisma-db/prisma/migrations/20220707120437_from_app_to_resource/migration.sql
  packages/amplication-prisma-db/prisma/schema.prisma
  packages/amplication-server/src/core/block/block.service.spec.ts
  packages/amplication-server/src/core/build/build.service.spec.ts
  packages/amplication-server/src/core/git/__tests__/git.service.spec.ts
  packages/amplication-server/src/core/resource/__mocks__/Resource.mock.ts
  packages/amplication-server/src/core/resource/dto/ResourceCreateInput.ts
  packages/amplication-server/src/core/resource/resource.resolver.spec.ts
  packages/amplication-server/src/core/resource/resource.service.spec.ts
  packages/amplication-server/src/core/resource/sampleResource.ts
  packages/amplication-server/src/core/workspace/workspace.resolver.spec.ts
  packages/amplication-server/src/models/Resource.ts
  packages/amplication-server/src/schema.graphql
Labels: 0.15.0

#3009 Feat/2782 project crud
  packages/amplication-cli/src/models.ts
  packages/amplication-client/package-lock.json
  packages/amplication-client/src/models.ts
  packages/amplication-data-service-generator/src/models.ts
  packages/amplication-data/src/models.ts
  packages/amplication-git-pull-request-service/src/models.ts
  packages/amplication-server/src/core/core.module.ts
  packages/amplication-server/src/core/project/dto/ProjectCreateArgs.ts
  packages/amplication-server/src/core/project/dto/ProjectCreateInput.ts
  packages/amplication-server/src/core/project/dto/ProjectFindManyArgs.ts
  packages/amplication-server/src/core/project/dto/ProjectOrderByInput.ts
  packages/amplication-server/src/core/project/dto/ProjectWhereInput.ts
  packages/amplication-server/src/core/project/project.module.ts
  packages/amplication-server/src/core/project/project.resolver.ts
  packages/amplication-server/src/core/project/project.service.ts
  packages/amplication-server/src/core/resource/dto/ResourceCreateInput.ts
  packages/amplication-server/src/models/Project.ts
  packages/amplication-server/src/models/index.ts
  packages/amplication-server/src/schema.graphql
Labels: @amplication/server, 0.15.0

#3093 Fix/3091 prisma resource type
  packages/amplication-prisma-db/prisma/migrations/20220707120437_from_app_to_resource/migration.sql
  packages/amplication-prisma-db/prisma/migrations/20220712125221_resource_type/migration.sql
Labels: 0.15.0

#3099 Change postgresql service type to LoadBlancer
  helm/charts/amplication/values-alex.yaml
  helm/charts/amplication/values-amit.yaml
  helm/charts/amplication/values-common.yaml
  helm/charts/amplication/values-mor.yaml
  helm/charts/amplication/values-shimi.yaml
Labels: 0.14.2

#3100 FIX: Deploying none existing image tag
  .github/workflows/cd-aws.yml
  .github/workflows/scripts/deploy-image.sh
Labels: 0.14.2

#3085 Feat/3077 disconnect resource from workspace
  packages/amplication-cli/src/api/resources-create.ts
  packages/amplication-cli/src/commands/resources/create.ts
  packages/amplication-cli/src/models.ts
  packages/amplication-client/src/models.ts
  packages/amplication-data-service-generator/src/models.ts
  packages/amplication-data/src/models.ts
  packages/amplication-git-pull-request-service/src/models.ts
  packages/amplication-prisma-db/prisma/migrations/20220712143206_disconnect_resource_from_workspace/migration.sql
  packages/amplication-prisma-db/prisma/schema.prisma
  packages/amplication-server/src/core/build/build.service.ts
  packages/amplication-server/src/core/permissions/permissions.service.spec.ts
  packages/amplication-server/src/core/permissions/permissions.service.ts
  packages/amplication-server/src/core/resource/dto/ResourceCreateInput.ts
  packages/amplication-server/src/core/resource/dto/ResourceWhereInput.ts
  packages/amplication-server/src/core/resource/resource.resolver.spec.ts
  packages/amplication-server/src/core/resource/resource.resolver.ts
  packages/amplication-server/src/core/resource/resource.service.spec.ts
  packages/amplication-server/src/core/resource/resource.service.ts
  packages/amplication-server/src/core/resource/sampleResource.spec.ts
  packages/amplication-server/src/core/resource/sampleResource.ts
  packages/amplication-server/src/core/workspace/workspace.module.ts
  packages/amplication-server/src/core/workspace/workspace.resolver.spec.ts
  packages/amplication-server/src/core/workspace/workspace.resolver.ts
  packages/amplication-server/src/enums/AuthorizableResourceParameter.ts
  packages/amplication-server/src/models/Project.ts
  packages/amplication-server/src/models/Resource.ts
  packages/amplication-server/src/models/Workspace.ts
  packages/amplication-server/src/schema.graphql
Labels: @amplication/server, @amplication/prisma-db, 0.15.0

#3142 Upgrade `@prisma/client` and `nestjs-prisma` in `@amplication/data-service-generator`
  packages/amplication-data-service-generator/package-lock.json
  packages/amplication-data-service-generator/package.json
  packages/amplication-data-service-generator/src/server/static/package-lock.json
  packages/amplication-data-service-generator/src/server/static/package.json
Labels: 0.14.3

#3145 Upgrade `@prisma/client` and `nestjs-prisma` in `@amplication/git-pull-request-service`
  ee/packages/amplication-git-pull-service/package-lock.json
  ee/packages/amplication-git-pull-service/package.json
  packages/amplication-prisma-db/package-lock.json
  packages/amplication-prisma-db/package.json
Labels: 0.14.3

#2444 Fix/2259 update apollo server express package
  packages/amplication-data-service-generator/package-lock.json
  packages/amplication-data-service-generator/package.json
  packages/amplication-data-service-generator/src/admin/static/package-lock.json
  packages/amplication-data-service-generator/src/admin/static/package.json
  packages/amplication-data-service-generator/src/server/static/package-lock.json
  packages/amplication-data-service-generator/src/server/static/package.json
  packages/amplication-data-service-generator/src/util/ast.ts
  packages/amplication-server/package-lock.json
  packages/amplication-server/package.json
Labels: 0.14.3

#3163 fix(sql): migration fix
  packages/amplication-prisma-db/prisma/migrations/20220712143206_disconnect_resource_from_workspace/migration.sql
Labels: 0.15.0

#3180 Fix Prisma one to one relation
  packages/amplication-data-service-generator/src/server/prisma/create-prisma-schema.spec.ts
  packages/amplication-data-service-generator/src/server/prisma/create-prisma-schema.ts
  packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service-custom-path.spec.ts.snap
  packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service-without-graphql.spec.ts.snap
  packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service-without-restApi.spec.ts.snap
  packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
  packages/amplication-data-service-generator/src/tests/entities.ts
  packages/amplication-data-service-generator/src/version.ts
Labels: 0.14.5

#3193 Use repo's default base branch for Amplication PRs
  packages/amplication-data-service-generator/src/version.ts
  packages/amplication-git-pull-request-service/src/core/pull-request/dto/GitCommit.ts
  packages/amplication-git-pull-request-service/src/core/pull-request/pull-request.service.ts
  packages/amplication-git-service/src/services/git.service.ts
  packages/amplication-server/src/core/build/build.service.ts
  packages/amplication-server/src/core/build/dto/GitCommit.ts
Labels: 0.14.5

#3196 fix(dsg): update lock and @nestjs/passport
  packages/amplication-data-service-generator/src/server/static/package-lock.json
  packages/amplication-data-service-generator/src/server/static/package.json
Labels: 0.14.5

#3194 Use minor minor version pinning in Dockerfiles instead of patch
  ee/packages/amplication-git-pull-service/Dockerfile
  ee/packages/amplication-git-push-webhook-service/Dockerfile
  packages/amplication-client/Dockerfile
  packages/amplication-data-service-generator/Dockerfile
  packages/amplication-data-service-generator/src/admin/static/Dockerfile
  packages/amplication-data-service-generator/src/server/static/Dockerfile
  packages/amplication-git-pull-request-service/Dockerfile
  packages/amplication-scheduler/Dockerfile
  packages/amplication-server/Dockerfile
  packages/amplication-storage-gateway/Dockerfile
Labels: 0.14.6

#3124 Project Screen
  packages/amplication-client/src/Layout/InnerTabLink.scss
  packages/amplication-client/src/Layout/InnerTabLink.tsx
  packages/amplication-client/src/Project/AddNewProject.scss
  packages/amplication-client/src/Project/AddNewProject.tsx
  packages/amplication-client/src/Project/NewProject.scss
  packages/amplication-client/src/Project/NewProject.tsx
  packages/amplication-client/src/Project/ProjectList.scss
  packages/amplication-client/src/Project/ProjectList.tsx
  packages/amplication-client/src/Project/ProjectListItem.tsx
  packages/amplication-client/src/Project/ProjectSideBar.scss
  packages/amplication-client/src/Project/ProjectSideBar.tsx
  packages/amplication-client/src/Project/WorkspaceSettingsNavigation.scss
  packages/amplication-client/src/Project/WorkspaceSettingsNavigation.tsx
  packages/amplication-client/src/Workspaces/WorkspaceLayout.tsx
  packages/amplication-client/src/Workspaces/WorkspaceSelector.scss
  packages/amplication-client/src/Workspaces/WorkspaceSelector.tsx
  packages/amplication-client/src/style/mixin.scss
  packages/amplication-design-system/icons/amplicationicon.svg
Labels: @amplication/client, 0.15.0

#3103 Separating Code Generation: Step 1
  .vscode/launch.json
  packages/amplication-server/.env
  packages/amplication-server/README.md
  packages/amplication-server/src/core/build/build.module.ts
  packages/amplication-server/src/core/build/build.service.spec.ts
  packages/amplication-server/src/core/build/build.service.ts
  packages/amplication-server/src/core/build/buildContextStorage.service.ts
  packages/amplication-server/src/core/build/dto/AppInfo.ts
  packages/amplication-server/src/core/build/dto/BuildContext.ts
  packages/amplication-server/src/core/build/dto/BuildContextData.ts
  packages/amplication-server/src/core/build/dto/FileLocation.ts
  packages/amplication-server/src/core/build/dto/GenerateResource.ts
  packages/amplication-server/src/core/build/dto/StorageTypeEnum.ts
  packages/amplication-server/src/core/fsStorage/fsStorage.module.ts
  packages/amplication-server/src/core/fsStorage/fsStorage.service.ts
  packages/amplication-server/src/core/queue/queue.service.ts
  packages/amplication-server/src/services/storage.service.ts
Labels: feature: dsg-separation

#3207 DSG version alignment
  packages/amplication-data-service-generator/package-lock.json
  packages/amplication-data-service-generator/package.json
  packages/amplication-data-service-generator/src/version.ts
Labels: @amplication/data-service-generator, 0.14.6

#3199 CLI - fix `AMP_SERVER_URL` value
  packages/amplication-cli/src/properties.ts
Labels: 0.14.6

#3202 Uninstall `@prisma/client` from dev-dependencies and install it as a dependency
  packages/amplication-data-service-generator/src/server/static/package-lock.json
  packages/amplication-data-service-generator/src/server/static/package.json
Labels: 0.14.6

#3133 Adding project resource and project block
  packages/amplication-cli/src/models.ts
  packages/amplication-client/src/models.ts
  packages/amplication-code-gen-types/src/models.ts
  packages/amplication-data-service-generator/src/models.ts
  packages/amplication-git-pull-request-service/src/models.ts
  packages/amplication-prisma-db/prisma/migrations/20220711090906_project_resource_block/migration.sql
  packages/amplication-prisma-db/prisma/schema.prisma
  packages/amplication-server/src/core/block/block.service.spec.ts
  packages/amplication-server/src/core/block/block.service.ts
  packages/amplication-server/src/core/block/blockType.service.spec.ts
  packages/amplication-server/src/core/block/blockType.service.ts
  packages/amplication-server/src/core/block/types.ts
  packages/amplication-server/src/core/entityPage/entityPage.service.spec.ts
  packages/amplication-server/src/core/project/project.module.ts
  packages/amplication-server/src/core/project/project.resolver.ts
  packages/amplication-server/src/core/project/project.service.ts
  packages/amplication-server/src/core/projectConfigurationSettings/dto/ProjectConfigurationSettings.ts
  packages/amplication-server/src/core/projectConfigurationSettings/dto/ProjectConfigurationSettingsUpdateInput.ts
  packages/amplication-server/src/core/projectConfigurationSettings/dto/UpdateProjectConfigurationSettingsArgs.ts
  packages/amplication-server/src/core/projectConfigurationSettings/errors/ProjectConfigurationSettingsExistError.ts
  packages/amplication-server/src/core/projectConfigurationSettings/projectConfigurationSettings.module.ts
  packages/amplication-server/src/core/projectConfigurationSettings/projectConfigurationSettings.resolver.ts
  packages/amplication-server/src/core/projectConfigurationSettings/projectConfigurationSettings.service.ts
  packages/amplication-server/src/core/resource/constants.ts
  packages/amplication-server/src/core/resource/errors/ProjectConfigurationExistError.ts
  packages/amplication-server/src/core/resource/resource.module.ts
  packages/amplication-server/src/core/resource/resource.service.spec.ts
  packages/amplication-server/src/core/resource/resource.service.ts
  packages/amplication-server/src/core/serviceSettings/constants.ts
  packages/amplication-server/src/core/serviceSettings/serviceSettings.service.ts
  packages/amplication-server/src/enums/EnumBlockType.ts
  packages/amplication-server/src/schema.graphql
Labels: 0.15.0

#3228 fix(client): hubspot identify
  packages/amplication-client/src/util/analytics.ts
Labels: 0.14.7

#3231 Update `nestjs/passport` dependency on `server` and `storage-gateway`
  packages/amplication-server/package-lock.json
  packages/amplication-server/package.json
  packages/amplication-storage-gateway/package-lock.json
  packages/amplication-storage-gateway/package.json
Labels: 0.14.7

#3240 Update `getResources` query
  packages/amplication-client/src/Project/ProjectPage.tsx
  packages/amplication-client/src/Workspaces/ResourceList.tsx
  packages/amplication-client/src/Workspaces/WorkspaceLayout.tsx
  packages/amplication-client/src/Workspaces/hooks/useResources.ts
  packages/amplication-client/src/Workspaces/queries/resourcesQuery.ts
  packages/amplication-client/src/context/appContext.tsx
Labels: 0.15.0

#3206 Implementing project page layout
  packages/amplication-client/src/Layout/InnerTabLink.scss
  packages/amplication-client/src/Project/AddNewProject.tsx
  packages/amplication-client/src/Project/NewProject.tsx
  packages/amplication-client/src/Project/ProjectList.scss
  packages/amplication-client/src/Project/ProjectList.tsx
  packages/amplication-client/src/Project/ProjectListItem.tsx
  packages/amplication-client/src/Project/ProjectPage.scss
  packages/amplication-client/src/Project/ProjectPage.tsx
  packages/amplication-client/src/Project/ProjectSideBar.scss
  packages/amplication-client/src/Project/ProjectSideBar.tsx
  packages/amplication-client/src/Project/WorkspaceSettingsNavigation.scss
  packages/amplication-client/src/Project/WorkspaceSettingsNavigation.tsx
  packages/amplication-client/src/Resource/create-resource/CreateServiceWizard.tsx
  packages/amplication-client/src/Workspaces/NewWorkspace.tsx
  packages/amplication-client/src/Workspaces/ResourceList.tsx
  packages/amplication-client/src/Workspaces/WorkspaceForm.tsx
  packages/amplication-client/src/Workspaces/WorkspaceLayout.tsx
  packages/amplication-client/src/Workspaces/WorkspaceSelector.scss
  packages/amplication-client/src/Workspaces/WorkspaceSelector.tsx
  packages/amplication-client/src/Workspaces/WorkspaceSelectorList.tsx
  packages/amplication-client/src/Workspaces/WorkspaceSelectorListItem.tsx
  packages/amplication-client/src/Workspaces/hooks/useCurrentWorkspace.ts
  packages/amplication-client/src/Workspaces/hooks/useProjectSelector.ts
  packages/amplication-client/src/Workspaces/hooks/useResources.ts
  packages/amplication-client/src/Workspaces/hooks/useWorkspaceSelector.ts
  packages/amplication-client/src/Workspaces/hooks/workspace.ts
  packages/amplication-client/src/Workspaces/queries/projectQueries.ts
  packages/amplication-client/src/Workspaces/queries/resourcesQueries.ts
  packages/amplication-client/src/Workspaces/queries/workspaceQueries.ts
  packages/amplication-client/src/context/appContext.tsx
  packages/amplication-client/src/routes/appRoutes.tsx
  packages/amplication-client/src/style/mixin.scss
  packages/amplication-client/src/style/parameters.scss
  packages/amplication-server/src/core/project/project.resolver.ts
Labels: 0.15.0

#3248 Add AppMatchRoute and AppRouteProps type
  packages/amplication-client/src/Project/ProjectPage.tsx
  packages/amplication-client/src/Resource/create-resource/CreateServiceWizard.tsx
  packages/amplication-client/src/Workspaces/WorkspaceLayout.tsx
  packages/amplication-client/src/routes/routesUtil.tsx
Labels: 0.15.0

#3254 Update routes for workspace members and workspace settings
  packages/amplication-client/src/Project/WorkspaceSettingsNavigation.tsx
  packages/amplication-client/src/Workspaces/hooks/useProjectSelector.ts
Labels: 0.15.0

#3257 Fix signin route
  packages/amplication-client/src/Workspaces/hooks/useCurrentWorkspace.ts
Labels: 0.15.0
