Repository amplication/amplication, pull requests merged in 2022-09, with the labels that each got.

#3707 Route to create service wizard after signup with GitHub
  packages/amplication-client/src/User/Login.tsx
  packages/amplication-client/src/User/Signup.tsx
  packages/amplication-client/src/Workspaces/hooks/useProjectSelector.ts
  packages/amplication-server/package-lock.json
  packages/amplication-server/package.json
  packages/amplication-server/src/core/auth/auth.controller.ts
  packages/amplication-server/src/core/auth/auth.module.ts
  packages/amplication-server/src/core/auth/github.guard.ts
  packages/amplication-server/src/core/auth/github.strategy.spec.ts
  packages/amplication-server/src/core/auth/github.strategy.ts
  packages/amplication-server/src/core/auth/types.ts
Labels: 0.15.3

#3720 add Amplication plugin support
  packages/amplication-code-gen-types/package.json
  packages/amplication-code-gen-types/src/code-gen-types.ts
  packages/amplication-code-gen-types/src/eventsParams.ts
  packages/amplication-code-gen-types/src/index.ts
  packages/amplication-code-gen-types/src/plugin-generic.ts
  packages/amplication-code-gen-types/src/plugins-types.ts
  packages/amplication-data-service-generator/src/admin/create-admin.ts
  packages/amplication-data-service-generator/src/admin/create-dto-modules.ts
  packages/amplication-data-service-generator/src/admin/create-dto-name-to-path.ts
  packages/amplication-data-service-generator/src/admin/entity/create-entities-components.ts
  packages/amplication-data-service-generator/src/admin/entity/create-entity-components.ts
  packages/amplication-data-service-generator/src/admin/entity/create-entity-title-components.ts
  packages/amplication-data-service-generator/src/admin/entity/entity-create-component/create-entity-create-component.ts
  packages/amplication-data-service-generator/src/admin/entity/entity-edit-component/create-edit-entity-component.ts
  packages/amplication-data-service-generator/src/admin/entity/entity-list-component/create-entity-list-component.ts
  packages/amplication-data-service-generator/src/admin/entity/entity-show-component/create-entity-show-component.ts
  packages/amplication-data-service-generator/src/admin/entity/entity-title-component/create-entity-title-component.ts
  packages/amplication-data-service-generator/src/create-data-service-impl.ts
  packages/amplication-data-service-generator/src/dsg-context.ts
  packages/amplication-data-service-generator/src/plugin-wrapper.ts
  packages/amplication-data-service-generator/src/register-plugin.ts
  packages/amplication-data-service-generator/src/server/auth/createAuth.ts
  packages/amplication-data-service-generator/src/server/create-server.ts
  packages/amplication-data-service-generator/src/server/resource/controller/create-controller.ts
  packages/amplication-data-service-generator/src/server/resource/controller/create-data-mapping.ts
  packages/amplication-data-service-generator/src/server/resource/controller/create-select.spec.ts
  packages/amplication-data-service-generator/src/server/resource/controller/create-select.ts
  packages/amplication-data-service-generator/src/server/resource/create-dtos.ts
  packages/amplication-data-service-generator/src/server/resource/create-resource.ts
  packages/amplication-data-service-generator/src/server/resource/dto/create-create-input.ts
  packages/amplication-data-service-generator/src/server/resource/dto/create-dto-module.ts
  packages/amplication-data-service-generator/src/server/resource/dto/create-entity-dto.ts
  packages/amplication-data-service-generator/src/server/resource/dto/create-input.ts
  packages/amplication-data-service-generator/src/server/resource/dto/create-update-input.ts
  packages/amplication-data-service-generator/src/server/resource/dto/create-where-input.ts
  packages/amplication-data-service-generator/src/server/resource/dto/create-where-unique-input.ts
  packages/amplication-data-service-generator/src/server/resource/dto/graphql/create/create-create-args.ts
  packages/amplication-data-service-generator/src/server/resource/dto/graphql/delete/create-delete-args.ts
  packages/amplication-data-service-generator/src/server/resource/dto/graphql/entity-list-relation-filter/create-entity-list-relation-filter.ts
  packages/amplication-data-service-generator/src/server/resource/dto/graphql/find-many/create-find-many-args.ts
  packages/amplication-data-service-generator/src/server/resource/dto/graphql/find-one/create-find-one-args.ts
  packages/amplication-data-service-generator/src/server/resource/dto/graphql/order-by-input/order-by-input.ts
  packages/amplication-data-service-generator/src/server/resource/dto/graphql/update/create-update-args.ts
  packages/amplication-data-service-generator/src/server/resource/dto/nested-input-dto/create-nested-input-dto.spec.ts
  packages/amplication-data-service-generator/src/server/resource/dto/nested-input-dto/create-nested-input-dto.ts
  packages/amplication-data-service-generator/src/server/resource/dto/nested-input-dto/create-nested/create-create-nested-many-without-input.ts
  packages/amplication-data-service-generator/src/server/resource/dto/nested-input-dto/update-nested/create-update-many-without-input.ts
  packages/amplication-data-service-generator/src/server/resource/dto/nestjs-graphql.util.ts
  packages/amplication-data-service-generator/src/server/resource/resolver/create-resolver.ts
  packages/amplication-data-service-generator/src/server/resource/service/create-service.ts
  packages/amplication-data-service-generator/src/server/seed/create-seed.ts
  packages/amplication-data-service-generator/src/util/ast.ts
  packages/amplication-data-service-generator/src/util/entity.ts
Labels: @amplication/data-service-generator, 0.16

#3729 Style/project navigation
  packages/amplication-client/src/Workspaces/WorkspaceHeader/WorkspaceHeader.scss
  packages/amplication-client/src/Workspaces/WorkspaceHeader/WorkspaceHeader.tsx
Labels: type: style

#3734 Main feature branch - Plugins
  packages/amplication-cli/src/models.ts
  packages/amplication-client/src/Plugins/InstalledPlugins.tsx
  packages/amplication-client/src/Plugins/PluginTree.scss
  packages/amplication-client/src/Plugins/PluginTree.tsx
  packages/amplication-client/src/Plugins/PluginsCatalog.tsx
  packages/amplication-client/src/Plugins/PluginsCatalogItem.scss
  packages/amplication-client/src/Plugins/PluginsCatalogItem.tsx
  packages/amplication-client/src/Plugins/PluginsPage.tsx
  packages/amplication-client/src/Plugins/hooks/usePlugins.ts
  packages/amplication-client/src/Plugins/queries/pluginsQueries.ts
  packages/amplication-client/src/Resource/resourceMenuUtils.ts
  packages/amplication-client/src/models.ts
  packages/amplication-client/src/routes/resourceRoutes.tsx
  packages/amplication-code-gen-types/src/code-gen-types.ts
  packages/amplication-code-gen-types/src/models.ts
  packages/amplication-code-gen-types/src/plugins-types.ts
  packages/amplication-data-service-generator/package-lock.json
  packages/amplication-data-service-generator/package.json
  packages/amplication-data-service-generator/src/create-data-service-impl.ts
  packages/amplication-data-service-generator/src/create-data-service-worker.ts
  packages/amplication-data-service-generator/src/create-data-service.ts
  packages/amplication-data-service-generator/src/models.ts
  packages/amplication-data-service-generator/src/register-plugin.ts
  packages/amplication-data-service-generator/src/version.ts
  packages/amplication-git-pull-request-service/src/models.ts
  packages/amplication-prisma-db/prisma/migrations/20220906122818_block_plugin_installation/migration.sql
  packages/amplication-prisma-db/prisma/schema.prisma
  packages/amplication-server/src/core/block/block.service.ts
  packages/amplication-server/src/core/build/build.module.ts
  packages/amplication-server/src/core/build/build.service.ts
  packages/amplication-server/src/core/core.module.ts
  packages/amplication-server/src/core/pluginInstallation/dto/CreatePluginInstallationArgs.ts
  packages/amplication-server/src/core/pluginInstallation/dto/FindManyPluginInstallationArgs.ts
  packages/amplication-server/src/core/pluginInstallation/dto/PluginInstallation.ts
  packages/amplication-server/src/core/pluginInstallation/dto/PluginInstallationCreateInput.ts
  packages/amplication-server/src/core/pluginInstallation/dto/PluginInstallationOrderByInput.ts
  packages/amplication-server/src/core/pluginInstallation/dto/PluginInstallationUpdateInput.ts
  packages/amplication-server/src/core/pluginInstallation/dto/PluginInstallationWhereInput.ts
  packages/amplication-server/src/core/pluginInstallation/dto/UpdatePluginInstallationArgs.ts
  packages/amplication-server/src/core/pluginInstallation/pluginInstallation.module.ts
  packages/amplication-server/src/core/pluginInstallation/pluginInstallation.resolver.ts
  packages/amplication-server/src/core/pluginInstallation/pluginInstallation.service.ts
  packages/amplication-server/src/enums/EnumBlockType.ts
  packages/amplication-server/src/schema.graphql
Labels: do not merge

#3755 External Apis data from server to dsg
  packages/amplication-cli/src/models.ts
  packages/amplication-client/src/models.ts
  packages/amplication-code-gen-types/src/code-gen-types.ts
  packages/amplication-code-gen-types/src/dsg-resource-data.ts
  packages/amplication-code-gen-types/src/index.ts
  packages/amplication-code-gen-types/src/models.ts
  packages/amplication-data-service-generator/package-lock.json
  packages/amplication-data-service-generator/package.json
  packages/amplication-data-service-generator/scripts/generate-test-data-service.ts
  packages/amplication-data-service-generator/src/create-data-service-impl.ts
  packages/amplication-data-service-generator/src/create-data-service-worker.ts
  packages/amplication-data-service-generator/src/create-data-service.ts
  packages/amplication-data-service-generator/src/models.ts
  packages/amplication-data-service-generator/src/tests/create-data-service-custom-path.spec.ts
  packages/amplication-data-service-generator/src/tests/create-data-service-without-graphql.spec.ts
  packages/amplication-data-service-generator/src/tests/create-data-service-without-restApi.spec.ts
  packages/amplication-data-service-generator/src/tests/create-data-service.spec.ts
  packages/amplication-git-pull-request-service/src/models.ts
  packages/amplication-server/src/core/build/build.module.ts
  packages/amplication-server/src/core/build/build.service.spec.ts
  packages/amplication-server/src/core/build/build.service.ts
  packages/amplication-server/src/core/resource/dto/ResourceWhereInput.ts
  packages/amplication-server/src/core/serviceTopics/dto/messagePattern/EnumMessagePatternConnectionOptions.ts
  packages/amplication-server/src/core/serviceTopics/dto/messagePattern/MessagePattern.ts
  packages/amplication-server/src/schema.graphql
Labels: do not merge

#3738 User id added to generated token (base token & jwt token)
  packages/amplication-data-service-generator/src/server/auth/token/basicToken.service.template.ts
  packages/amplication-data-service-generator/src/server/auth/token/jwtToken.service.template.ts
  packages/amplication-data-service-generator/src/server/static/src/auth/ITokenService.ts
  packages/amplication-data-service-generator/src/server/static/src/auth/UserInfo.ts
  packages/amplication-data-service-generator/src/server/static/src/auth/auth.service.ts
  packages/amplication-data-service-generator/src/server/static/src/tests/auth/constants.ts
  packages/amplication-data-service-generator/src/server/static/src/tests/auth/jwt/jwt.strategy.spec.ts
  packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service-custom-path.spec.ts.snap
  packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service-without-graphql.spec.ts.snap
  packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service-without-restApi.spec.ts.snap
  packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
Labels: PR: needs review

#3785 Refactor plugin wrapper on existing events
  packages/amplication-code-gen-types/src/code-gen-types.ts
  packages/amplication-code-gen-types/src/plugin-events-params.ts
  packages/amplication-code-gen-types/src/plugin-events.ts
  packages/amplication-code-gen-types/src/plugins-types.ts
  packages/amplication-data-service-generator/src/admin/app/create-app.ts
  packages/amplication-data-service-generator/src/admin/constants.ts
  packages/amplication-data-service-generator/src/admin/create-admin.ts
  packages/amplication-data-service-generator/src/create-data-service-impl.ts
  packages/amplication-data-service-generator/src/dsg-context.ts
  packages/amplication-data-service-generator/src/server/auth/createAuth.ts
  packages/amplication-data-service-generator/src/server/constants.ts
  packages/amplication-data-service-generator/src/server/create-server.ts
  packages/amplication-data-service-generator/src/server/docker-compose/create-docker-compose-db.ts
  packages/amplication-data-service-generator/src/server/docker-compose/create-docker-compose.ts
  packages/amplication-data-service-generator/src/server/resource/controller/create-controller.ts
  packages/amplication-data-service-generator/src/server/resource/create-resource.ts
  packages/amplication-data-service-generator/src/server/resource/module/create-module.ts
  packages/amplication-data-service-generator/src/server/resource/resolver/create-resolver.ts
  packages/amplication-data-service-generator/src/server/resource/service/create-service.ts
  packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service-custom-path.spec.ts.snap
Labels: PR: needs fixes

#3747 fix: add updateProject method in project service
  packages/amplication-client/src/Resource/ResourceForm.tsx
  packages/amplication-client/src/Resource/resourceSettings/DirectoriesProjectConfigurationSettingsForm.tsx
  packages/amplication-client/src/Workspaces/WorkspaceHeader/HeaderMenuStaticOptions.tsx
  packages/amplication-client/src/Workspaces/WorkspaceHeader/WorkspaceHeader.tsx
  packages/amplication-client/src/Workspaces/hooks/useProjectSelector.ts
  packages/amplication-design-system/package.json
  packages/amplication-server/src/core/project/dto/ProjectUpdateInput.ts
  packages/amplication-server/src/core/project/dto/UpdateProjectArgs.ts
  packages/amplication-server/src/core/project/project.resolver.ts
  packages/amplication-server/src/core/project/project.service.ts
  packages/amplication-server/src/core/resource/resource.service.ts
  packages/amplication-server/src/schema.graphql
Labels: PR: needs fixes
