Repository amplication/amplication, pull requests merged in 2023-02, with the labels that each got.

#5131 chore: enable nx distributed cache
  nx.json
Labels: type: chore, CI\CD

#5203 refactor(scripts): merge duplicate scripts directory and change references
  README.md
  libs/util/code-gen-utils/project.json
  package.json
  scripts/publish.mjs
  scripts/setup.ts
Labels: type: enhancement

#5265 fix(client): remove full-screen-loader from App and implement in Work…
  packages/amplication-client/src/App.tsx
  packages/amplication-design-system/src/components/Loader/FullScreenLoader.tsx
Labels: type: bug
